# Data Description
- Author: RUEI-HSIANG, CHANG (B12303030)，Codex 協助
- Date first created: 20261019
- Background: 新找到的競選／政黨人物頁，補學歷、一般經歷與人物入口；保留本輪前的資料版本。
- Unit of observation: 證據表＝候選人×欄位×來源；人物頁表＝候選人；主表＝候選人；欄位清單＝候選人×欄位。
- Sample period: 2026-10-19 保存與整理的來源快照，不代表所有經歷發生於本日。
- Known issues: 新人物頁僅以姓名＋縣市＋公職唯一對應，尚未完成獨立身分交叉核對；來源申報學歷不等於認證學位；「在學／博士班／研究所／肄業」均保留原文，未自動分級。一般經歷不是行政經歷，不把2022當選或歷任直接推定2026仍在任。原810位沒有MOI對應頁者中25位取得新人物頁，仍785位未有這兩批人物頁；25位生日及性別仍未補齊。
- Definition for each variable:

  - 共通 candidate_key、candidate_name、county_city、office_type：研究名冊識別與人名、公職、縣市。
  - 證據表 field、value_raw：人物頁入口／學歷／一般經歷／明列曾參選的原文或0值；profile_url 入口與背景欄位分列。
  - source_url、source_file、source_sha256、source_locator：原文出處、保存檔與定位。evidence_tier：競選／政黨申報，未獨立認證。identity_status：唯一姓名＋縣市＋公職對應、仍待獨立身分核對。observation_date：本次整理日。
  - 人物頁表 profile_url、education_raw、experience_raw：可點選頁與未分級的學經歷原文；birth_date、sex 留空；對應 status 表示背景區塊未列示。previous_moi_profile_present 表示是否已在原692筆人物頁表，不等於現任或已認證。
  - 主表 registration_* 為原登記出處；party_registration_raw 原推薦政黨；qualification_* 保留既有資格狀態、未在本輪升級；sample_inclusion 保留組內規則待定；directory_lead_count 保留舊名錄計數。各 *_status 為目前線索狀態，不能當作分析值。
  - 欄位清單 field、status、existing_value、evidence、note、next_source、updated_date：欄位、查核狀態、來源值、出處、限制、下一步與日期；只更新精確對應的profile／education及有明文依據的first_time欄位。

- Data path / Role / SHA-256:
  - data/processed/candidate_background_evidence_round3_20261019.csv / collection evidence or inventory / 5195c8b1902f8228f8001f3986e7d2d433b0662e2d5a069bdd015a491d4bf663 (146 列)
  - data/processed/council_campaign_profiles_20261019.csv / collection evidence or inventory / 28fed78971de8248fab91ce32c889851ae2df17de303c2ea25b3e0bb9778ae00 (28 列)
  - data/processed/candidate_master_reviewed_round3_20261019.csv / collection evidence or inventory / b5656f830d321c7806d3742175f7a0761699f59f3ecd442cb9a5b3310b1c8840 (1583 列)
  - data/processed/candidate_fields_reviewed_round3_20261019.csv / collection evidence or inventory / 72c245eedc0396077cf2fa5c0e821f68c41c9d566d10242b3bb2ba5b2e615144 (31660 列)
- Source data: data/raw/round3_20261019/capture_manifest.json（逐來源hash，原始文件 data/raw/social_sources_20261019_documentation.ipynb）；上游 candidate_master_reviewed_20261019.csv、candidate_fields_reviewed_20261019.csv、candidate_profile_leads_20261019.csv。
- Processing code: data/code/prepare_background_round3_20261019.ipynb（固定各輸入SHA-256）。
- Role: collection evidence / inventory；不是模型已完成的分析輸入。
- Verification status: 下列程式從保存檔核對hash、列數、鍵與未改欄位；保留原始來源未覆寫。
- Downstream analysis input: 需先處理身分、學位完成、生日與性別缺口後再選擇分析樣本；不得直接以status當作屬性值。

In [1]:
from pathlib import Path
import json,hashlib,pandas as pd
ROOT=next(p for p in [Path.cwd(),*Path.cwd().parents] if (p/'AGENTS.md').exists() and (p/'templates').is_dir())
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
FRAMES={}

## Change for Your Own Data

In [2]:
assert sha(ROOT/'data/processed/candidate_background_evidence_round3_20261019.csv')=='5195c8b1902f8228f8001f3986e7d2d433b0662e2d5a069bdd015a491d4bf663'
FRAMES['data/processed/candidate_background_evidence_round3_20261019.csv']=pd.read_csv(ROOT/'data/processed/candidate_background_evidence_round3_20261019.csv',dtype=str).fillna('')
assert len(FRAMES['data/processed/candidate_background_evidence_round3_20261019.csv'])==146
assert sha(ROOT/'data/processed/council_campaign_profiles_20261019.csv')=='28fed78971de8248fab91ce32c889851ae2df17de303c2ea25b3e0bb9778ae00'
FRAMES['data/processed/council_campaign_profiles_20261019.csv']=pd.read_csv(ROOT/'data/processed/council_campaign_profiles_20261019.csv',dtype=str).fillna('')
assert len(FRAMES['data/processed/council_campaign_profiles_20261019.csv'])==28
assert sha(ROOT/'data/processed/candidate_master_reviewed_round3_20261019.csv')=='b5656f830d321c7806d3742175f7a0761699f59f3ecd442cb9a5b3310b1c8840'
FRAMES['data/processed/candidate_master_reviewed_round3_20261019.csv']=pd.read_csv(ROOT/'data/processed/candidate_master_reviewed_round3_20261019.csv',dtype=str).fillna('')
assert len(FRAMES['data/processed/candidate_master_reviewed_round3_20261019.csv'])==1583
assert sha(ROOT/'data/processed/candidate_fields_reviewed_round3_20261019.csv')=='72c245eedc0396077cf2fa5c0e821f68c41c9d566d10242b3bb2ba5b2e615144'
FRAMES['data/processed/candidate_fields_reviewed_round3_20261019.csv']=pd.read_csv(ROOT/'data/processed/candidate_fields_reviewed_round3_20261019.csv',dtype=str).fillna('')
assert len(FRAMES['data/processed/candidate_fields_reviewed_round3_20261019.csv'])==31660

## Summary

In [3]:
for path,d in FRAMES.items():print(path,{'rows':len(d),'columns':len(d.columns)})

data/processed/candidate_background_evidence_round3_20261019.csv {'rows': 146, 'columns': 13}
data/processed/council_campaign_profiles_20261019.csv {'rows': 28, 'columns': 15}
data/processed/candidate_master_reviewed_round3_20261019.csv {'rows': 1583, 'columns': 34}
data/processed/candidate_fields_reviewed_round3_20261019.csv {'rows': 31660, 'columns': 11}

### Sample

In [4]:
for path,d in FRAMES.items():
 print(path);display(d.head(10))

data/processed/candidate_background_evidence_round3_20261019.csv

,candidate_key,candidate_name,county_city,office_type,field,value_raw,source_url,source_file,source_sha256,source_locator,evidence_tier,identity_status,observation_date
0,2026|直轄市議員|臺北市第1選舉區|謝閔弘,謝閔弘,臺北市,直轄市議員,profile_url,https://www.taiwangogo.tw/hsieh-min-hung/,https://www.taiwangogo.tw/hsieh-min-hung/,data/raw/round3_20261019/50b22ce8b7a3e6fd7409....,7b6f03fafac81cc5a11e9cf57b85912efee9bc2c304fff...,candidate card name/city/office + candidate de...,campaign_or_party_declared_not_independent_cer...,unique_name_county_office_match_pending_additi...,2026-10-19
1,2026|直轄市議員|臺北市第1選舉區|謝閔弘,謝閔弘,臺北市,直轄市議員,education,石牌國小 | 明德國中 | 建國中學 | 國立臺灣師範大學東亞學系在學,https://www.taiwangogo.tw/hsieh-min-hung/,data/raw/round3_20261019/50b22ce8b7a3e6fd7409....,7b6f03fafac81cc5a11e9cf57b85912efee9bc2c304fff...,.cv-biocard h4=學歷 + sibling ul li,campaign_or_party_declared_not_independent_cer...,unique_name_county_office_match_pending_additi...,2026-10-19
2,2026|直轄市議員|臺北市第1選舉區|謝閔弘,謝閔弘,臺北市,直轄市議員,experience,家教、補習班老師 | 社交俱樂部負責人 | 2022 臺北市北投區裕民里里長候選人,https://www.taiwangogo.tw/hsieh-min-hung/,data/raw/round3_20261019/50b22ce8b7a3e6fd7409....,7b6f03fafac81cc5a11e9cf57b85912efee9bc2c304fff...,.cv-biocard h4=經歷 + sibling ul li,campaign_or_party_declared_not_independent_cer...,unique_name_county_office_match_pending_additi...,2026-10-19
3,2026|直轄市議員|臺北市第2選舉區|吳欣岱,吳欣岱,臺北市,直轄市議員,profile_url,https://www.taiwangogo.tw/wu-hsin-tai/,https://www.taiwangogo.tw/wu-hsin-tai/,data/raw/round3_20261019/d08b17c685eeeea3a02d....,415684bda08a2ac26c27e04c707c48bdafd3f45f7ff517...,candidate card name/city/office + candidate de...,campaign_or_party_declared_not_independent_cer...,unique_name_county_office_match_pending_additi...,2026-10-19
4,2026|直轄市議員|臺北市第2選舉區|吳欣岱,吳欣岱,臺北市,直轄市議員,education,國立陽明大學醫學系,https://www.taiwangogo.tw/wu-hsin-tai/,data/raw/round3_20261019/d08b17c685eeeea3a02d....,415684bda08a2ac26c27e04c707c48bdafd3f45f7ff517...,.cv-biocard h4=學歷 + sibling ul li,campaign_or_party_declared_not_independent_cer...,unique_name_county_office_match_pending_additi...,2026-10-19
5,2026|直轄市議員|臺北市第2選舉區|吳欣岱,吳欣岱,臺北市,直轄市議員,experience,屏東醫院主治醫師 | 衛生福利部台中醫院住院醫師 | 豐原醫院不分科住院醫師 | 台中醫院外...,https://www.taiwangogo.tw/wu-hsin-tai/,data/raw/round3_20261019/d08b17c685eeeea3a02d....,415684bda08a2ac26c27e04c707c48bdafd3f45f7ff517...,.cv-biocard h4=經歷 + sibling ul li,campaign_or_party_declared_not_independent_cer...,unique_name_county_office_match_pending_additi...,2026-10-19
6,2026|直轄市議員|臺北市第3選舉區|鄧樂強,鄧樂強,臺北市,直轄市議員,profile_url,https://www.taiwangogo.tw/teng-le-chiang/,https://www.taiwangogo.tw/teng-le-chiang/,data/raw/round3_20261019/38c8a89a30712044dac9....,7eabcd2b5efce0e00b35634d4d8bbe32d6831fe0efe1f5...,candidate card name/city/office + candidate de...,campaign_or_party_declared_not_independent_cer...,unique_name_county_office_match_pending_additi...,2026-10-19
7,2026|直轄市議員|臺北市第3選舉區|鄧樂強,鄧樂強,臺北市,直轄市議員,education,國立台灣大學法律系 | 國立銘傳大學企業管理研究所,https://www.taiwangogo.tw/teng-le-chiang/,data/raw/round3_20261019/38c8a89a30712044dac9....,7eabcd2b5efce0e00b35634d4d8bbe32d6831fe0efe1f5...,.cv-biocard h4=學歷 + sibling ul li,campaign_or_party_declared_not_independent_cer...,unique_name_county_office_match_pending_additi...,2026-10-19
8,2026|直轄市議員|臺北市第3選舉區|鄧樂強,鄧樂強,臺北市,直轄市議員,experience,空軍上校 | 國安系統 | 中華動態競爭戰略發展學會財務長,https://www.taiwangogo.tw/teng-le-chiang/,data/raw/round3_20261019/38c8a89a30712044dac9....,7eabcd2b5efce0e00b35634d4d8bbe32d6831fe0efe1f5...,.cv-biocard h4=經歷 + sibling ul li,campaign_or_party_declared_not_independent_cer...,unique_name_county_office_match_pending_additi...,2026-10-19
9,2026|直轄市議員|臺北市第4選舉區|李惠暄,李惠暄,臺北市,直轄市議員,profile_url,https://www.taiwangogo.tw/li-hui-hsuan/,https://www.taiwangogo.tw/li-hui-hsuan/,data/raw/round3_20261019/8853da31089f05ed88af....,d40afcb8fe98e5ec47b97ba1ea68f1568d80e9cf7047a9...,candidate card name/city/office + candidate de...,campaign_or_party_declared_not_independent_cer...,unique_name_county_office_match_pending_additi...,2026-10-19

data/processed/council_campaign_profiles_20261019.csv

,candidate_key,candidate_name,county_city,office_type,profile_url,education_raw,experience_raw,birth_date,sex,birth_date_status,sex_status,identity_status,previous_moi_profile_present,source_file,source_sha256
0,2026|直轄市議員|臺北市第1選舉區|謝閔弘,謝閔弘,臺北市,直轄市議員,https://www.taiwangogo.tw/hsieh-min-hung/,石牌國小 | 明德國中 | 建國中學 | 國立臺灣師範大學東亞學系在學,家教、補習班老師 | 社交俱樂部負責人 | 2022 臺北市北投區裕民里里長候選人,,,not_listed_in_background_block,not_listed_in_background_block,unique_name_county_office_match_pending_additi...,False,data/raw/round3_20261019/50b22ce8b7a3e6fd7409....,7b6f03fafac81cc5a11e9cf57b85912efee9bc2c304fff...
1,2026|直轄市議員|臺北市第2選舉區|吳欣岱,吳欣岱,臺北市,直轄市議員,https://www.taiwangogo.tw/wu-hsin-tai/,國立陽明大學醫學系,屏東醫院主治醫師 | 衛生福利部台中醫院住院醫師 | 豐原醫院不分科住院醫師 | 台中醫院外...,,,not_listed_in_background_block,not_listed_in_background_block,unique_name_county_office_match_pending_additi...,False,data/raw/round3_20261019/d08b17c685eeeea3a02d....,415684bda08a2ac26c27e04c707c48bdafd3f45f7ff517...
2,2026|直轄市議員|臺北市第3選舉區|鄧樂強,鄧樂強,臺北市,直轄市議員,https://www.taiwangogo.tw/teng-le-chiang/,國立台灣大學法律系 | 國立銘傳大學企業管理研究所,空軍上校 | 國安系統 | 中華動態競爭戰略發展學會財務長,,,not_listed_in_background_block,not_listed_in_background_block,unique_name_county_office_match_pending_additi...,False,data/raw/round3_20261019/38c8a89a30712044dac9....,7eabcd2b5efce0e00b35634d4d8bbe32d6831fe0efe1f5...
3,2026|直轄市議員|臺北市第4選舉區|李惠暄,李惠暄,臺北市,直轄市議員,https://www.taiwangogo.tw/li-hui-hsuan/,天主教輔仁大學法研所博士班（進修中） | 天主教輔仁大學法研所碩士 | 政治大學法律系學士 ...,巨展法律事務所 資深合夥人 | 惠聖法律事務所 所長 | 輔仁大學法務室 主任 | 法律扶助...,,,not_listed_in_background_block,not_listed_in_background_block,unique_name_county_office_match_pending_additi...,False,data/raw/round3_20261019/8853da31089f05ed88af....,d40afcb8fe98e5ec47b97ba1ea68f1568d80e9cf7047a9...
4,2026|直轄市議員|臺北市第5選舉區|王振庭,王振庭,臺北市,直轄市議員,https://www.taiwangogo.tw/wang-chen-ting/,東海大學社會工作學系,8年補教老師 | 5年保險業務主管 | 3年民間清潔隊 | 古亭商圈發展協會常務監事,,,not_listed_in_background_block,not_listed_in_background_block,unique_name_county_office_match_pending_additi...,False,data/raw/round3_20261019/4b68edf3fc599a2eba40....,76665c2bbb9773e04de8899561f744a73f17f22a68ec42...
5,2026|直轄市議員|臺北市第6選舉區|陳峙穎,陳峙穎,臺北市,直轄市議員,https://www.taiwangogo.tw/chen-chih-ying/,輔仁大學經濟系 | 臺北市立中崙高級中學 | 臺北市立實踐國民中學 | 臺北市永建國民小學,2018-2026年 導護志工守護孩童 | 2022-2026年 連任里長(得票較上屆成長8...,,,not_listed_in_background_block,not_listed_in_background_block,unique_name_county_office_match_pending_additi...,False,data/raw/round3_20261019/ea8701d95029e885aad6....,71aa0214f1d255dbeb58a12688b534738682fc73ab867b...
6,2026|直轄市議員|新北市第3選舉區|甘崇緯,甘崇緯,新北市,直轄市議員,https://www.taiwangogo.tw/kan-chung-wei/,國立交通大學多媒體工程所碩士 | 國立中央大學資訊工程學系學士,台灣綠黨共同召集人 | 天下第一台YT/Podcast主持製作人 | 天域科技電玩程式設計師...,,,not_listed_in_background_block,not_listed_in_background_block,unique_name_county_office_match_pending_additi...,False,data/raw/round3_20261019/017cec83ee85a7109e3d....,1c5cb9a08b99504adf537c1e38747105d94bbe88c7b0df...
7,2026|直轄市議員|新北市第4選舉區|陳宛毓,陳宛毓,新北市,直轄市議員,https://www.taiwangogo.tw/chen-wan-yu/,蘆洲成功國小 | 蘆洲國中 | 三重商工 | 國立勤益科技大學 工管系,實驗教育老師十年 | 還路於民行人路權促進會 理事,,,not_listed_in_background_block,not_listed_in_background_block,unique_name_county_office_match_pending_additi...,False,data/raw/round3_20261019/db10af224a42e4e679bb....,af4d38bad23278341e3b756ae2674302c6ce204770967a...
8,2026|直轄市議員|新北市第9選舉區|張佑輔,張佑輔,新北市,直轄市議員,https://www.taiwangogo.tw/chang-yu-fu/,國立成功大學土木工程學系畢業,公共服務類 | 勞動部諮詢委員 | 外籍工作者協會副秘書長 | 台灣二手循環促進協會理事長 ...,,,not_listed_in_background_block,not_listed_in_background_block,unique_name_county_office_match_pending_additi...,False,data/raw/round3_20261019/403b3fd51e7e1255c7da....,30f806b38db8c48dd4dec3aea5eeabb0391763a67c90fe...
9,2026|直轄市議員|新北市第11選舉區|郭書成,郭書成,新北市,直轄市議員,https://www.taiwangogo.tw/kuo-shu-cheng/,台北市立麗山高級中學 | 國立中山大學 劇場藝術學系,獨立村里長學院 共同創辦人 | 獨立村里長協會 理事長 | 國立中山大學學生會 會長 | 行...,,,not_listed_in_background_block,not_listed_in_background_block,unique_name_county_office_match_pending_additi...,False,data/raw/round3_20261019/d100b0b5e9dc46b0eb51....,898d37909e653dd280b72320abd70169d36221c8c1a89f...

data/processed/candidate_master_reviewed_round3_20261019.csv

,candidate_key,candidate_name,office_type,county_city,electoral_district,party_registration_raw,registration_source,registration_source_file,registration_source_page,qualification_inherited,...,Threads_status,posts_Facebook_status,posts_Instagram_status,posts_Threads_status,followers_status,policy_text_status,visual_status,political_family_status,administrative_experience_status,qualification_status
0,2026-C1-001,郭璽,直轄市長,臺北市,,台灣麻將最大黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
1,2026-C1-002,沈伯洋,直轄市長,臺北市,,民主進步黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,部分原文已保存，尚未政策編碼,未查找,未查找,未查找,官方內文待重新核對
2,2026-C1-003,蕭文乾,直轄市長,臺北市,,臺灣SoR無法黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
3,2026-C1-004,唐新民,直轄市長,臺北市,,三勢團結促進聯盟,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
4,2026-C1-005,蔣萬安,直轄市長,臺北市,,中國國民黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
5,2026-C1-006,林志成,直轄市長,臺北市,,無,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
6,2026-C1-007,蘇巧慧,直轄市長,新北市,,民主進步黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,部分原文已保存，尚未政策編碼,未查找,未查找,未查找,官方內文待重新核對
7,2026-C1-008,李四川,直轄市長,新北市,,中國國民黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
8,2026-C1-009,蘇輝湟,直轄市長,新北市,,無,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
9,2026-C1-010,張善政,直轄市長,桃園市,,中國國民黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對

data/processed/candidate_fields_reviewed_round3_20261019.csv

,candidate_key,candidate_name,office_type,county_city,field,status,existing_value,evidence,note,next_source,updated_date
0,2026-C1-001,郭璽,直轄市長,臺北市,sex,已有資料，待來源複核,男,https://db.cec.gov.tw/,dob_corroborated_by_media,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
1,2026-C1-001,郭璽,直轄市長,臺北市,birth_date,已有資料，待來源複核,1958-08-31,https://db.cec.gov.tw/,CEC_name_and_birth_date_corroborated_by_CNA,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
2,2026-C1-001,郭璽,直轄市長,臺北市,education,已有資料，待來源複核,大學,,歷史公報或媒體補充，非2026學歷認證,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
3,2026-C1-001,郭璽,直轄市長,臺北市,incumbency,既有搜尋後仍缺，待補查,,,,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
4,2026-C1-001,郭璽,直轄市長,臺北市,first_time_this_office,既有搜尋後仍缺，待補查,,,0=有過參選證據；空白不表示首次。此處沿用既有表。,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
5,2026-C1-001,郭璽,直轄市長,臺北市,first_time_any_office,已有資料，待來源複核,0,https://db.cec.gov.tw/,0=有過參選證據；空白不表示首次。此處沿用既有表。,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
6,2026-C1-001,郭璽,直轄市長,臺北市,profile,既有搜尋後仍缺，待補查,,,,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
7,2026-C1-001,郭璽,直轄市長,臺北市,website,既有搜尋後仍缺，待補查,,,,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
8,2026-C1-001,郭璽,直轄市長,臺北市,Facebook,尚未驗證，不代表無帳號,,,,官方人物頁／競選網站交叉連結,2026-10-19
9,2026-C1-001,郭璽,直轄市長,臺北市,Instagram,尚未驗證，不代表無帳號,,,,官方人物頁／競選網站交叉連結,2026-10-19

### Summary Stats

In [5]:
e,p,m,f=FRAMES.values()
display(e.field.value_counts().to_frame('證據列數'));display(p.previous_moi_profile_present.value_counts().to_frame('人物數'));display(p[['candidate_name','education_raw','experience_raw']])

                        證據列數
field
profile_url               47
education                 47
experience                47
first_time_any_office      4
first_time_this_office     1

                              人物數
previous_moi_profile_present
False                          25
True                            3

,candidate_name,education_raw,experience_raw
0,謝閔弘,石牌國小 | 明德國中 | 建國中學 | 國立臺灣師範大學東亞學系在學,家教、補習班老師 | 社交俱樂部負責人 | 2022 臺北市北投區裕民里里長候選人
1,吳欣岱,國立陽明大學醫學系,屏東醫院主治醫師 | 衛生福利部台中醫院住院醫師 | 豐原醫院不分科住院醫師 | 台中醫院外...
2,鄧樂強,國立台灣大學法律系 | 國立銘傳大學企業管理研究所,空軍上校 | 國安系統 | 中華動態競爭戰略發展學會財務長
3,李惠暄,天主教輔仁大學法研所博士班（進修中） | 天主教輔仁大學法研所碩士 | 政治大學法律系學士 ...,巨展法律事務所 資深合夥人 | 惠聖法律事務所 所長 | 輔仁大學法務室 主任 | 法律扶助...
4,王振庭,東海大學社會工作學系,8年補教老師 | 5年保險業務主管 | 3年民間清潔隊 | 古亭商圈發展協會常務監事
5,陳峙穎,輔仁大學經濟系 | 臺北市立中崙高級中學 | 臺北市立實踐國民中學 | 臺北市永建國民小學,2018-2026年 導護志工守護孩童 | 2022-2026年 連任里長(得票較上屆成長8...
6,甘崇緯,國立交通大學多媒體工程所碩士 | 國立中央大學資訊工程學系學士,台灣綠黨共同召集人 | 天下第一台YT/Podcast主持製作人 | 天域科技電玩程式設計師...
7,陳宛毓,蘆洲成功國小 | 蘆洲國中 | 三重商工 | 國立勤益科技大學 工管系,實驗教育老師十年 | 還路於民行人路權促進會 理事
8,張佑輔,國立成功大學土木工程學系畢業,公共服務類 | 勞動部諮詢委員 | 外籍工作者協會副秘書長 | 台灣二手循環促進協會理事長 ...
9,郭書成,台北市立麗山高級中學 | 國立中山大學 劇場藝術學系,獨立村里長學院 共同創辦人 | 獨立村里長協會 理事長 | 國立中山大學學生會 會長 | 行...
10,吳程澤,文藻外語大學 國際事務系 國際政治、文化組 | 基隆市天主教聖心高中,奧特邦媒體集團/汽車鑑賞誌 文字/攝影編輯 | 大葉高島屋百貨公司 行銷企劃 一級專員 | ...
11,沈佩玲,台大電子工程所碩士 | 交大電子工程學系 | 中山女中,小民參政歐巴桑聯盟 政黨發言人 | 桃園市政府公園適性發展審議會委員 | 創新教育教師 | ...
12,李雅芬,長庚科技大學 護理系 | 台南護理專科學校 護理系,東元醫院資深麻醉護理師 | 新竹市議員蔡惠婷辦公室主任 | 國小營養午餐家長委員 | 華人泌...
13,張育慈,台灣大學新聞研究所 | 中央大學客家社會文化碩士 | 元智大學社會暨政策科學學士 | 竹北高...,時代力量新聞部主任 | 新竹縣議會議員助理 | 新竹縣政府民政處 | 壯闊台灣倡議專員
14,林裙靜,國立中央大學客家研究博士班 | 國立中央大學客家社會與政策碩士 | 中國文化大學中文系文藝創...,2024 台灣綠黨共同召集人 | 2023 勾筆工作室主理人 | 2022 竹東鎮第四選區鎮...
15,蔡惠婷,台東大學語文教育系,2022-2026新竹市第11屆議員 | 2018-2022新竹市第10屆議員 | 2006...
16,林彥甫,美國紐約州立大學公共行政碩士 | 清華大學計量財務金融學士,時代力量新竹市議會黨團 總召 | 國際扶輪新竹陽光扶輪社 服務計畫主委 | 荷蘭村C區第 2...
17,廖子齊,國立台灣大學法律系司法組學士 | 國立新竹女子高級中學 | 苗栗縣君毅國中 | 新竹市香山區...,第10、11屆新竹市議員 | 竹塹文教基金會 理事 | 竹塹文化資產行動 前線成員 | 英國...
18,吳翌立,康寧醫護暨管理專科學校 | 麗山國中 | 麗山國小,議員辦公室主任 | 新光醫院護理師 | 主人兒童托育中心護理師
19,蔡佩珊,政治大學廣播電視學系碩士班 | 政治大學廣播電視學系大學部 | 台中女中,國際貿易-外貿協會西語組 | 行銷企畫-日商廣告代理商 | 教育專業-資深自學生家長 | 婦...
20,鄒明諺,國立中正大學政治學系 | 臺中一中 | 光榮國中 | 永隆國小,時代力量台中黨部 執行長 | 終結大里醫療焚化爐污染 發起人 | 促使霧峰大型殯葬區撤案 發...
21,陳玥妗,嘉義大學農業生物科技研究所,中研院南部生物科技研究中心研究助理 | 實驗教育師資（公民、科學） | 國中理化代課老師 |...
22,林詩涵,暨南國際大學社會政策與社會工作學系 | 台中二中 | 曉明女中初中部,小民參政歐巴桑聯盟黨召集人 | 有限責任台灣友善書業供給合作社理事 | 台灣圖書室文化協會常...
23,吳依潔,高雄女中 | 台大心理系畢業 | 台大心理系碩士班,台灣基進台南黨部主委 | 崑山國小家長會顧問 | 第52屆台大研究生協會會長
24,薛兆基,舊城國小 | 大義國中 | 鳳山高中 | 中興大學 | 高雄大學IEMBA,高雄市政府研考會委員 | 民報南部業務經理兼記者 | 自立晚報南區處長兼特派員 | 高雄市公...
25,于仙玲,高雄市鳳山高中 | 國立成功大學護理學系,高雄市榮民總醫院外科病房護理師 | 高雄市阮綜合醫院門診護理師 | abc牙醫植牙中心開刀房...
26,劉仲書,亞洲大學財經法律系（肄業） | 國立宜蘭高中 | 宜蘭縣復興國中 | 宜蘭縣力行國小 | 私...,臺鐵列車長 | 高鐵延伸宜蘭監督聯盟發言人 | 臺鐵產業工會常務理事 | 天下雜誌獨立評論專...
27,孟繁嘉,東海大學 社會工作學系 學士,台灣露德協會 花東分辦／洄瀾居所負責人 | 花蓮禪光育幼院 前院長

### Assertions

In [6]:
e,p,m,f=FRAMES.values()
assert m.candidate_key.is_unique and len(m)==1583
assert len(f)==31660 and not f.duplicated(['candidate_key','field']).any()
assert not e.duplicated(['candidate_key','field','source_url']).any()
assert p.candidate_key.is_unique and p.candidate_key.isin(m.candidate_key).all()
assert e.candidate_key.isin(m.candidate_key).all()
assert p.birth_date.eq('').all() and p.sex.eq('').all()
assert int(p.previous_moi_profile_present.eq('False').sum())==25
assert '在學' in p[p.candidate_name.eq('謝閔弘')].iloc[0].education_raw
old=pd.read_csv(ROOT/'data/processed/candidate_fields_reviewed_20261019.csv',dtype=str).fillna('')
keys=['candidate_key','field']
a=f.set_index(keys);b=old.set_index(keys)
for field in ['sex','birth_date','incumbency','administrative_experience']:
 pd.testing.assert_frame_equal(a.xs(field,level='field'),b.xs(field,level='field'))
print('PASS：資料列數／鍵／來源追溯／25個新增頁面／在學原文保留；未動生日、性別、現任與行政經歷。')

PASS：資料列數／鍵／來源追溯／25個新增頁面／在學原文保留；未動生日、性別、現任與行政經歷。