# Data Description
- Author: RUEI-HSIANG, CHANG（B12303030；AI協助）
- Date first created: 20261019
- Background: 第六輪候選人資料整合：18人背景來源原文（其中16個新人物頁）、4人新增官方生日支持、3人新增歷史申報性別、5人補非首次任何民選公職，並整合29組社群入口與81人首長比對；另續補陳重嘉與温世政完整生日（後者專業學會來源非政府）；1162列第三方履歷主張保留為待查。
- Unit of observation: master／council／mayor／profile為候選人；fields為候選人×欄位；社群工作單為候選人×平台；帳號證據為候選人×平台×來源×URL；背景證據為候選人×欄位×來源；worklist為上游履歷主張×來源。
- Sample period: 2026候選人登記名冊為框架。背景引用2014、2018、2020、2022、2024歷史申報及2026擷取的人物頁，不當作同時期的戶籍或學位認證；貼文窗口未啟用。
- Known issues: 仍733人缺目前幾類人物頁；歷史姓名匹配需身分證據。692人的2022歷史生日／性別序列不混入本輪跨年資料；4人額外官方生日與3人性別分欄。林德建未取得明載性別，維持未知。政黨／競選頁的履歷為自述、學位未認證。524人的1162列主張全未核實，不以姓名出現在整頁文字當作完成。社群目標內容未全面核對，貼文、窗口量及追蹤數缺漏不是0。首長名錄不是停職／代理法律狀態全查；宜蘭另記林茂盛代理，雲林僅名錄來源、近期直接政府內文待補。非名錄首長不能直接推定任期屆滿或挑戰者。
- Definition for each variable:
    - `candidate_key`沿用名冊公職×縣市×選區×姓名／既有縣市長ID，不以姓名單欄連接；`office_type`與`county_city`保留名冊原文。
    - `birth_date_supported_history`／`sex_supported_history`為原2022有身分支持的歷史序列；`birth_date_additional_official`、`birth_date_additional_source_year`為額外官方人物頁或跨年中選會生日；`sex_additional_source_value`／`sex_additional_source_year`為明載申報性別，與性別推測分開。`birth_date_self_declared`為先前自述，不混入官方。
    - `additional_historical_education_cec`為新連結歷史表原學歷欄，不認證2026最高學歷；`education_raw`／`experience_raw`保留逐頁原文；`round6_profile_urls`為本輪已讀來源，原profile欄不覆寫。
    - `first_time_any_office_supported`／`first_time_this_office_supported`：0表示有可支持過往參選／任職的來源；未知維持空白，未由查無紀錄填1。
    - `matches_listed_elected_head`僅為同縣市候選人姓名與名錄民選首長的比對0/1；`government_role_name_as_captured`保留另一官方頁明載名稱；`acting_head_observed`僅宜蘭=1，其餘空白不等於沒有代理；`listed_elected_head_registered_in_roster`只表示登記名冊有無同名民選首長，不代表最終資格。
    - `account_url`為候選人專屬區塊直接列出的網址；`source_locator`保留DOM／明載文字定位；`target_content_status`目標帳號內容存取狀態，不等同來源頁成功。`window_count`與追蹤起訖維持空白。
    - 待查表`upstream_title`／`upstream_organization`／`upstream_*date`為第三方主張，不是本研究核實職務；`http_status`與`page_mentions_candidate_name`只記來源可得性；`claim_verified=0`表示尚未核實主張。
    - 各輸出其他欄位沿用前輪已記錄定義；來源、年份與證據狀態保留在逐欄證據表，未將概略履歷轉成行政年資或政治家族判定。
- Data path: 下表10個實際輸出，各自讀取固定hash。
- Source data: 前輪5個snapshot、81人round4縣市長表、3份來源manifest、履歷retrieval_plan，及官方歷史表／解壓manifest；精確inputs見產生程式PINS及HISTORY_PINS。
- Processing code: [第六輪處理Notebook](../code/career_round6_20261019.ipynb)
- Role: review_inventory／source_observation／discovery_worklist；尚不是完整可推論分析資料。
- Verification status: 以磁碟讀回schema、key、筆數、社群及背景轉換規則進行實際驗證，結果保留於本文件執行輸出。
- SHA-256: 各檔固定如下。
- Downstream analysis input: 必須使用下表同一份檔案與固定hash；未在本輪重跑統計finding。

| Data path | Rows | SHA-256 |
| --- | --- | --- |
| `data/processed/snapshots/pre_identity_round7_20261019/candidate_master_current.csv` | 1583 | `863118696723c57e4188dea85a3a344658641e3f12692a8c87862e7a1ee1bd12` |
| `data/processed/snapshots/pre_identity_round7_20261019/candidate_fields_current.csv` | 31660 | `7344f7328301b184d7f2c89473c0c0532e1d07e9e3f64a739df6f3c528c60350` |
| `data/processed/snapshots/pre_identity_round7_20261019/council_background_20261019.csv` | 1502 | `06bbbaf105fa5c1a1286776ddad67f6bf642f3b2961ffa0fd66775126f2680dc` |
| `data/processed/candidate_social_account_evidence_current.csv` | 233 | `7b53408d0db28ec76e50571f94307aa71591d299a6cd8dab8c03e6f3dce07666` |
| `data/processed/meta_candidate_account_worklist_current.csv` | 4749 | `af310f7c2e79a57e8050176e98c344b23eccaf93b3e76dc55afee60e3ca6f032` |
| `data/processed/candidate_profiles_round6_20261019.csv` | 18 | `c794b2e934bff27d295a6bda4c5ed6010fff511f357c520f0bebb1b08449cfe8` |
| `data/processed/candidate_background_evidence_round6_20261019.csv` | 49 | `71269c828d18be5d1f8a2ec5385c43adfdf95a33ed1de9659d8776503355b70f` |
| `data/processed/mayor_head_comparison_round6_20261019.csv` | 81 | `66ec6d7c79ab97becc516ace9eba2e227be1ef138fd8c0d8fc602f3baeb036e4` |
| `data/processed/candidates_2026_enriched_round6_20261019.csv` | 81 | `e0864634ab220e1dd9298a3a6b487c90246b834a678542fad6c7798698c93fb8` |
| `data/processed/council_career_source_worklist_round6_20261019.csv` | 1162 | `7f467321214ecb4c640dd66e951ac16ea9663b4072f075213cebb530263a542e` |

### 生日續補來源界線

陳重嘉1981-01-19：官方議會人物頁明載；温世政1973-05-04：2021-07-17專業學會名冊第1頁第8列已視讀，搭配當屆媒體生日／診所身分支持，來源非政府。兩筆原HTTP403保存；web工具摘錄另列方法，不假稱全文下載成功。完整生日59/81、仍缺22人；不是59筆全部政府來源認證。陳重嘉非首次任何民選公職亦由官方歷屆議員履歷補0，首次縣市長仍未知。

公開來源副本修訂（2026-10-19）：7份第三方HTML中的Google地圖API key已遮蔽；原始HTTP回應bytes已核對後私存於Git儲存庫外。來源manifest同時保存original_response_sha256與清理後sha256，PINS及輸出來源指紋綁定清理後公開版本。人物學經歷、生日、政見等研究文字未刪改。詳見[清理紀錄](../../report/source_capture_security_20261019.md)。

第七輪接續註記：本輪三份current背景／逐欄輸出已封存至pre_identity_round7快照；本文件仍讀寫其第六輪版本，最新整合由council_identity_round7產生。

In [1]:
from pathlib import Path
import pandas as pd,hashlib
ROOT=next(p for p in [Path.cwd(),*Path.cwd().parents] if (p/"AGENTS.md").is_file() and (p/"templates").is_dir())
PINS={'data/processed/snapshots/pre_identity_round7_20261019/candidate_master_current.csv': '863118696723c57e4188dea85a3a344658641e3f12692a8c87862e7a1ee1bd12', 'data/processed/snapshots/pre_identity_round7_20261019/candidate_fields_current.csv': '7344f7328301b184d7f2c89473c0c0532e1d07e9e3f64a739df6f3c528c60350', 'data/processed/snapshots/pre_identity_round7_20261019/council_background_20261019.csv': '06bbbaf105fa5c1a1286776ddad67f6bf642f3b2961ffa0fd66775126f2680dc', 'data/processed/candidate_social_account_evidence_current.csv': '7b53408d0db28ec76e50571f94307aa71591d299a6cd8dab8c03e6f3dce07666', 'data/processed/meta_candidate_account_worklist_current.csv': 'af310f7c2e79a57e8050176e98c344b23eccaf93b3e76dc55afee60e3ca6f032', 'data/processed/candidate_profiles_round6_20261019.csv': 'c794b2e934bff27d295a6bda4c5ed6010fff511f357c520f0bebb1b08449cfe8', 'data/processed/candidate_background_evidence_round6_20261019.csv': '71269c828d18be5d1f8a2ec5385c43adfdf95a33ed1de9659d8776503355b70f', 'data/processed/mayor_head_comparison_round6_20261019.csv': '66ec6d7c79ab97becc516ace9eba2e227be1ef138fd8c0d8fc602f3baeb036e4', 'data/processed/candidates_2026_enriched_round6_20261019.csv': 'e0864634ab220e1dd9298a3a6b487c90246b834a678542fad6c7798698c93fb8', 'data/processed/council_career_source_worklist_round6_20261019.csv': '7f467321214ecb4c640dd66e951ac16ea9663b4072f075213cebb530263a542e'}
EXPECTED={'data/processed/snapshots/pre_identity_round7_20261019/candidate_master_current.csv': {'rows': 1583, 'columns': 34, 'key': ['candidate_key'], 'sha256': '863118696723c57e4188dea85a3a344658641e3f12692a8c87862e7a1ee1bd12'}, 'data/processed/snapshots/pre_identity_round7_20261019/candidate_fields_current.csv': {'rows': 31660, 'columns': 11, 'key': ['candidate_key', 'field'], 'sha256': '7344f7328301b184d7f2c89473c0c0532e1d07e9e3f64a739df6f3c528c60350'}, 'data/processed/snapshots/pre_identity_round7_20261019/council_background_20261019.csv': {'rows': 1502, 'columns': 48, 'key': ['candidate_key'], 'sha256': '06bbbaf105fa5c1a1286776ddad67f6bf642f3b2961ffa0fd66775126f2680dc'}, 'data/processed/candidate_social_account_evidence_current.csv': {'rows': 233, 'columns': 14, 'key': [], 'sha256': '7b53408d0db28ec76e50571f94307aa71591d299a6cd8dab8c03e6f3dce07666'}, 'data/processed/meta_candidate_account_worklist_current.csv': {'rows': 4749, 'columns': 13, 'key': ['candidate_key', 'platform'], 'sha256': 'af310f7c2e79a57e8050176e98c344b23eccaf93b3e76dc55afee60e3ca6f032'}, 'data/processed/candidate_profiles_round6_20261019.csv': {'rows': 18, 'columns': 11, 'key': ['candidate_key'], 'sha256': 'c794b2e934bff27d295a6bda4c5ed6010fff511f357c520f0bebb1b08449cfe8'}, 'data/processed/candidate_background_evidence_round6_20261019.csv': {'rows': 49, 'columns': 9, 'key': [], 'sha256': '71269c828d18be5d1f8a2ec5385c43adfdf95a33ed1de9659d8776503355b70f'}, 'data/processed/mayor_head_comparison_round6_20261019.csv': {'rows': 81, 'columns': 17, 'key': ['candidate_key'], 'sha256': '66ec6d7c79ab97becc516ace9eba2e227be1ef138fd8c0d8fc602f3baeb036e4'}, 'data/processed/candidates_2026_enriched_round6_20261019.csv': {'rows': 81, 'columns': 61, 'key': ['candidate_key'], 'sha256': 'e0864634ab220e1dd9298a3a6b487c90246b834a678542fad6c7798698c93fb8'}, 'data/processed/council_career_source_worklist_round6_20261019.csv': {'rows': 1162, 'columns': 19, 'key': [], 'sha256': '7f467321214ecb4c640dd66e951ac16ea9663b4072f075213cebb530263a542e'}}
frames={}
for p,h in PINS.items():
 q=(ROOT/p).resolve();assert q.is_relative_to((ROOT/"data/processed").resolve()) and q.is_file() and hashlib.sha256(q.read_bytes()).hexdigest()==h,p
 d=pd.read_csv(q,dtype=str,keep_default_na=False);assert len(d)==EXPECTED[p]["rows"] and len(d.columns)==EXPECTED[p]["columns"]
 if EXPECTED[p]["key"]:assert not d.duplicated(EXPECTED[p]["key"]).any(),p
 frames[p]=d
print("Read and hash/schema/key checked",len(frames),"saved outputs")

Read and hash/schema/key checked 10 saved outputs

## Change for Your Own Data

本文件只讀固定輸出，不執行下載、處理或覆寫。原始來源bytes說明見[來源文件](../raw/career_round6_20261019_documentation.ipynb)。

## Summary

### Sample

In [2]:
for p,d in frames.items():
 print(p);display(d.head(10))

data/processed/snapshots/pre_identity_round7_20261019/candidate_master_current.csv

,candidate_key,candidate_name,office_type,county_city,electoral_district,party_registration_raw,registration_source,registration_source_file,registration_source_page,qualification_inherited,...,Threads_status,posts_Facebook_status,posts_Instagram_status,posts_Threads_status,followers_status,policy_text_status,visual_status,political_family_status,administrative_experience_status,qualification_status
0,2026-C1-001,郭璽,直轄市長,臺北市,,台灣麻將最大黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
1,2026-C1-002,沈伯洋,直轄市長,臺北市,,民主進步黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,人物頁／競選頁已列帳號連結；目標內容待核對,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,部分原文已保存，尚未政策編碼,未查找,未查找,未查找,官方內文待重新核對
2,2026-C1-003,蕭文乾,直轄市長,臺北市,,臺灣SoR無法黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
3,2026-C1-004,唐新民,直轄市長,臺北市,,三勢團結促進聯盟,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
4,2026-C1-005,蔣萬安,直轄市長,臺北市,,中國國民黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
5,2026-C1-006,林志成,直轄市長,臺北市,,無,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
6,2026-C1-007,蘇巧慧,直轄市長,新北市,,民主進步黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,人物頁／競選頁已列帳號連結；目標內容待核對,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,部分原文已保存，尚未政策編碼,未查找,未查找,未查找,官方內文待重新核對
7,2026-C1-008,李四川,直轄市長,新北市,,中國國民黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,人物頁／競選頁已列帳號連結；目標內容待核對,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
8,2026-C1-009,蘇輝湟,直轄市長,新北市,,無,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
9,2026-C1-010,張善政,直轄市長,桃園市,,中國國民黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對

data/processed/snapshots/pre_identity_round7_20261019/candidate_fields_current.csv

,candidate_key,candidate_name,office_type,county_city,field,status,existing_value,evidence,note,next_source,updated_date
0,2026-C1-001,郭璽,直轄市長,臺北市,sex,已有資料，待來源複核,男,https://db.cec.gov.tw/,dob_corroborated_by_media,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
1,2026-C1-001,郭璽,直轄市長,臺北市,birth_date,已有資料，待來源複核,1958-08-31,https://db.cec.gov.tw/,CEC_name_and_birth_date_corroborated_by_CNA,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
2,2026-C1-001,郭璽,直轄市長,臺北市,education,已有資料，待來源複核,大學,,歷史公報或媒體補充，非2026學歷認證,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
3,2026-C1-001,郭璽,直轄市長,臺北市,incumbency,既有搜尋後仍缺，待補查,,,,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
4,2026-C1-001,郭璽,直轄市長,臺北市,first_time_this_office,既有搜尋後仍缺，待補查,,,0=有過參選證據；空白不表示首次。此處沿用既有表。,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
5,2026-C1-001,郭璽,直轄市長,臺北市,first_time_any_office,已有資料，待來源複核,0,https://db.cec.gov.tw/,0=有過參選證據；空白不表示首次。此處沿用既有表。,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
6,2026-C1-001,郭璽,直轄市長,臺北市,profile,既有搜尋後仍缺，待補查,,,,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
7,2026-C1-001,郭璽,直轄市長,臺北市,website,既有搜尋後仍缺，待補查,,,,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
8,2026-C1-001,郭璽,直轄市長,臺北市,Facebook,尚未驗證，不代表無帳號,,,,官方人物頁／競選網站交叉連結,2026-10-19
9,2026-C1-001,郭璽,直轄市長,臺北市,Instagram,尚未驗證，不代表無帳號,,,,官方人物頁／競選網站交叉連結,2026-10-19

data/processed/snapshots/pre_identity_round7_20261019/council_background_20261019.csv

,candidate_key,candidate_name,county_city,office_type,electoral_district,party_registration_raw,birth_date_supported_history,birth_year_supported_history,sex_supported_history,birth_sex_evidence_status,...,bulletin_source_url,bulletin_source_file,bulletin_source_page,bulletin_identity_status,birth_date_additional_official,birth_date_additional_source_url,birth_date_additional_evidence_status,round6_profile_urls,birth_date_additional_source_year,additional_historical_education_cec
0,2026|直轄市議員|臺北市第1選舉區|謝閔弘,謝閔弘,臺北市,直轄市議員,臺北市第1選舉區,時代力量,,,,尚無可連結的歷史紀錄,...,,,,,,,,,,
1,2026|直轄市議員|臺北市第1選舉區|李文,李文,臺北市,直轄市議員,臺北市第1選舉區,無,,,,尚無可連結的歷史紀錄,...,,,,,,,,,,
2,2026|直轄市議員|臺北市第1選舉區|陳彥廷,陳彥廷,臺北市,直轄市議員,臺北市第1選舉區,無,,,,尚無可連結的歷史紀錄,...,,,,,,,,,,
3,2026|直轄市議員|臺北市第1選舉區|鍾佩玲,鍾佩玲,臺北市,直轄市議員,臺北市第1選舉區,民主進步黨,1979-03-27,1979,女,2022官方申報，先前身分連結審核有支持；非2026戶籍認定,...,,,,,,,,,,
4,2026|直轄市議員|臺北市第1選舉區|紀建漢,紀建漢,臺北市,直轄市議員,臺北市第1選舉區,無,,,,尚無可連結的歷史紀錄,...,,,,,,,,,,
5,2026|直轄市議員|臺北市第1選舉區|陳賢蔚,陳賢蔚,臺北市,直轄市議員,臺北市第1選舉區,民主進步黨,1977-07-12,1977,男,2022官方申報，先前身分連結審核有支持；非2026戶籍認定,...,,,,,,,,,,
6,2026|直轄市議員|臺北市第1選舉區|林世宗,林世宗,臺北市,直轄市議員,臺北市第1選舉區,民主進步黨,1959-06-13,1959,男,2022官方申報，先前身分連結審核有支持；非2026戶籍認定,...,,,,,,,,,,
7,2026|直轄市議員|臺北市第1選舉區|黃瀞瑩,黃瀞瑩,臺北市,直轄市議員,臺北市第1選舉區,台灣民眾黨,1992-06-10,1992,女,2022官方申報，先前身分連結審核有支持；非2026戶籍認定,...,,,,,,,,,,
8,2026|直轄市議員|臺北市第1選舉區|林揚庭,林揚庭,臺北市,直轄市議員,臺北市第1選舉區,中國國民黨,,,,尚無可連結的歷史紀錄,...,,,,,,,,,,
9,2026|直轄市議員|臺北市第1選舉區|陳慈慧,陳慈慧,臺北市,直轄市議員,臺北市第1選舉區,民主進步黨,1983-11-22,1983,女,2022官方申報，先前身分連結審核有支持；非2026戶籍認定,...,,,,,,,,,,

data/processed/candidate_social_account_evidence_current.csv

,candidate_key,candidate_name,county_city,office_type,platform,account_url,source_url,source_file,source_locator,evidence_status,target_content_status,checked_date,source_year,source_identity_status
0,2026|縣市議員|南投縣第1選舉區|吳淳祐,吳淳祐,南投縣,縣（市）議員,Facebook,https://www.facebook.com/profile.php?id=615900...,https://www.pridewatch.tw/candidate/chunyounantou,data/raw/background_expansion_20261019/0a4e87f...,ul.candidate-social-links,candidate_specific_civil_society_profile_link,not_verified_not_posts_captured,2026-10-19,,
1,2026|縣市議員|南投縣第1選舉區|吳淳祐,吳淳祐,南投縣,縣（市）議員,Instagram,https://www.instagram.com/chunyou.nantou,https://www.pridewatch.tw/candidate/chunyounantou,data/raw/background_expansion_20261019/0a4e87f...,ul.candidate-social-links,candidate_specific_civil_society_profile_link,not_verified_not_posts_captured,2026-10-19,,
2,2026-C2-033,温世政,南投縣,縣（市）長,Facebook,https://www.facebook.com/wEnShihheng,https://teamtaiwan.dpp.org.tw/asset/types/elec...,data/raw/round3_20261019/cab91a155008312e422c....,mayor_data name=温世政 field=fb,party_candidate_object_link,not_verified_not_posts_captured,2026-10-19,,
3,2026-C2-033,温世政,南投縣,縣（市）長,Instagram,https://www.instagram.com/wen_shih_cheng,https://teamtaiwan.dpp.org.tw/asset/types/elec...,data/raw/round3_20261019/cab91a155008312e422c....,mayor_data name=温世政 field=ig,party_candidate_object_link,not_verified_not_posts_captured,2026-10-19,,
4,2026-C2-033,温世政,南投縣,縣（市）長,Threads,https://www.threads.com/@wen_shih_cheng,https://teamtaiwan.dpp.org.tw/asset/types/elec...,data/raw/round3_20261019/cab91a155008312e422c....,mayor_data name=温世政 field=threads,party_candidate_object_link,not_verified_not_posts_captured,2026-10-19,,
5,2026|縣市議員|嘉義市第2選舉區|林詩涵,林詩涵,嘉義市,縣（市）議員,Facebook,https://www.facebook.com/shihhanlin.chiayi,https://www.taiwangogo.tw/lin-shih-han/,data/raw/round3_20261019/f94d16aea58833d3e1d3....,.cv-social; candidate card 林詩涵; 嘉義市,campaign_directory_candidate_link,not_verified_not_posts_captured,2026-10-19,,
6,2026|縣市議員|嘉義市第2選舉區|林詩涵,林詩涵,嘉義市,縣（市）議員,Instagram,https://www.instagram.com/flip_chiayi,https://www.taiwangogo.tw/lin-shih-han/,data/raw/round3_20261019/f94d16aea58833d3e1d3....,.cv-social; candidate card 林詩涵; 嘉義市,campaign_directory_candidate_link,not_verified_not_posts_captured,2026-10-19,,
7,2026-C2-080,王美惠,嘉義市,縣（市）長,Facebook,https://www.facebook.com/ahueimoto,https://teamtaiwan.dpp.org.tw/asset/types/elec...,data/raw/round3_20261019/cab91a155008312e422c....,mayor_data name=王美惠 field=fb,party_candidate_object_link,not_verified_not_posts_captured,2026-10-19,,
8,2026-C2-080,王美惠,嘉義市,縣（市）長,Instagram,https://www.instagram.com/ahueimoto,https://teamtaiwan.dpp.org.tw/asset/types/elec...,data/raw/round3_20261019/cab91a155008312e422c....,mayor_data name=王美惠 field=ig,party_candidate_object_link,not_verified_not_posts_captured,2026-10-19,,
9,2026-C2-080,王美惠,嘉義市,縣（市）長,Threads,https://www.threads.com/@ahueimoto,https://teamtaiwan.dpp.org.tw/asset/types/elec...,data/raw/round3_20261019/cab91a155008312e422c....,mayor_data name=王美惠 field=threads,party_candidate_object_link,not_verified_not_posts_captured,2026-10-19,,

data/processed/meta_candidate_account_worklist_current.csv

,candidate_key,candidate_name,county_city,office_type,platform,official_urls,discovered_on,account_status,posts_status,window_count,followers_start,followers_end,updated_date
0,2026-C1-001,郭璽,臺北市,直轄市長,Facebook,,,not_yet_found_not_absent,not_collected_not_zero,,,,2026-10-19
1,2026-C1-001,郭璽,臺北市,直轄市長,Instagram,,,not_yet_found_not_absent,not_collected_not_zero,,,,2026-10-19
2,2026-C1-001,郭璽,臺北市,直轄市長,Threads,,,not_yet_found_not_absent,not_collected_not_zero,,,,2026-10-19
3,2026-C1-002,沈伯洋,臺北市,直轄市長,Facebook,https://www.facebook.com/1087764201093899 | ht...,https://puma.taipei/ | https://www.pumashen.or...,candidate_specific_source_link_target_content_...,not_collected_not_zero,,,,2026-10-19
4,2026-C1-002,沈伯洋,臺北市,直轄市長,Instagram,https://www.instagram.com/pumashen,https://teamtaiwan.dpp.org.tw/asset/types/elec...,candidate_specific_source_link_target_content_...,not_collected_not_zero,,,,2026-10-19
5,2026-C1-002,沈伯洋,臺北市,直轄市長,Threads,https://www.threads.com/@pumashen,https://teamtaiwan.dpp.org.tw/asset/types/elec...,candidate_specific_source_link_target_content_...,not_collected_not_zero,,,,2026-10-19
6,2026-C1-003,蕭文乾,臺北市,直轄市長,Facebook,,,not_yet_found_not_absent,not_collected_not_zero,,,,2026-10-19
7,2026-C1-003,蕭文乾,臺北市,直轄市長,Instagram,,,not_yet_found_not_absent,not_collected_not_zero,,,,2026-10-19
8,2026-C1-003,蕭文乾,臺北市,直轄市長,Threads,,,not_yet_found_not_absent,not_collected_not_zero,,,,2026-10-19
9,2026-C1-004,唐新民,臺北市,直轄市長,Facebook,,,not_yet_found_not_absent,not_collected_not_zero,,,,2026-10-19

data/processed/candidate_profiles_round6_20261019.csv

,candidate_key,candidate_name,county_city,electoral_district,source_url,source_file,source_tier,education_raw,experience_raw,identity_review,checked_date
0,2026|縣市議員|基隆市第7選舉區|楊秀玉,楊秀玉,基隆市,基隆市第7選舉區,https://youth.pfpnext.com/2026/candidate-detai...,data/raw/social_followup_round6_20261019/c9fb4...,party_candidate_page_self_reported,,現任 第 19 屆基隆市議員(副議長) 曾任 第 18 屆基隆市議員 現任 基隆市警察之友會...,姓名、當屆縣市及選區文字與名冊一致；曾任／現任按來源原文保留，不單憑此認定任職法律狀態,2026-10-19
1,2026|直轄市議員|新北市第4選舉區|劉成謙,劉成謙,新北市,新北市第4選舉區,https://youth.pfpnext.com/2026/candidate-detai...,data/raw/career_expansion_20261019/fff69c0c06e...,party_candidate_page_self_reported,,現任 親民黨青年團副團長 現任 社團法人台灣機車路權促進會秘書長、創會理事 現任 社團法人行...,姓名、當屆縣市及選區文字與名冊一致；曾任／現任按來源原文保留，不單憑此認定任職法律狀態,2026-10-19
2,2026|直轄市議員|桃園市第2選舉區|陳泓維,陳泓維,桃園市,桃園市第2選舉區,https://youth.pfpnext.com/2026/candidate-detai...,data/raw/social_followup_round6_20261019/b39ba...,party_candidate_page_self_reported,,經歷 立法委員賴香伶桃園辦公室 主任 經歷 民眾黨中央黨部組織發展部 副主任 經歷 立法委員...,姓名、當屆縣市及選區文字與名冊一致；曾任／現任按來源原文保留，不單憑此認定任職法律狀態,2026-10-19
3,2026|直轄市議員|桃園市第6選舉區|徐慈檉,徐慈檉,桃園市,桃園市第6選舉區,https://youth.pfpnext.com/2026/candidate-detai...,data/raw/social_followup_round6_20261019/ce69d...,party_candidate_page_self_reported,,曾任 開南大學資訊傳播學系講師 曾任 立法委員孫大千、陳學聖、趙正宇、蔡壁如秘書 曾任 市長...,姓名、當屆縣市及選區文字與名冊一致；曾任／現任按來源原文保留，不單憑此認定任職法律狀態,2026-10-19
4,2026|縣市議員|宜蘭縣第12選舉區|陳傑麟,陳傑麟,宜蘭縣,宜蘭縣第12選舉區,https://youth.pfpnext.com/2026/candidate-detai...,data/raw/social_followup_round6_20261019/02779...,party_candidate_page_self_reported,,曾任 宜蘭縣議會第18屆、第19屆縣議員 曾任 宜蘭縣政府民政處副處長、縣府秘書 曾任 宜蘭...,姓名、當屆縣市及選區文字與名冊一致；曾任／現任按來源原文保留，不單憑此認定任職法律狀態,2026-10-19
5,2026|直轄市議員|新北市第3選舉區|蕭夙玲,蕭夙玲,新北市,新北市第3選舉區,https://youth.pfpnext.com/2026/candidate-detai...,data/raw/social_followup_round6_20261019/048db...,party_candidate_page_self_reported,,新北市議員宋明宗新莊區服務處主任 新北市議長蔣根煌福營區服務處主任 中華民國保齡球國家代表隊...,姓名、當屆縣市及選區文字與名冊一致；曾任／現任按來源原文保留，不單憑此認定任職法律狀態,2026-10-19
6,2026|直轄市議員|臺中市第4選舉區|黃朝淵,黃朝淵,臺中市,臺中市第4選舉區,https://youth.pfpnext.com/2026/candidate-detai...,data/raw/social_followup_round6_20261019/a201e...,party_candidate_page_self_reported,,可翔科技總經理 東森集團副總經理 亞洲醫美集團法務長兼副總經理 警政時報副社長 社團法人台中...,姓名、當屆縣市及選區文字與名冊一致；曾任／現任按來源原文保留，不單憑此認定任職法律狀態,2026-10-19
7,2026|縣市議員|基隆市第5選舉區|黃舒琳,黃舒琳,基隆市,基隆市第5選舉區,https://youth.pfpnext.com/2026/candidate-detai...,data/raw/social_followup_round6_20261019/f6a94...,party_candidate_page_self_reported,,現任 親民黨青年團 副團長 曾任 自然保育與環境資訊基金會 專案執行 曾任 配客嘉股份有限公...,姓名、當屆縣市及選區文字與名冊一致；曾任／現任按來源原文保留，不單憑此認定任職法律狀態,2026-10-19
8,2026|縣市議員|基隆市第2選舉區|鄭素禎,鄭素禎,基隆市,基隆市第2選舉區,https://youth.pfpnext.com/2026/candidate-detai...,data/raw/social_followup_round6_20261019/f5032...,party_candidate_page_self_reported,,民國76年 基層公務員特考及格 曾任 基隆市環保局辦事員、科員 曾任 正濱國小、深澳國小、大...,姓名、當屆縣市及選區文字與名冊一致；曾任／現任按來源原文保留，不單憑此認定任職法律狀態,2026-10-19
9,2026|直轄市議員|新北市第13選舉區|林啟明,林啟明,新北市,新北市第13選舉區,https://youth.pfpnext.com/2026/candidate-detai...,data/raw/social_followup_round6_20261019/dd2a1...,party_candidate_page_self_reported,海軍陸戰隊專修班45期畢 | 醒吾科技大學 | 省立仁愛高農,2025 新北市烏來區模範父親 2018 新北市烏來區區民代表候選人 2014 新北市烏來區...,姓名、當屆縣市及選區文字與名冊一致；曾任／現任按來源原文保留，不單憑此認定任職法律狀態,2026-10-19

data/processed/candidate_background_evidence_round6_20261019.csv

,candidate_key,candidate_name,field,value,source_url,source_file,source_year,evidence_status,checked_date
0,2026|縣市議員|基隆市第7選舉區|楊秀玉,楊秀玉,experience,現任 第 19 屆基隆市議員(副議長) 曾任 第 18 屆基隆市議員 現任 基隆市警察之友會...,https://youth.pfpnext.com/2026/candidate-detai...,data/raw/social_followup_round6_20261019/c9fb4...,2026,party_candidate_page_self_reported；姓名、當屆縣市及選區文...,2026-10-19
1,2026|直轄市議員|新北市第4選舉區|劉成謙,劉成謙,experience,現任 親民黨青年團副團長 現任 社團法人台灣機車路權促進會秘書長、創會理事 現任 社團法人行...,https://youth.pfpnext.com/2026/candidate-detai...,data/raw/career_expansion_20261019/fff69c0c06e...,2026,party_candidate_page_self_reported；姓名、當屆縣市及選區文...,2026-10-19
2,2026|直轄市議員|桃園市第2選舉區|陳泓維,陳泓維,experience,經歷 立法委員賴香伶桃園辦公室 主任 經歷 民眾黨中央黨部組織發展部 副主任 經歷 立法委員...,https://youth.pfpnext.com/2026/candidate-detai...,data/raw/social_followup_round6_20261019/b39ba...,2026,party_candidate_page_self_reported；姓名、當屆縣市及選區文...,2026-10-19
3,2026|直轄市議員|桃園市第6選舉區|徐慈檉,徐慈檉,experience,曾任 開南大學資訊傳播學系講師 曾任 立法委員孫大千、陳學聖、趙正宇、蔡壁如秘書 曾任 市長...,https://youth.pfpnext.com/2026/candidate-detai...,data/raw/social_followup_round6_20261019/ce69d...,2026,party_candidate_page_self_reported；姓名、當屆縣市及選區文...,2026-10-19
4,2026|縣市議員|宜蘭縣第12選舉區|陳傑麟,陳傑麟,experience,曾任 宜蘭縣議會第18屆、第19屆縣議員 曾任 宜蘭縣政府民政處副處長、縣府秘書 曾任 宜蘭...,https://youth.pfpnext.com/2026/candidate-detai...,data/raw/social_followup_round6_20261019/02779...,2026,party_candidate_page_self_reported；姓名、當屆縣市及選區文...,2026-10-19
5,2026|直轄市議員|新北市第3選舉區|蕭夙玲,蕭夙玲,experience,新北市議員宋明宗新莊區服務處主任 新北市議長蔣根煌福營區服務處主任 中華民國保齡球國家代表隊...,https://youth.pfpnext.com/2026/candidate-detai...,data/raw/social_followup_round6_20261019/048db...,2026,party_candidate_page_self_reported；姓名、當屆縣市及選區文...,2026-10-19
6,2026|直轄市議員|臺中市第4選舉區|黃朝淵,黃朝淵,experience,可翔科技總經理 東森集團副總經理 亞洲醫美集團法務長兼副總經理 警政時報副社長 社團法人台中...,https://youth.pfpnext.com/2026/candidate-detai...,data/raw/social_followup_round6_20261019/a201e...,2026,party_candidate_page_self_reported；姓名、當屆縣市及選區文...,2026-10-19
7,2026|縣市議員|基隆市第5選舉區|黃舒琳,黃舒琳,experience,現任 親民黨青年團 副團長 曾任 自然保育與環境資訊基金會 專案執行 曾任 配客嘉股份有限公...,https://youth.pfpnext.com/2026/candidate-detai...,data/raw/social_followup_round6_20261019/f6a94...,2026,party_candidate_page_self_reported；姓名、當屆縣市及選區文...,2026-10-19
8,2026|縣市議員|基隆市第2選舉區|鄭素禎,鄭素禎,experience,民國76年 基層公務員特考及格 曾任 基隆市環保局辦事員、科員 曾任 正濱國小、深澳國小、大...,https://youth.pfpnext.com/2026/candidate-detai...,data/raw/social_followup_round6_20261019/f5032...,2026,party_candidate_page_self_reported；姓名、當屆縣市及選區文...,2026-10-19
9,2026|直轄市議員|新北市第13選舉區|林啟明,林啟明,education,海軍陸戰隊專修班45期畢 | 醒吾科技大學 | 省立仁愛高農,https://youth.pfpnext.com/2026/candidate-detai...,data/raw/social_followup_round6_20261019/dd2a1...,2026,party_candidate_page_self_reported；姓名、當屆縣市及選區文...,2026-10-19

data/processed/mayor_head_comparison_round6_20261019.csv

,candidate_key,candidate_name,county_city,listed_elected_head_name,moi_source_url,moi_source_file,government_role_name_as_captured,government_role_source_url,government_role_source_file,government_role_context,government_role_locator,source_scope,acting_head_observed,matches_listed_elected_head,listed_elected_head_registered_in_roster,comparison_status,checked_date
0,2026-C1-001,郭璽,臺北市,蔣萬安,https://www.moi.gov.tw/LocalOfficial_Content.a...,data/raw/mayor_incumbency_20261019/e2263dbfb2d...,蔣萬安,https://www.gov.taipei/News_Content_Leader.asp...,data/raw/mayor_incumbency_20261019/ef321533527...,﻿ 臺北市政府全球資訊網-蔣萬安市長-蔣萬安 跳到主要內容區塊 搜尋 搜尋 公民參與 台北市...,HTML text and explicitly named img alt; not in...,official_role_context_as_captured_not_full_leg...,,0,1,not_the_listed_elected_head; no automatic term...,2026-10-19
1,2026-C1-002,沈伯洋,臺北市,蔣萬安,https://www.moi.gov.tw/LocalOfficial_Content.a...,data/raw/mayor_incumbency_20261019/e2263dbfb2d...,蔣萬安,https://www.gov.taipei/News_Content_Leader.asp...,data/raw/mayor_incumbency_20261019/ef321533527...,﻿ 臺北市政府全球資訊網-蔣萬安市長-蔣萬安 跳到主要內容區塊 搜尋 搜尋 公民參與 台北市...,HTML text and explicitly named img alt; not in...,official_role_context_as_captured_not_full_leg...,,0,1,not_the_listed_elected_head; no automatic term...,2026-10-19
2,2026-C1-003,蕭文乾,臺北市,蔣萬安,https://www.moi.gov.tw/LocalOfficial_Content.a...,data/raw/mayor_incumbency_20261019/e2263dbfb2d...,蔣萬安,https://www.gov.taipei/News_Content_Leader.asp...,data/raw/mayor_incumbency_20261019/ef321533527...,﻿ 臺北市政府全球資訊網-蔣萬安市長-蔣萬安 跳到主要內容區塊 搜尋 搜尋 公民參與 台北市...,HTML text and explicitly named img alt; not in...,official_role_context_as_captured_not_full_leg...,,0,1,not_the_listed_elected_head; no automatic term...,2026-10-19
3,2026-C1-004,唐新民,臺北市,蔣萬安,https://www.moi.gov.tw/LocalOfficial_Content.a...,data/raw/mayor_incumbency_20261019/e2263dbfb2d...,蔣萬安,https://www.gov.taipei/News_Content_Leader.asp...,data/raw/mayor_incumbency_20261019/ef321533527...,﻿ 臺北市政府全球資訊網-蔣萬安市長-蔣萬安 跳到主要內容區塊 搜尋 搜尋 公民參與 台北市...,HTML text and explicitly named img alt; not in...,official_role_context_as_captured_not_full_leg...,,0,1,not_the_listed_elected_head; no automatic term...,2026-10-19
4,2026-C1-005,蔣萬安,臺北市,蔣萬安,https://www.moi.gov.tw/LocalOfficial_Content.a...,data/raw/mayor_incumbency_20261019/e2263dbfb2d...,蔣萬安,https://www.gov.taipei/News_Content_Leader.asp...,data/raw/mayor_incumbency_20261019/ef321533527...,﻿ 臺北市政府全球資訊網-蔣萬安市長-蔣萬安 跳到主要內容區塊 搜尋 搜尋 公民參與 台北市...,HTML text and explicitly named img alt; not in...,official_role_context_as_captured_not_full_leg...,,1,1,matches_listed_elected_head_and_official_role_...,2026-10-19
5,2026-C1-006,林志成,臺北市,蔣萬安,https://www.moi.gov.tw/LocalOfficial_Content.a...,data/raw/mayor_incumbency_20261019/e2263dbfb2d...,蔣萬安,https://www.gov.taipei/News_Content_Leader.asp...,data/raw/mayor_incumbency_20261019/ef321533527...,﻿ 臺北市政府全球資訊網-蔣萬安市長-蔣萬安 跳到主要內容區塊 搜尋 搜尋 公民參與 台北市...,HTML text and explicitly named img alt; not in...,official_role_context_as_captured_not_full_leg...,,0,1,not_the_listed_elected_head; no automatic term...,2026-10-19
6,2026-C1-007,蘇巧慧,新北市,侯友宜,https://www.moi.gov.tw/LocalOfficial_Content.a...,data/raw/mayor_incumbency_20261019/be060bb813c...,侯友宜,https://www.ntpc.gov.tw/ch/home.jsp?id=5de1e44...,data/raw/mayor_incumbency_20261019/02a5c146d9f...,侯友宜-新北市政府 瀏覽輔助設定 × 顏色設定： 黃字黑背景 無彩色 預設色彩 如『您的瀏覽...,HTML text and explicitly named img alt; not in...,official_role_context_as_captured_not_full_leg...,,0,0,not_the_listed_elected_head; no automatic term...,2026-10-19
7,2026-C1-008,李四川,新北市,侯友宜,https://www.moi.gov.tw/LocalOfficial_Content.a...,data/raw/mayor_incumbency_20261019/be060bb813c...,侯友宜,https://www.ntpc.gov.tw/ch/home.jsp?id=5de1e44...,data/raw/mayor_incumbency_20261019/02a5c146d9f...,侯友宜-新北市政府 瀏覽輔助設定 × 顏色設定： 黃字黑背景 無彩色 預設色彩 如『您的瀏覽...,HTML text and explicitly named img alt; not in...,official_role_context_as_captured_not_full_leg...,,0,0,not_the_listed_elected_head; no automatic term...,2026-10-19
8,2026-C1-009,蘇輝湟,新北市,侯友宜,https://www.moi.gov.tw/LocalOfficial_Content.a...,data/raw/mayor_incumbency_20261019/be060bb813c...,侯友宜,https://www.ntpc.gov.tw/ch/home.jsp?id=5de1e44...,data/raw/mayor_incumbency_20261019/02a5c146d9f...,侯友宜-新北市政府 瀏覽輔助設定 × 顏色設定： 黃字黑背景 無彩色 預設色彩 如『您的瀏覽...,HTML text and explicitly named img alt; not in...,official_role_context_as_captured_not_full_leg...,,0,0,not_the_listed_elected_head; no automatic term...,2026-10-19
9,2026-C1-010,張善政,桃園市,張善政,https://www.moi.gov.tw/LocalOfficial_Content.a...,data/raw/mayor_incumbency_20261019/6f03f427278...,張善政,https://idipc-tiiai.tycg.gov.tw/about?id=0svtt...,data/raw/mayor_incumbency_20261019/ede27d373c1...,策進會 工商策進會 關於我們 服務項目 組織架構 市長兼主任委員 執行長 中小企業服務中心 ...,HTML text and explicitly named img alt; not in...,official_role_context_as_captured_not_full_leg...,,1,1,matches_listed_elected_head_and_official_role_...,2026-10-19

data/processed/candidates_2026_enriched_round6_20261019.csv

,candidate_key,county_city,registration_date_roc,candidate_name,party_recommendation_original,source_note,office_type,source_file,source_page,source_url,...,sex_source_tier,sex_evidence_status,sex_directory_supplement,sex_directory_source_url,listed_elected_head_name,matches_listed_elected_head,government_role_name_as_captured,government_role_source_url,acting_head_observed,comparison_status
0,2026-C1-001,臺北市,115/08/31,郭璽,台灣麻將最大黨,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,historical_CEC,dob_corroborated_by_media,,,蔣萬安,0,蔣萬安,https://www.gov.taipei/News_Content_Leader.asp...,,not_the_listed_elected_head; no automatic term...
1,2026-C1-002,臺北市,115/09/02,沈伯洋,民主進步黨,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,official_profile,source_observation,,,蔣萬安,0,蔣萬安,https://www.gov.taipei/News_Content_Leader.asp...,,not_the_listed_elected_head; no automatic term...
2,2026-C1-003,臺北市,115/09/02,蕭文乾,臺灣SoR無法黨,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,official_bulletin,visually_checked_pdf_cell,,,蔣萬安,0,蔣萬安,https://www.gov.taipei/News_Content_Leader.asp...,,not_the_listed_elected_head; no automatic term...
3,2026-C1-004,臺北市,115/09/03,唐新民,三勢團結促進聯盟,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,historical_CEC,dob_corroborated_by_media,,,蔣萬安,0,蔣萬安,https://www.gov.taipei/News_Content_Leader.asp...,,not_the_listed_elected_head; no automatic term...
4,2026-C1-005,臺北市,115/09/04,蔣萬安,中國國民黨,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,historical_CEC,dob_corroborated_by_media,,,蔣萬安,1,蔣萬安,https://www.gov.taipei/News_Content_Leader.asp...,,matches_listed_elected_head_and_official_role_...
5,2026-C1-006,臺北市,115/09/04,林志成,無,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,historical_CEC,dob_corroborated_by_media,,,蔣萬安,0,蔣萬安,https://www.gov.taipei/News_Content_Leader.asp...,,not_the_listed_elected_head; no automatic term...
6,2026-C1-007,新北市,115/09/02,蘇巧慧,民主進步黨,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,official_profile,source_observation,,,侯友宜,0,侯友宜,https://www.ntpc.gov.tw/ch/home.jsp?id=5de1e44...,,not_the_listed_elected_head; no automatic term...
7,2026-C1-008,新北市,115/09/04,李四川,中國國民黨,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,official_government_sex,explicit_sex_role_identity_matched,,,侯友宜,0,侯友宜,https://www.ntpc.gov.tw/ch/home.jsp?id=5de1e44...,,not_the_listed_elected_head; no automatic term...
8,2026-C1-009,新北市,115/09/04,蘇輝湟,無,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,historical_CEC,dob_corroborated_by_media,,,侯友宜,0,侯友宜,https://www.ntpc.gov.tw/ch/home.jsp?id=5de1e44...,,not_the_listed_elected_head; no automatic term...
9,2026-C1-010,桃園市,115/09/01,張善政,中國國民黨,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,historical_CEC,dob_corroborated_by_media,,,張善政,1,張善政,https://idipc-tiiai.tycg.gov.tw/about?id=0svtt...,,matches_listed_elected_head_and_official_role_...

data/processed/council_career_source_worklist_round6_20261019.csv

,candidate_key,candidate_name,county_city,electoral_district,upstream_title,upstream_organization,upstream_start_date,upstream_end_date,upstream_source_title,upstream_source_type,source_url,http_status,source_file,source_sha256,content_type,page_mentions_candidate_name,review_status,claim_verified,checked_date
0,2026|縣市議員|連江縣第1選舉區|吳軾子,吳軾子,連江縣,連江縣第1選舉區,曾任總幹事,馬祖旅台同鄉會,,,馬祖日報：吳軾子完成縣長選舉國民黨黨內登記（2005-05-02）,news,https://www.matsu-news.gov.tw/news/article/38687,200,data/raw/career_expansion_20261019/ae0700e23a1...,c8e485f0d57ee6bded5f73f12ce7c462c7723993d660d0...,text/html; charset=UTF-8,1,page_mentions_name_not_identity_or_claim_valid...,0,2026-10-19
1,2026|縣市議員|連江縣第1選舉區|吳軾子,吳軾子,連江縣,連江縣第1選舉區,曾任《中國現場》節目主持人,環球電視台,,,馬祖日報：吳軾子完成縣長選舉國民黨黨內登記（2005-05-02）,news,https://www.matsu-news.gov.tw/news/article/38687,200,data/raw/career_expansion_20261019/ae0700e23a1...,c8e485f0d57ee6bded5f73f12ce7c462c7723993d660d0...,text/html; charset=UTF-8,1,page_mentions_name_not_identity_or_claim_valid...,0,2026-10-19
2,2026|縣市議員|連江縣第1選舉區|吳軾子,吳軾子,連江縣,連江縣第1選舉區,曾任通識教育兼任講師,育達技術學院,,,馬祖日報：吳軾子完成縣長選舉國民黨黨內登記（2005-05-02）,news,https://www.matsu-news.gov.tw/news/article/38687,200,data/raw/career_expansion_20261019/ae0700e23a1...,c8e485f0d57ee6bded5f73f12ce7c462c7723993d660d0...,text/html; charset=UTF-8,1,page_mentions_name_not_identity_or_claim_valid...,0,2026-10-19
3,2026|縣市議員|連江縣第1選舉區|林惠萍,林惠萍,連江縣,連江縣第1選舉區,曾任第五、七屆議員,連江縣議會,,,111年連江縣南竿鄉選舉公報第2頁：林惠萍學經歷（候選人自填）,gov,https://eebulletin.cec.gov.tw/111/20連江縣/04鄉鎮市民...,200,data/raw/background_expansion_20261019/8892bdd...,a1b1c51b339fe286b15f44d0c512db8540c0860393dc17...,application/pdf,,pdf_bytes_saved_person_field_extraction_pending,0,2026-10-19
4,2026|縣市議員|連江縣第1選舉區|林惠萍,林惠萍,連江縣,連江縣第1選舉區,公共事務學系研究所畢業（2022年公報自填）,銘傳大學,,,111年連江縣南竿鄉選舉公報第2頁：林惠萍學經歷（候選人自填）,gov,https://eebulletin.cec.gov.tw/111/20連江縣/04鄉鎮市民...,200,data/raw/background_expansion_20261019/8892bdd...,a1b1c51b339fe286b15f44d0c512db8540c0860393dc17...,application/pdf,,pdf_bytes_saved_person_field_extraction_pending,0,2026-10-19
5,2026|縣市議員|連江縣第1選舉區|林惠萍,林惠萍,連江縣,連江縣第1選舉區,理事長（2022年公報列載經歷）,連江縣銘傳校友會,,,111年連江縣南竿鄉選舉公報第2頁：林惠萍學經歷（候選人自填）,gov,https://eebulletin.cec.gov.tw/111/20連江縣/04鄉鎮市民...,200,data/raw/background_expansion_20261019/8892bdd...,a1b1c51b339fe286b15f44d0c512db8540c0860393dc17...,application/pdf,,pdf_bytes_saved_person_field_extraction_pending,0,2026-10-19
6,2026|縣市議員|連江縣第1選舉區|林惠萍,林惠萍,連江縣,連江縣第1選舉區,理事長（2022年公報列載經歷）,連江縣青溪婦女協會,,,111年連江縣南竿鄉選舉公報第2頁：林惠萍學經歷（候選人自填）,gov,https://eebulletin.cec.gov.tw/111/20連江縣/04鄉鎮市民...,200,data/raw/background_expansion_20261019/8892bdd...,a1b1c51b339fe286b15f44d0c512db8540c0860393dc17...,application/pdf,,pdf_bytes_saved_person_field_extraction_pending,0,2026-10-19
7,2026|縣市議員|連江縣第2選舉區|謝秉軒,謝秉軒,連江縣,連江縣第2選舉區,畢業（2026年報導）,醒吾大學,,,馬祖通訊社：謝秉軒投入北竿議員選舉（2026-09-04）,news,https://matzunews.com/5765/,200,data/raw/background_expansion_20261019/0cd62ba...,8706be0d94b0e7aa125074c48dd9dae5b4bedd214aa11c...,text/html; charset=UTF-8,1,page_mentions_name_not_identity_or_claim_valid...,0,2026-10-19
8,2026|縣市議員|連江縣第3選舉區|王孝榛,王孝榛,連江縣,連江縣第3選舉區,曾任議員,連江縣議會,,,馬祖日報：連江縣議員登記情形（2026-09-05，連江縣議會轉載）,news,https://www.mtcc.gov.tw/ch/Detail/7168?mcid=11...,200,data/raw/career_expansion_20261019/c18ac5c1cf0...,5755576f806f25f9e8d0ce174c619b9f9e300ae6863fae...,text/html; charset=utf-8,1,page_mentions_name_not_identity_or_claim_valid...,0,2026-10-19
9,2026|縣市議員|連江縣第3選舉區|王孝榛,王孝榛,連江縣,連江縣第3選舉區,曾任代課老師（2018年公報自填）,東莒國小,,,107年連江縣議員選舉公報第3頁：王孝榛學經歷（候選人自填）,gov,https://eebulletin.cec.gov.tw/107/20連江縣/02縣議員/...,,,,,,not_downloaded_or_unreadable,0,2026-10-19

### Summary Stats

In [3]:
display(pd.DataFrame([{ "path":p,"rows":len(d),"columns":len(d.columns),"blank_cells":int(d.eq("").sum().sum())} for p,d in frames.items()]))
c=frames["data/processed/snapshots/pre_identity_round7_20261019/council_background_20261019.csv"];a=frames["data/processed/candidate_social_account_evidence_current.csv"];m=frames["data/processed/candidates_2026_enriched_round6_20261019.csv"]
print("Profile gaps",int((c.moi_profile_url.eq("")&c.campaign_profile_url.eq("")&c.additional_profile_url.eq("")).sum()))
print("Official birthday union",int((c.birth_date_supported_history.ne("")|c.birth_date_additional_official.ne("")).sum()),"explicit sex union",int((c.sex_supported_history.ne("")|c.sex_additional_source_value.ne("")).sum()))
print("Social people",a.candidate_key.nunique(),"candidate/platform pairs",len(a[["candidate_key","platform"]].drop_duplicates()));print("Mayor DOB missing",int(m.birth_date_verified.eq("").sum()))

,path,rows,columns,blank_cells
0,data/processed/snapshots/pre_identity_round7_2...,1583,34,81
1,data/processed/snapshots/pre_identity_round7_2...,31660,11,73540
2,data/processed/snapshots/pre_identity_round7_2...,1502,48,46214
3,data/processed/candidate_social_account_eviden...,233,14,376
4,data/processed/meta_candidate_account_worklist...,4749,13,23343
5,data/processed/candidate_profiles_round6_20261...,18,11,15
6,data/processed/candidate_background_evidence_r...,49,9,0
7,data/processed/mayor_head_comparison_round6_20...,81,17,96
8,data/processed/candidates_2026_enriched_round6...,81,61,1464
9,data/processed/council_career_source_worklist_...,1162,19,3467

Profile gaps 733
Official birthday union 696 explicit sex union 696
Social people 87 candidate/platform pairs 201
Mayor DOB missing 22

### Assertions

In [4]:
master=frames["data/processed/snapshots/pre_identity_round7_20261019/candidate_master_current.csv"];f=frames["data/processed/snapshots/pre_identity_round7_20261019/candidate_fields_current.csv"];w=frames["data/processed/meta_candidate_account_worklist_current.csv"]
assert len(master)==1583 and len(f)==31660 and len(c)==1502 and len(w)==4749
assert w[["window_count","followers_start","followers_end"]].eq("").all().all()
assert a.candidate_key.nunique()==87 and len(a[["candidate_key","platform"]].drop_duplicates())==201
assert c.loc[c.candidate_name.eq("林德建"),"birth_date_additional_official"].iloc[0]=="1971-05-04"
assert c.loc[c.candidate_name.eq("林德建"),"sex_supported_history"].iloc[0]=="" and c.loc[c.candidate_name.eq("林德建"),"sex_additional_source_value"].iloc[0]==""
for name,birth in [("陳泓維","1987-05-08"),("林啟明","1962-05-19"),("吳建智咖啡哥","1982-05-12")]:
 row=c[c.candidate_name.eq(name)].iloc[0];assert row.birth_date_additional_official==birth and row.sex_additional_source_value=="男"
assert int(c.first_time_any_office_supported.eq("0").sum())==702 and int(c.first_time_this_office_supported.eq("0").sum())==695
h=frames["data/processed/mayor_head_comparison_round6_20261019.csv"]
assert len(h)==81 and h.county_city.nunique()==22 and h.matches_listed_elected_head.eq("1").sum()==8
assert h[h.county_city.eq("宜蘭縣")].listed_elected_head_name.eq("林姿妙").all() and h[h.county_city.eq("宜蘭縣")].government_role_name_as_captured.eq("林茂盛").all()
assert h[h.county_city.eq("雲林縣")].source_scope.eq("moi_directory_only_current_role_recheck_pending").all()
assert m.birth_date_verified.ne("").sum()==59 and m.birth_date_verified.eq("").sum()==22
lead=frames["data/processed/council_career_source_worklist_round6_20261019.csv"];assert len(lead)==1162 and lead.candidate_key.nunique()==524 and lead.claim_verified.eq("0").all()
print("PASS: saved rows/keys, candidate identity linkage, separate historical source years, unknown sex preserved, social counts, deferred post fields, mayor source limits, unvalidated career leads.")
assert m.loc[m.candidate_name.eq("陳重嘉"),"birth_date_verified"].iloc[0]=="1981-01-19"
assert m.loc[m.candidate_name.eq("温世政"),"birth_date_verified"].iloc[0]=="1973-05-04"
assert "not_government" in m.loc[m.candidate_name.eq("温世政"),"birth_date_evidence_status"].iloc[0]

PASS: saved rows/keys, candidate identity linkage, separate historical source years, unknown sex preserved, social counts, deferred post fields, mayor source limits, unvalidated career leads.

2026-10-20 維護：重複檔案改用單一保存路徑，固定指紋同步更新；議員登記CSV排版換行改為空格，政黨標籤不變。本次已獨立從raw表格重建並比對全部1,502筆及16欄；未重跑本Notebook或整條研究流程，既有執行輸出屬先前執行紀錄。