# Data Description
- Author: RUEI-HSIANG, CHANG (B12303030)，Codex協助
- Date first created: 20261019
- Background: 官方刊載背景頁與歷史公報逐欄核對；補足7人的學經歷原文、陳素月完整生日及杜文卿明載之歷史性別／曾任公職證據。
- Unit of observation: 人物頁表每候選人一列；access review每候選人×來源一列；evidence每候選人×欄位×來源一列；主表每候選人一列；fields每候選人×欄位一列。
- Sample period: 2026研究名冊；來源年代包含2012人物報導、2002–2005立委履歷、2015公報及現有公所／內政部人物頁；年代與證據層級分欄。
- Known issues: 7位有背景頁原文並非7位所有背景已核實。人物頁連結以姓名與地方情境支持，獨立身分連結仍待複核；杜文卿另以2026黨公告及歷史人物頁支持。研究所研究不認定畢業；黨籍年代有變化時不覆寫2026登記推薦政黨。戴光宗、曾亮哲title命中但無履歷正文，未填第三方學歷。社群63人／158組來源入口未改；貼文、窗口與追蹤數依指示暫緩。
- Definition for each variable:
  - candidate_key／candidate_name／county_city／electoral_district：原2026名冊鍵、姓名、縣市及選區，不以姓名單欄跨縣市合併。
  - profile_url／education_raw／experience_raw：政府人物頁或政府報社人物稿的明確原文。換行以字面\n保留，CSV每筆一個實體列。
  - source_year／evidence_tier／identity_status：來源年代、刊載層級及身分連結狀態，不能把取得日當任職起日。
  - source_file／source_sha256／source_locator／source_url：保存檔、固定hash、實際DOM或公報頁碼及原URL。
  - field／value_raw：來源支持的欄位及原始值。非首次0有明載歷史公職支持；未知不填首次1。
  - access review result／note：7份實際學經歷正文與2份title-only頁框分開。
  - council新欄sex_additional_source_value／url／year：杜文卿歷史立委頁明載男，獨立保存2002–2005來源，不混入690筆2022歷史生日／性別欄。birthday仍未知。
  - mayor birth_date_verified／evidence_status：陳素月2015公報第1頁55年1月18日換算1966-01-18，以彰化第4選區、文化大學史學系所及縣議員履歷和現任立院頁比對，排除宜蘭同名者；非戶籍認證。
  - 其餘current欄位沿用前輪定義；新增學經歷寫入議員背景，education與profile狀態同步fields/master；未自行新增分析樣本或改變納入規則。
- Data path / Role / SHA-256:
  - data/processed/government_profiles_round4_20261019.csv / verified saved collection inventory or evidence / c66f99647bba2c81b336155c9d3205fab3eab57fd6bd302d31ff669b52ada04e (7列)
  - data/processed/government_evidence_round4_20261019.csv / verified saved collection inventory or evidence / 8379a828fa123f02bf5331055d9e571a0789fa9ead8a4b71a597086e882bb1ad (25列)
  - data/processed/government_access_review_round4_20261019.csv / verified saved collection inventory or evidence / fdc97df6d2b75bb1d28b10e12dff6ece61b9c51563752ff74bc541f14883b96a (9列)
  - data/processed/candidates_2026_enriched_round4_20261019.csv / verified saved collection inventory or evidence / 37fa15d5298ba12857f55fdd87d3d3903a1dc68d7eb975995b6d228f92be4194 (81列)
  - data/processed/snapshots/pre_bulletin_round5_20261019/candidate_master_current.csv / verified saved collection inventory or evidence / df9c43800b4e67b5153ead90ad52128b922d3773c4285e3a3c079f059dbed746 (1583列)
  - data/processed/snapshots/pre_bulletin_round5_20261019/candidate_fields_current.csv / verified saved collection inventory or evidence / 3ac72c7a54ec9e6aaa0ef8c3a0501d415fccefd2537e51d778540434b84513dc (31660列)
  - data/processed/snapshots/pre_bulletin_round5_20261019/council_background_20261019.csv / verified saved collection inventory or evidence / 46dbe63f4d57ef57efba0497d4d3e906c59397b738a6f4b40691af43a8243256 (1502列)

- Source data: pre_government_round4_20261019三表快照、縣市長round3及兩批raw manifest，精確SHA已固定在處理Notebook PINS。
- Processing code: data/code/government_profiles_round4_20261019.ipynb，clean kernel已執行並保留輸出。
- Role: processed collection inventory / evidence；非最終分析樣本，未做統計推論。
- Verification status: 下方重讀保存檔檢查hash、列數、鍵與新增值；處理程式另檢查literal原文／實際DOM、未動欄位與CSV實體行。
- Downstream analysis input: current三表及縣市長round4；source_expansion舊三表已封存並將歷史程式改寫封存路徑，不覆寫latest current。前輪舊文件只驗證其原版本，不當作本輪57人生日之文件。


版本註記：本輪原current檔已封存至snapshots/pre_bulletin_round5_20261019，最新current改由council_bulletin_round5_20261019.ipynb產出。

In [1]:
from pathlib import Path
import json,hashlib,pandas as pd
ROOT=next(p for p in [Path.cwd(),*Path.cwd().parents] if (p/'AGENTS.md').exists() and (p/'templates').is_dir())
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def read(p):return pd.read_csv(ROOT/p,dtype=str).fillna('')

## Change for Your Own Data

In [2]:
FRAMES={}
assert sha(ROOT/'data/processed/government_profiles_round4_20261019.csv')=='c66f99647bba2c81b336155c9d3205fab3eab57fd6bd302d31ff669b52ada04e'
FRAMES['data/processed/government_profiles_round4_20261019.csv']=read('data/processed/government_profiles_round4_20261019.csv')
assert len(FRAMES['data/processed/government_profiles_round4_20261019.csv'])==7
assert sha(ROOT/'data/processed/government_evidence_round4_20261019.csv')=='8379a828fa123f02bf5331055d9e571a0789fa9ead8a4b71a597086e882bb1ad'
FRAMES['data/processed/government_evidence_round4_20261019.csv']=read('data/processed/government_evidence_round4_20261019.csv')
assert len(FRAMES['data/processed/government_evidence_round4_20261019.csv'])==25
assert sha(ROOT/'data/processed/government_access_review_round4_20261019.csv')=='fdc97df6d2b75bb1d28b10e12dff6ece61b9c51563752ff74bc541f14883b96a'
FRAMES['data/processed/government_access_review_round4_20261019.csv']=read('data/processed/government_access_review_round4_20261019.csv')
assert len(FRAMES['data/processed/government_access_review_round4_20261019.csv'])==9
assert sha(ROOT/'data/processed/candidates_2026_enriched_round4_20261019.csv')=='37fa15d5298ba12857f55fdd87d3d3903a1dc68d7eb975995b6d228f92be4194'
FRAMES['data/processed/candidates_2026_enriched_round4_20261019.csv']=read('data/processed/candidates_2026_enriched_round4_20261019.csv')
assert len(FRAMES['data/processed/candidates_2026_enriched_round4_20261019.csv'])==81
assert sha(ROOT/'data/processed/snapshots/pre_bulletin_round5_20261019/candidate_master_current.csv')=='df9c43800b4e67b5153ead90ad52128b922d3773c4285e3a3c079f059dbed746'
FRAMES['data/processed/snapshots/pre_bulletin_round5_20261019/candidate_master_current.csv']=read('data/processed/snapshots/pre_bulletin_round5_20261019/candidate_master_current.csv')
assert len(FRAMES['data/processed/snapshots/pre_bulletin_round5_20261019/candidate_master_current.csv'])==1583
assert sha(ROOT/'data/processed/snapshots/pre_bulletin_round5_20261019/candidate_fields_current.csv')=='3ac72c7a54ec9e6aaa0ef8c3a0501d415fccefd2537e51d778540434b84513dc'
FRAMES['data/processed/snapshots/pre_bulletin_round5_20261019/candidate_fields_current.csv']=read('data/processed/snapshots/pre_bulletin_round5_20261019/candidate_fields_current.csv')
assert len(FRAMES['data/processed/snapshots/pre_bulletin_round5_20261019/candidate_fields_current.csv'])==31660
assert sha(ROOT/'data/processed/snapshots/pre_bulletin_round5_20261019/council_background_20261019.csv')=='46dbe63f4d57ef57efba0497d4d3e906c59397b738a6f4b40691af43a8243256'
FRAMES['data/processed/snapshots/pre_bulletin_round5_20261019/council_background_20261019.csv']=read('data/processed/snapshots/pre_bulletin_round5_20261019/council_background_20261019.csv')
assert len(FRAMES['data/processed/snapshots/pre_bulletin_round5_20261019/council_background_20261019.csv'])==1502

## Summary

In [3]:
for p,d in FRAMES.items():print(p,{'rows':len(d),'columns':len(d.columns)})

data/processed/government_profiles_round4_20261019.csv {'rows': 7, 'columns': 12}
data/processed/government_evidence_round4_20261019.csv {'rows': 25, 'columns': 13}
data/processed/government_access_review_round4_20261019.csv {'rows': 9, 'columns': 7}
data/processed/candidates_2026_enriched_round4_20261019.csv {'rows': 81, 'columns': 55}
data/processed/snapshots/pre_bulletin_round5_20261019/candidate_master_current.csv {'rows': 1583, 'columns': 34}
data/processed/snapshots/pre_bulletin_round5_20261019/candidate_fields_current.csv {'rows': 31660, 'columns': 11}
data/processed/snapshots/pre_bulletin_round5_20261019/council_background_20261019.csv {'rows': 1502, 'columns': 33}

### Sample

In [4]:
for p,d in FRAMES.items():
 print(p);display(d.head(10))

data/processed/government_profiles_round4_20261019.csv

,candidate_key,candidate_name,county_city,electoral_district,profile_url,education_raw,experience_raw,source_year,evidence_tier,identity_status,source_file,source_sha256
0,2026|縣市議員|南投縣第1選舉區|廖詒綉,廖詒綉,南投縣,南投縣第1選舉區,https://www.moi.gov.tw/LocalOfficial_Content.a...,亞洲大學經營管理學系碩士,1.南投市民代表會第9~12屆市民代表\n2.中國國民黨第13、14屆全國青工總會總會長\n...,captured_2026_source_term_2022,government_published_profile_not_degree_certif...,source_name_county_context_reviewed_independen...,data/raw/background_expansion_20261019/4a24327...,cae49d6cae15158c44541bf558932315d4dd3d445867d5...
1,2026|縣市議員|金門縣第1選舉區|戴德滿,戴德滿,金門縣,金門縣第1選舉區,https://www.kmdn.gov.tw/1117/1271/4189/209125/,愛華國小，金城國中，第一士校，陸軍官校憲兵科,桃園112憲兵隊少校調查官，東森警備保全股份有限公司負責人，桃園縣金門同鄉會理事長,2012,government_hosted_newspaper_profile_not_govern...,source_name_county_context_reviewed_independen...,data/raw/background_expansion_20261019/97facb5...,4296d775f9340dfd53666f707730d164da8d6f4af74243...
2,2026|縣市議員|嘉義縣第2選舉區|何秀英,何秀英,嘉義縣,嘉義縣第2選舉區,https://www.moi.gov.tw/LocalOfficial_Content.a...,新港國中畢業,"新港鄉農會第14,15屆理事\n新港鄉民代表\n第三屆嘉南農田水利會會務委員",captured_2026_source_term_2022,government_published_profile_not_degree_certif...,source_name_county_context_reviewed_independen...,data/raw/background_expansion_20261019/5379b34...,1a56d44af9c7f3187dec4ac02b3ab7e1d69b70895e2bac...
3,2026|縣市議員|嘉義縣第3選舉區|陳靖雅,陳靖雅,嘉義縣,嘉義縣第3選舉區,https://www.moi.gov.tw/LocalOfficial_Content.a...,南華大學旅遊事業管理學系,一、專任導遊。\n二、陳信文議員服務處主任。,captured_2026_source_term_2022,government_published_profile_not_degree_certif...,source_name_county_context_reviewed_independen...,data/raw/background_expansion_20261019/b59bfa2...,105494a4ed81a80e77a3a4fb56d9ad80f1651bd5ebab2b...
4,2026|縣市議員|苗栗縣第2選舉區|謝昌年,謝昌年,苗栗縣,苗栗縣第2選舉區,https://www.tongluo.gov.tw/cp.aspx?n=3341,育達科技大學休閒事業管理學系,"銅鑼鄉第17.18.19屆代表,銅鑼鄉第18屆主席",captured_2026_source_term_2022,government_published_profile_not_degree_certif...,source_name_county_context_reviewed_independen...,data/raw/background_expansion_20261019/2a8a84d...,5e5b30590457d9f2605b279e3b56e9b8449c20b6d14acd...
5,2026|縣市議員|苗栗縣第3選舉區|杜文卿,杜文卿,苗栗縣,苗栗縣第3選舉區,https://www.ly.gov.tw/Pages/List.aspx?nodeid=1126,美國加州大學長堤分校國際社工研究所研究,民進黨苗栗縣黨部主委、 | 民進黨中央執行委員、 | 民進黨中央評議委員、 | 國代主席團主...,2002-2005_term5,government_published_profile_not_degree_certif...,source_name_county_context_reviewed_independen...,data/raw/background_expansion_20261019/f040dc2...,8df4a341482cdb1791793fb34ccbffd52199e788b09924...
6,2026|縣市議員|苗栗縣第6選舉區|詹錦章,詹錦章,苗栗縣,苗栗縣第6選舉區,https://www.juolan.gov.tw/cp.aspx?n=3137,高工補校畢業,卓蘭鎮農會理事長 | 卓蘭鎮農會常務監事 | 新榮里第19、20屆里長,captured_2026_source_term_2022,government_published_profile_not_degree_certif...,source_name_county_context_reviewed_independen...,data/raw/background_expansion_20261019/db2ca39...,f8afa62fffbac349bf1d4054a6e4d9efb433c96e6e634e...

data/processed/government_evidence_round4_20261019.csv

,candidate_key,candidate_name,county_city,field,value_raw,source_url,source_file,source_sha256,source_locator,source_year,evidence_tier,identity_status,checked_date
0,2026|縣市議員|南投縣第1選舉區|廖詒綉,廖詒綉,南投縣,profile,https://www.moi.gov.tw/LocalOfficial_Content.a...,https://www.moi.gov.tw/LocalOfficial_Content.a...,data/raw/background_expansion_20261019/4a24327...,cae49d6cae15158c44541bf558932315d4dd3d445867d5...,"div.essay: caption 學歷／簡歷, div.p",captured_2026_source_term_2022,government_published_profile_not_degree_certif...,source_name_county_context_reviewed_independen...,2026-10-19
1,2026|縣市議員|南投縣第1選舉區|廖詒綉,廖詒綉,南投縣,education,亞洲大學經營管理學系碩士,https://www.moi.gov.tw/LocalOfficial_Content.a...,data/raw/background_expansion_20261019/4a24327...,cae49d6cae15158c44541bf558932315d4dd3d445867d5...,"div.essay: caption 學歷／簡歷, div.p",captured_2026_source_term_2022,government_published_profile_not_degree_certif...,source_name_county_context_reviewed_independen...,2026-10-19
2,2026|縣市議員|南投縣第1選舉區|廖詒綉,廖詒綉,南投縣,experience,1.南投市民代表會第9~12屆市民代表\n2.中國國民黨第13、14屆全國青工總會總會長\n...,https://www.moi.gov.tw/LocalOfficial_Content.a...,data/raw/background_expansion_20261019/4a24327...,cae49d6cae15158c44541bf558932315d4dd3d445867d5...,"div.essay: caption 學歷／簡歷, div.p",captured_2026_source_term_2022,government_published_profile_not_degree_certif...,source_name_county_context_reviewed_independen...,2026-10-19
3,2026|縣市議員|金門縣第1選舉區|戴德滿,戴德滿,金門縣,profile,https://www.kmdn.gov.tw/1117/1271/4189/209125/,https://www.kmdn.gov.tw/1117/1271/4189/209125/,data/raw/background_expansion_20261019/97facb5...,4296d775f9340dfd53666f707730d164da8d6f4af74243...,人物小檔案：學歷／經歷；2012-05-05報導,2012,government_hosted_newspaper_profile_not_govern...,source_name_county_context_reviewed_independen...,2026-10-19
4,2026|縣市議員|金門縣第1選舉區|戴德滿,戴德滿,金門縣,education,愛華國小，金城國中，第一士校，陸軍官校憲兵科,https://www.kmdn.gov.tw/1117/1271/4189/209125/,data/raw/background_expansion_20261019/97facb5...,4296d775f9340dfd53666f707730d164da8d6f4af74243...,人物小檔案：學歷／經歷；2012-05-05報導,2012,government_hosted_newspaper_profile_not_govern...,source_name_county_context_reviewed_independen...,2026-10-19
5,2026|縣市議員|金門縣第1選舉區|戴德滿,戴德滿,金門縣,experience,桃園112憲兵隊少校調查官，東森警備保全股份有限公司負責人，桃園縣金門同鄉會理事長,https://www.kmdn.gov.tw/1117/1271/4189/209125/,data/raw/background_expansion_20261019/97facb5...,4296d775f9340dfd53666f707730d164da8d6f4af74243...,人物小檔案：學歷／經歷；2012-05-05報導,2012,government_hosted_newspaper_profile_not_govern...,source_name_county_context_reviewed_independen...,2026-10-19
6,2026|縣市議員|嘉義縣第2選舉區|何秀英,何秀英,嘉義縣,profile,https://www.moi.gov.tw/LocalOfficial_Content.a...,https://www.moi.gov.tw/LocalOfficial_Content.a...,data/raw/background_expansion_20261019/5379b34...,1a56d44af9c7f3187dec4ac02b3ab7e1d69b70895e2bac...,"div.essay: caption 學歷／簡歷, div.p",captured_2026_source_term_2022,government_published_profile_not_degree_certif...,source_name_county_context_reviewed_independen...,2026-10-19
7,2026|縣市議員|嘉義縣第2選舉區|何秀英,何秀英,嘉義縣,education,新港國中畢業,https://www.moi.gov.tw/LocalOfficial_Content.a...,data/raw/background_expansion_20261019/5379b34...,1a56d44af9c7f3187dec4ac02b3ab7e1d69b70895e2bac...,"div.essay: caption 學歷／簡歷, div.p",captured_2026_source_term_2022,government_published_profile_not_degree_certif...,source_name_county_context_reviewed_independen...,2026-10-19
8,2026|縣市議員|嘉義縣第2選舉區|何秀英,何秀英,嘉義縣,experience,"新港鄉農會第14,15屆理事\n新港鄉民代表\n第三屆嘉南農田水利會會務委員",https://www.moi.gov.tw/LocalOfficial_Content.a...,data/raw/background_expansion_20261019/5379b34...,1a56d44af9c7f3187dec4ac02b3ab7e1d69b70895e2bac...,"div.essay: caption 學歷／簡歷, div.p",captured_2026_source_term_2022,government_published_profile_not_degree_certif...,source_name_county_context_reviewed_independen...,2026-10-19
9,2026|縣市議員|嘉義縣第3選舉區|陳靖雅,陳靖雅,嘉義縣,profile,https://www.moi.gov.tw/LocalOfficial_Content.a...,https://www.moi.gov.tw/LocalOfficial_Content.a...,data/raw/background_expansion_20261019/b59bfa2...,105494a4ed81a80e77a3a4fb56d9ad80f1651bd5ebab2b...,"div.essay: caption 學歷／簡歷, div.p",captured_2026_source_term_2022,government_published_profile_not_degree_certif...,source_name_county_context_reviewed_independen...,2026-10-19

data/processed/government_access_review_round4_20261019.csv

,candidate_key,candidate_name,source_url,source_file,source_sha256,result,note
0,2026|縣市議員|南投縣第1選舉區|廖詒綉,廖詒綉,https://www.moi.gov.tw/LocalOfficial_Content.a...,data/raw/background_expansion_20261019/4a24327...,cae49d6cae15158c44541bf558932315d4dd3d445867d5...,explicit_education_and_experience_fields_read,保留原文字；未從軍校、姓名、照片或親屬角色推定性別。
1,2026|縣市議員|金門縣第1選舉區|戴德滿,戴德滿,https://www.kmdn.gov.tw/1117/1271/4189/209125/,data/raw/background_expansion_20261019/97facb5...,4296d775f9340dfd53666f707730d164da8d6f4af74243...,explicit_education_and_experience_fields_read,保留原文字；未從軍校、姓名、照片或親屬角色推定性別。
2,2026|縣市議員|嘉義縣第2選舉區|何秀英,何秀英,https://www.moi.gov.tw/LocalOfficial_Content.a...,data/raw/background_expansion_20261019/5379b34...,1a56d44af9c7f3187dec4ac02b3ab7e1d69b70895e2bac...,explicit_education_and_experience_fields_read,保留原文字；未從軍校、姓名、照片或親屬角色推定性別。
3,2026|縣市議員|嘉義縣第3選舉區|陳靖雅,陳靖雅,https://www.moi.gov.tw/LocalOfficial_Content.a...,data/raw/background_expansion_20261019/b59bfa2...,105494a4ed81a80e77a3a4fb56d9ad80f1651bd5ebab2b...,explicit_education_and_experience_fields_read,保留原文字；未從軍校、姓名、照片或親屬角色推定性別。
4,2026|縣市議員|苗栗縣第2選舉區|謝昌年,謝昌年,https://www.tongluo.gov.tw/cp.aspx?n=3341,data/raw/background_expansion_20261019/2a8a84d...,5e5b30590457d9f2605b279e3b56e9b8449c20b6d14acd...,explicit_education_and_experience_fields_read,保留原文字；未從軍校、姓名、照片或親屬角色推定性別。
5,2026|縣市議員|苗栗縣第3選舉區|杜文卿,杜文卿,https://www.ly.gov.tw/Pages/List.aspx?nodeid=1126,data/raw/background_expansion_20261019/f040dc2...,8df4a341482cdb1791793fb34ccbffd52199e788b09924...,explicit_education_and_experience_fields_read,保留原文字；未從軍校、姓名、照片或親屬角色推定性別。
6,2026|縣市議員|苗栗縣第6選舉區|詹錦章,詹錦章,https://www.juolan.gov.tw/cp.aspx?n=3137,data/raw/background_expansion_20261019/db2ca39...,f8afa62fffbac349bf1d4054a6e4d9efb433c96e6e634e...,explicit_education_and_experience_fields_read,保留原文字；未從軍校、姓名、照片或親屬角色推定性別。
7,2026|縣市議員|嘉義縣第1選舉區|戴光宗,戴光宗,https://www.cyscc.gov.tw/Parliamentary_Content...,data/raw/background_expansion_20261019/8b852a1...,e0f28b71bde3fe6e777d0ec983ecbe735c531341086ef8...,page_title_only_no_readable_profile_fields,HTTP200與title姓名命中不當作人物履歷；不抄第三方摘要。
8,2026|縣市議員|嘉義縣第6選舉區|曾亮哲,曾亮哲,https://www.cyscc.gov.tw/Parliamentary_Content...,data/raw/background_expansion_20261019/a5f3414...,fd478762711a58d7f96988e0e3a6ad983401ed373d700b...,page_title_only_no_readable_profile_fields,HTTP200與title姓名命中不當作人物履歷；不抄第三方摘要。

data/processed/candidates_2026_enriched_round4_20261019.csv

,candidate_key,county_city,registration_date_roc,candidate_name,party_recommendation_original,source_note,office_type,source_file,source_page,source_url,...,prior_mayor_evidence_file,first_time_any_evidence_status,first_time_mayor_evidence_status,no_prior_mayor_match_in_available_archive,identity_conflict_notes,background_collection_status,sex_source_tier,sex_evidence_status,sex_directory_supplement,sex_directory_source_url
0,2026-C1-001,臺北市,115/08/31,郭璽,台灣麻將最大黨,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,,prior_CEC_record_name_and_birth_date_corroborated,,1,,partial_with_sources,historical_CEC,dob_corroborated_by_media,,
1,2026-C1-002,臺北市,115/09/02,沈伯洋,民主進步黨,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,,positive_prior_elected_office_evidence,,1,,partial_with_sources,official_profile,source_observation,,
2,2026-C1-003,臺北市,115/09/02,蕭文乾,臺灣SoR無法黨,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,,positive_prior_elected_office_evidence,,1,,partial_with_sources,official_bulletin,visually_checked_pdf_cell,,
3,2026-C1-004,臺北市,115/09/03,唐新民,三勢團結促進聯盟,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,data/raw/cec_all_offices/100_elcand.csv,prior_CEC_record_name_and_birth_date_corroborated,prior_CEC_mayoral_record_name_and_birth_date_c...,0,,partial_with_sources,historical_CEC,dob_corroborated_by_media,,
4,2026-C1-005,臺北市,115/09/04,蔣萬安,中國國民黨,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,data/raw/cec_all_offices/100_elcand.csv,prior_CEC_record_name_and_birth_date_corroborated,prior_CEC_mayoral_record_name_and_birth_date_c...,0,,partial_with_sources,historical_CEC,dob_corroborated_by_media,,
5,2026-C1-006,臺北市,115/09/04,林志成,無,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,,prior_CEC_record_name_and_birth_date_corroborated,,1,8 historical namesake/date conflicts excluded;...,partial_with_sources,historical_CEC,dob_corroborated_by_media,,
6,2026-C1-007,新北市,115/09/02,蘇巧慧,民主進步黨,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,,positive_prior_elected_office_evidence,,1,,partial_with_sources,official_profile,source_observation,,
7,2026-C1-008,新北市,115/09/04,李四川,中國國民黨,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,,,,1,2 historical namesake/date conflicts excluded;...,partial_with_sources,official_government_sex,explicit_sex_role_identity_matched,,
8,2026-C1-009,新北市,115/09/04,蘇輝湟,無,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,,prior_CEC_record_name_and_birth_date_corroborated,,1,,partial_with_sources,historical_CEC,dob_corroborated_by_media,,
9,2026-C1-010,桃園市,115/09/01,張善政,中國國民黨,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,data/raw/cec_all_offices/100_elcand.csv,prior_CEC_record_name_and_birth_date_corroborated,prior_CEC_mayoral_record_name_and_birth_date_c...,0,,partial_with_sources,historical_CEC,dob_corroborated_by_media,,

data/processed/snapshots/pre_bulletin_round5_20261019/candidate_master_current.csv

,candidate_key,candidate_name,office_type,county_city,electoral_district,party_registration_raw,registration_source,registration_source_file,registration_source_page,qualification_inherited,...,Threads_status,posts_Facebook_status,posts_Instagram_status,posts_Threads_status,followers_status,policy_text_status,visual_status,political_family_status,administrative_experience_status,qualification_status
0,2026-C1-001,郭璽,直轄市長,臺北市,,台灣麻將最大黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
1,2026-C1-002,沈伯洋,直轄市長,臺北市,,民主進步黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,人物頁／競選頁已列帳號連結；目標內容待核對,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,部分原文已保存，尚未政策編碼,未查找,未查找,未查找,官方內文待重新核對
2,2026-C1-003,蕭文乾,直轄市長,臺北市,,臺灣SoR無法黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
3,2026-C1-004,唐新民,直轄市長,臺北市,,三勢團結促進聯盟,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
4,2026-C1-005,蔣萬安,直轄市長,臺北市,,中國國民黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
5,2026-C1-006,林志成,直轄市長,臺北市,,無,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
6,2026-C1-007,蘇巧慧,直轄市長,新北市,,民主進步黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,人物頁／競選頁已列帳號連結；目標內容待核對,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,部分原文已保存，尚未政策編碼,未查找,未查找,未查找,官方內文待重新核對
7,2026-C1-008,李四川,直轄市長,新北市,,中國國民黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,人物頁／競選頁已列帳號連結；目標內容待核對,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
8,2026-C1-009,蘇輝湟,直轄市長,新北市,,無,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
9,2026-C1-010,張善政,直轄市長,桃園市,,中國國民黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對

data/processed/snapshots/pre_bulletin_round5_20261019/candidate_fields_current.csv

,candidate_key,candidate_name,office_type,county_city,field,status,existing_value,evidence,note,next_source,updated_date
0,2026-C1-001,郭璽,直轄市長,臺北市,sex,已有資料，待來源複核,男,https://db.cec.gov.tw/,dob_corroborated_by_media,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
1,2026-C1-001,郭璽,直轄市長,臺北市,birth_date,已有資料，待來源複核,1958-08-31,https://db.cec.gov.tw/,CEC_name_and_birth_date_corroborated_by_CNA,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
2,2026-C1-001,郭璽,直轄市長,臺北市,education,已有資料，待來源複核,大學,,歷史公報或媒體補充，非2026學歷認證,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
3,2026-C1-001,郭璽,直轄市長,臺北市,incumbency,既有搜尋後仍缺，待補查,,,,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
4,2026-C1-001,郭璽,直轄市長,臺北市,first_time_this_office,既有搜尋後仍缺，待補查,,,0=有過參選證據；空白不表示首次。此處沿用既有表。,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
5,2026-C1-001,郭璽,直轄市長,臺北市,first_time_any_office,已有資料，待來源複核,0,https://db.cec.gov.tw/,0=有過參選證據；空白不表示首次。此處沿用既有表。,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
6,2026-C1-001,郭璽,直轄市長,臺北市,profile,既有搜尋後仍缺，待補查,,,,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
7,2026-C1-001,郭璽,直轄市長,臺北市,website,既有搜尋後仍缺，待補查,,,,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
8,2026-C1-001,郭璽,直轄市長,臺北市,Facebook,尚未驗證，不代表無帳號,,,,官方人物頁／競選網站交叉連結,2026-10-19
9,2026-C1-001,郭璽,直轄市長,臺北市,Instagram,尚未驗證，不代表無帳號,,,,官方人物頁／競選網站交叉連結,2026-10-19

data/processed/snapshots/pre_bulletin_round5_20261019/council_background_20261019.csv

,candidate_key,candidate_name,county_city,office_type,electoral_district,party_registration_raw,birth_date_supported_history,birth_year_supported_history,sex_supported_history,birth_sex_evidence_status,...,incumbency_2026,incumbency_status,updated_date,additional_profile_url,additional_profile_status,birth_date_self_declared,birth_date_self_declared_source,sex_additional_source_value,sex_additional_source_url,sex_additional_source_year
0,2026|直轄市議員|臺北市第1選舉區|謝閔弘,謝閔弘,臺北市,直轄市議員,臺北市第1選舉區,時代力量,,,,尚無可連結的歷史紀錄,...,,未由歷史當選或履歷自動推定,2026-10-19,,,,,,,
1,2026|直轄市議員|臺北市第1選舉區|李文,李文,臺北市,直轄市議員,臺北市第1選舉區,無,,,,尚無可連結的歷史紀錄,...,,未由歷史當選或履歷自動推定,2026-10-19,,,,,,,
2,2026|直轄市議員|臺北市第1選舉區|陳彥廷,陳彥廷,臺北市,直轄市議員,臺北市第1選舉區,無,,,,尚無可連結的歷史紀錄,...,,未由歷史當選或履歷自動推定,2026-10-19,,,,,,,
3,2026|直轄市議員|臺北市第1選舉區|鍾佩玲,鍾佩玲,臺北市,直轄市議員,臺北市第1選舉區,民主進步黨,1979-03-27,1979,女,2022官方申報，先前身分連結審核有支持；非2026戶籍認定,...,,未由歷史當選或履歷自動推定,2026-10-19,,,,,,,
4,2026|直轄市議員|臺北市第1選舉區|紀建漢,紀建漢,臺北市,直轄市議員,臺北市第1選舉區,無,,,,尚無可連結的歷史紀錄,...,,未由歷史當選或履歷自動推定,2026-10-19,,,,,,,
5,2026|直轄市議員|臺北市第1選舉區|陳賢蔚,陳賢蔚,臺北市,直轄市議員,臺北市第1選舉區,民主進步黨,1977-07-12,1977,男,2022官方申報，先前身分連結審核有支持；非2026戶籍認定,...,,未由歷史當選或履歷自動推定,2026-10-19,,,,,,,
6,2026|直轄市議員|臺北市第1選舉區|林世宗,林世宗,臺北市,直轄市議員,臺北市第1選舉區,民主進步黨,1959-06-13,1959,男,2022官方申報，先前身分連結審核有支持；非2026戶籍認定,...,,未由歷史當選或履歷自動推定,2026-10-19,,,,,,,
7,2026|直轄市議員|臺北市第1選舉區|黃瀞瑩,黃瀞瑩,臺北市,直轄市議員,臺北市第1選舉區,台灣民眾黨,1992-06-10,1992,女,2022官方申報，先前身分連結審核有支持；非2026戶籍認定,...,,未由歷史當選或履歷自動推定,2026-10-19,,,,,,,
8,2026|直轄市議員|臺北市第1選舉區|林揚庭,林揚庭,臺北市,直轄市議員,臺北市第1選舉區,中國國民黨,,,,尚無可連結的歷史紀錄,...,,未由歷史當選或履歷自動推定,2026-10-19,,,,,,,
9,2026|直轄市議員|臺北市第1選舉區|陳慈慧,陳慈慧,臺北市,直轄市議員,臺北市第1選舉區,民主進步黨,1983-11-22,1983,女,2022官方申報，先前身分連結審核有支持；非2026戶籍認定,...,,未由歷史當選或履歷自動推定,2026-10-19,,,,,,,

### Summary Stats

In [5]:
display(FRAMES['data/processed/government_access_review_round4_20261019.csv'].result.value_counts().to_frame('來源數'))

                                               來源數
result
explicit_education_and_experience_fields_read    7
page_title_only_no_readable_profile_fields       2

### Assertions

In [6]:
profiles=FRAMES['data/processed/government_profiles_round4_20261019.csv'];e=FRAMES['data/processed/government_evidence_round4_20261019.csv'];audit=FRAMES['data/processed/government_access_review_round4_20261019.csv'];y=FRAMES['data/processed/candidates_2026_enriched_round4_20261019.csv'];m=FRAMES['data/processed/snapshots/pre_bulletin_round5_20261019/candidate_master_current.csv'];f=FRAMES['data/processed/snapshots/pre_bulletin_round5_20261019/candidate_fields_current.csv'];c=FRAMES['data/processed/snapshots/pre_bulletin_round5_20261019/council_background_20261019.csv']
assert len(profiles)==7 and profiles.candidate_key.is_unique
assert len(audit)==9 and audit.result.eq('page_title_only_no_readable_profile_fields').sum()==2
assert len(e)==25 and not e.duplicated(['candidate_key','field','source_url']).any()
assert len(m)==1583 and m.candidate_key.is_unique and len(f)==31660 and not f.duplicated(['candidate_key','field']).any()
assert len(c)==1502 and c.candidate_key.is_unique
assert y.birth_date_verified.ne('').sum()==57 and y[y.candidate_name.eq('陳素月')].iloc[0].birth_date_verified=='1966-01-18'
assert y[y.candidate_name.eq('魏造文')].iloc[0].sex_2026==''
assert c.sex_supported_history.ne('').sum()==690 and c.birth_date_supported_history.ne('').sum()==690
assert c.sex_additional_source_value.ne('').sum()==1 and c[c.candidate_name.eq('杜文卿')].iloc[0].sex_additional_source_value=='男'
assert int((c.moi_profile_url.eq('')&c.campaign_profile_url.eq('')&c.additional_profile_url.eq('')).sum())==756
old=read('data/processed/snapshots/pre_government_round4_20261019/candidate_fields_current.csv')
for field in ['incumbency','posts_Facebook','posts_Instagram','posts_Threads','followers','qualification','Facebook','Instagram','Threads','administrative_experience','political_family']:
 pd.testing.assert_frame_equal(old[old.field.eq(field)].reset_index(drop=True),f[f.field.eq(field)].reset_index(drop=True))
print('PASS：7背景頁、25逐欄證據、2頁框排除；57位縣市長完整生日；756位尚缺人物頁；保留690位2022歷史欄與未動社群／現任／貼文欄。')
print('議員非首次任何公職',int(c.first_time_any_office_supported.eq('0').sum()),'非首次議員',int(c.first_time_this_office_supported.eq('0').sum()))

PASS：7背景頁、25逐欄證據、2頁框排除；57位縣市長完整生日；756位尚缺人物頁；保留690位2022歷史欄與未動社群／現任／貼文欄。
議員非首次任何公職 695 非首次議員 692