# Data Description
- Author: RUEI-HSIANG, CHANG（B12303030；AI協助）
- Date first created: 20261019
- Background: 9位歷史身分連結接回逐欄證據；另3個人物頁實質背景，6個占位頁只留入口。
- Unit of observation: master/council/identity為候選人；fields為候選人×欄位；party為候選人頁；evidence為候選人×欄位×來源。
- Sample period: 2026名冊框架，歷史公報2022及其他年代另分欄，2026-10-19檢索。
- Known issues: 仍730人無目前幾類人物頁；153人歷史連結待核實，李柏融、柳淑芳本輪不提升。705人有跨年官方生日支持；706人明載性別聯集包含黃裕庭競選頁男性自述，不能統稱政府資料。未找到不是首次參選=1；名冊黨派與在任狀態不改。社群窗口、貼文與追蹤數暫緩。
- Definition for each variable: candidate_key沿用公職×縣市×選區×姓名鍵；birth_date_supported_history/sex_supported_history為已核對的2022申報；education_supported_history/experience_supported_history為歷史原文非當屆認證；round7_identity_url記載當屆身分橋接出處；party_page_lead_url包含占位頁；additional_profile_url僅實質頁；其餘欄位沿用[前輪資料字典](career_round6_20261019_documentation.ipynb)。本文件列示各檔完整schema、型別、缺失。
- Data path / Downstream analysis input: 下列7個實際檔，各自核對，角色均為review_inventory/evidence，尚非最終分析樣本。
- Source data: 4個pre_identity_round7快照、council_bulletin_cells_round5、人工核對設定及3份manifest，精確來源與hash見處理Notebook的PINS。
- Processing code: [council_identity_round7_20261019.ipynb](../code/council_identity_round7_20261019.ipynb)。
- Role: review inventory / evidence。
- Verification status: 下方只讀重開檢查；先前處理已執行，這裡獨立確認。
- SHA-256: 逐檔如下。
- `data/processed/snapshots/pre_cross_office_round8_20261019/candidate_master_current.csv`: 1583列、34欄；SHA-256 `0d2d2620f62cde3abaf691ce843925231bc84f95362562b16794d74aadf022e9`。
- `data/processed/snapshots/pre_cross_office_round8_20261019/candidate_fields_current.csv`: 31660列、11欄；SHA-256 `e2e4528410ee10272ddef071f431e42334e14891255277a1a44dce2203ef9b22`。
- `data/processed/snapshots/pre_cross_office_round8_20261019/council_background_20261019.csv`: 1502列、50欄；SHA-256 `f4b9055e53c7d8476f34389e4d810e26569c394c5e4916c50230b31fef7db2da`。
- `data/processed/snapshots/pre_cross_office_round8_20261019/council_history_pending_identity_current.csv`: 153列、18欄；SHA-256 `abf997cfa9ceac55cd7636db7950cfa934cb5d553183f5ff05d6181bc9bd72e0`。
- `data/processed/council_identity_review_round7_20261019.csv`: 11列、16欄；SHA-256 `624ab491f27dc8dd87bdb823f919960e7118b9b591a9c41ee63246df5f4b5be5`。
- `data/processed/party_profile_review_round7_20261019.csv`: 9列、12欄；SHA-256 `a50a882aeb2bedfbe9dfadb1d0dfb8aeaf2930ba9b51d89178151a3f6a51baa1`。
- `data/processed/candidate_evidence_round7_20261019.csv`: 70列、9欄；SHA-256 `a9a07816dc0f97566966a2d0214806a2138f7b6b3d9022f4bbdc614f9f4bf303`。

第八輪接續：本輪4份current輸出已封存至pre_cross_office_round8快照，避免舊程式覆寫最新結果；7份本輪輸出仍可獨立驗證。

In [1]:
from pathlib import Path
import json, hashlib
import pandas as pd
from IPython.display import display
ROOT=next(p for p in [Path.cwd(),*Path.cwd().parents] if (p/'AGENTS.md').exists() and (p/'data').exists())
sha=lambda p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
EXPECTED={'data/processed/snapshots/pre_cross_office_round8_20261019/candidate_master_current.csv': {'rows': 1583, 'columns': 34, 'key': ['candidate_key'], 'sha256': '0d2d2620f62cde3abaf691ce843925231bc84f95362562b16794d74aadf022e9'}, 'data/processed/snapshots/pre_cross_office_round8_20261019/candidate_fields_current.csv': {'rows': 31660, 'columns': 11, 'key': ['candidate_key', 'field'], 'sha256': 'e2e4528410ee10272ddef071f431e42334e14891255277a1a44dce2203ef9b22'}, 'data/processed/snapshots/pre_cross_office_round8_20261019/council_background_20261019.csv': {'rows': 1502, 'columns': 50, 'key': ['candidate_key'], 'sha256': 'f4b9055e53c7d8476f34389e4d810e26569c394c5e4916c50230b31fef7db2da'}, 'data/processed/snapshots/pre_cross_office_round8_20261019/council_history_pending_identity_current.csv': {'rows': 153, 'columns': 18, 'key': ['candidate_key'], 'sha256': 'abf997cfa9ceac55cd7636db7950cfa934cb5d553183f5ff05d6181bc9bd72e0'}, 'data/processed/council_identity_review_round7_20261019.csv': {'rows': 11, 'columns': 16, 'key': ['candidate_key'], 'sha256': '624ab491f27dc8dd87bdb823f919960e7118b9b591a9c41ee63246df5f4b5be5'}, 'data/processed/party_profile_review_round7_20261019.csv': {'rows': 9, 'columns': 12, 'key': ['candidate_key'], 'sha256': 'a50a882aeb2bedfbe9dfadb1d0dfb8aeaf2930ba9b51d89178151a3f6a51baa1'}, 'data/processed/candidate_evidence_round7_20261019.csv': {'rows': 70, 'columns': 9, 'key': [], 'sha256': 'a9a07816dc0f97566966a2d0214806a2138f7b6b3d9022f4bbdc614f9f4bf303'}}
D={}
for p,s in EXPECTED.items():
 assert sha(p)==s['sha256'],p
 d=pd.read_csv(ROOT/p,dtype=str,keep_default_na=False);assert d.shape==(s['rows'],s['columns'])
 if s['key']: assert not d.duplicated(s['key']).any()
 D[p]=d
print('Saved files verified:',len(D))

Saved files verified: 7

## Change for Your Own Data
僅讀固定7檔與hash，不執行處理或覆寫。

## Summary

### Sample

In [2]:
for p,d in D.items():
 print(p);display(d.head(10))

data/processed/snapshots/pre_cross_office_round8_20261019/candidate_master_current.csv

,candidate_key,candidate_name,office_type,county_city,electoral_district,party_registration_raw,registration_source,registration_source_file,registration_source_page,qualification_inherited,...,Threads_status,posts_Facebook_status,posts_Instagram_status,posts_Threads_status,followers_status,policy_text_status,visual_status,political_family_status,administrative_experience_status,qualification_status
0,2026-C1-001,郭璽,直轄市長,臺北市,,台灣麻將最大黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
1,2026-C1-002,沈伯洋,直轄市長,臺北市,,民主進步黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,人物頁／競選頁已列帳號連結；目標內容待核對,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,部分原文已保存，尚未政策編碼,未查找,未查找,未查找,官方內文待重新核對
2,2026-C1-003,蕭文乾,直轄市長,臺北市,,臺灣SoR無法黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
3,2026-C1-004,唐新民,直轄市長,臺北市,,三勢團結促進聯盟,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
4,2026-C1-005,蔣萬安,直轄市長,臺北市,,中國國民黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
5,2026-C1-006,林志成,直轄市長,臺北市,,無,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
6,2026-C1-007,蘇巧慧,直轄市長,新北市,,民主進步黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,人物頁／競選頁已列帳號連結；目標內容待核對,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,部分原文已保存，尚未政策編碼,未查找,未查找,未查找,官方內文待重新核對
7,2026-C1-008,李四川,直轄市長,新北市,,中國國民黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,人物頁／競選頁已列帳號連結；目標內容待核對,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
8,2026-C1-009,蘇輝湟,直轄市長,新北市,,無,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
9,2026-C1-010,張善政,直轄市長,桃園市,,中國國民黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對

data/processed/snapshots/pre_cross_office_round8_20261019/candidate_fields_current.csv

,candidate_key,candidate_name,office_type,county_city,field,status,existing_value,evidence,note,next_source,updated_date
0,2026-C1-001,郭璽,直轄市長,臺北市,sex,已有資料，待來源複核,男,https://db.cec.gov.tw/,dob_corroborated_by_media,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
1,2026-C1-001,郭璽,直轄市長,臺北市,birth_date,已有資料，待來源複核,1958-08-31,https://db.cec.gov.tw/,CEC_name_and_birth_date_corroborated_by_CNA,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
2,2026-C1-001,郭璽,直轄市長,臺北市,education,已有資料，待來源複核,大學,,歷史公報或媒體補充，非2026學歷認證,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
3,2026-C1-001,郭璽,直轄市長,臺北市,incumbency,既有搜尋後仍缺，待補查,,,,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
4,2026-C1-001,郭璽,直轄市長,臺北市,first_time_this_office,既有搜尋後仍缺，待補查,,,0=有過參選證據；空白不表示首次。此處沿用既有表。,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
5,2026-C1-001,郭璽,直轄市長,臺北市,first_time_any_office,已有資料，待來源複核,0,https://db.cec.gov.tw/,0=有過參選證據；空白不表示首次。此處沿用既有表。,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
6,2026-C1-001,郭璽,直轄市長,臺北市,profile,既有搜尋後仍缺，待補查,,,,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
7,2026-C1-001,郭璽,直轄市長,臺北市,website,既有搜尋後仍缺，待補查,,,,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
8,2026-C1-001,郭璽,直轄市長,臺北市,Facebook,尚未驗證，不代表無帳號,,,,官方人物頁／競選網站交叉連結,2026-10-19
9,2026-C1-001,郭璽,直轄市長,臺北市,Instagram,尚未驗證，不代表無帳號,,,,官方人物頁／競選網站交叉連結,2026-10-19

data/processed/snapshots/pre_cross_office_round8_20261019/council_background_20261019.csv

,candidate_key,candidate_name,county_city,office_type,electoral_district,party_registration_raw,birth_date_supported_history,birth_year_supported_history,sex_supported_history,birth_sex_evidence_status,...,bulletin_source_page,bulletin_identity_status,birth_date_additional_official,birth_date_additional_source_url,birth_date_additional_evidence_status,round6_profile_urls,birth_date_additional_source_year,additional_historical_education_cec,round7_identity_url,party_page_lead_url
0,2026|直轄市議員|臺北市第1選舉區|謝閔弘,謝閔弘,臺北市,直轄市議員,臺北市第1選舉區,時代力量,,,,尚無可連結的歷史紀錄,...,,,,,,,,,,
1,2026|直轄市議員|臺北市第1選舉區|李文,李文,臺北市,直轄市議員,臺北市第1選舉區,無,,,,尚無可連結的歷史紀錄,...,,,,,,,,,,
2,2026|直轄市議員|臺北市第1選舉區|陳彥廷,陳彥廷,臺北市,直轄市議員,臺北市第1選舉區,無,,,,尚無可連結的歷史紀錄,...,,,,,,,,,,
3,2026|直轄市議員|臺北市第1選舉區|鍾佩玲,鍾佩玲,臺北市,直轄市議員,臺北市第1選舉區,民主進步黨,1979-03-27,1979,女,2022官方申報，先前身分連結審核有支持；非2026戶籍認定,...,,,,,,,,,,
4,2026|直轄市議員|臺北市第1選舉區|紀建漢,紀建漢,臺北市,直轄市議員,臺北市第1選舉區,無,,,,尚無可連結的歷史紀錄,...,,,,,,,,,,
5,2026|直轄市議員|臺北市第1選舉區|陳賢蔚,陳賢蔚,臺北市,直轄市議員,臺北市第1選舉區,民主進步黨,1977-07-12,1977,男,2022官方申報，先前身分連結審核有支持；非2026戶籍認定,...,,,,,,,,,,
6,2026|直轄市議員|臺北市第1選舉區|林世宗,林世宗,臺北市,直轄市議員,臺北市第1選舉區,民主進步黨,1959-06-13,1959,男,2022官方申報，先前身分連結審核有支持；非2026戶籍認定,...,,,,,,,,,,
7,2026|直轄市議員|臺北市第1選舉區|黃瀞瑩,黃瀞瑩,臺北市,直轄市議員,臺北市第1選舉區,台灣民眾黨,1992-06-10,1992,女,2022官方申報，先前身分連結審核有支持；非2026戶籍認定,...,,,,,,,,,,
8,2026|直轄市議員|臺北市第1選舉區|林揚庭,林揚庭,臺北市,直轄市議員,臺北市第1選舉區,中國國民黨,,,,尚無可連結的歷史紀錄,...,,,,,,,,,,
9,2026|直轄市議員|臺北市第1選舉區|陳慈慧,陳慈慧,臺北市,直轄市議員,臺北市第1選舉區,民主進步黨,1983-11-22,1983,女,2022官方申報，先前身分連結審核有支持；非2026戶籍認定,...,,,,,,,,,,

data/processed/snapshots/pre_cross_office_round8_20261019/council_history_pending_identity_current.csv

,candidate_key,candidate_name,county_city,electoral_district,same_district_number,birth_date_history_candidate,identity_status,profile_evidence_present,history_name,history_county,history_district,history_birth_roc,history_sex,history_education,history_file,history_row,history_archive_member,source_sha256
0,2026|直轄市議員|臺北市第2選舉區|吳欣岱,吳欣岱,臺北市,臺北市第2選舉區,True,1987-07-01,同名同縣市歷史命中，身分仍待核對；未填入已核實欄,True,吳欣岱,臺北市,2,0760701,女,大學,data/raw/cec_all_offices/107_elcand.csv,34,votedata/votedata/voteData/2022-111年地方公職人員選舉/T...,af38d1e0ca691d9e353fcfb3e154f0cbe1f178d6e796ce...
1,2026|直轄市議員|臺北市第3選舉區|林柏勛,林柏勛,臺北市,臺北市第3選舉區,True,1983-11-15,同名同縣市歷史命中，身分仍待核對；未填入已核實欄,False,林柏勛,臺北市,3,0721115,男,碩士,data/raw/cec_all_offices/107_elcand.csv,43,votedata/votedata/voteData/2022-111年地方公職人員選舉/T...,af38d1e0ca691d9e353fcfb3e154f0cbe1f178d6e796ce...
2,2026|直轄市議員|臺北市第5選舉區|吳怡萱,吳怡萱,臺北市,臺北市第5選舉區,True,1989-08-17,同名同縣市歷史命中，身分仍待核對；未填入已核實欄,False,吳怡萱,臺北市,5,0780817,女,大學,data/raw/cec_all_offices/107_elcand.csv,75,votedata/votedata/voteData/2022-111年地方公職人員選舉/T...,af38d1e0ca691d9e353fcfb3e154f0cbe1f178d6e796ce...
3,2026|直轄市議員|臺北市第6選舉區|陳聖文,陳聖文,臺北市,臺北市第6選舉區,True,1998-05-06,同名同縣市歷史命中，身分仍待核對；未填入已核實欄,False,陳聖文,臺北市,6,0870506,男,碩士,data/raw/cec_all_offices/107_elcand.csv,112,votedata/votedata/voteData/2022-111年地方公職人員選舉/T...,af38d1e0ca691d9e353fcfb3e154f0cbe1f178d6e796ce...
4,2026|直轄市議員|新北市第2選舉區|張昭隆,張昭隆,新北市,新北市第2選舉區,False,1966-10-22,同名同縣市歷史命中，身分仍待核對；未填入已核實欄,False,張昭隆,新北市,8,0551022,男,大學,data/raw/cec_all_offices/107_elcand.csv,318,votedata/votedata/voteData/2022-111年地方公職人員選舉/T...,af38d1e0ca691d9e353fcfb3e154f0cbe1f178d6e796ce...
5,2026|直轄市議員|新北市第4選舉區|董俊良,董俊良,新北市,新北市第4選舉區,True,1970-07-30,同名同縣市歷史命中，身分仍待核對；未填入已核實欄,False,董俊良,新北市,4,0590730,男,高中(職),data/raw/cec_all_offices/107_elcand.csv,276,votedata/votedata/voteData/2022-111年地方公職人員選舉/T...,af38d1e0ca691d9e353fcfb3e154f0cbe1f178d6e796ce...
6,2026|直轄市議員|新北市第4選舉區|陳宛毓,陳宛毓,新北市,新北市第4選舉區,True,1988-04-18,同名同縣市歷史命中，身分仍待核對；未填入已核實欄,True,陳宛毓,新北市,4,0770418,女,大學,data/raw/cec_all_offices/107_elcand.csv,266,votedata/votedata/voteData/2022-111年地方公職人員選舉/T...,af38d1e0ca691d9e353fcfb3e154f0cbe1f178d6e796ce...
7,2026|直轄市議員|新北市第5選舉區|戴瑋姗,戴瑋姗,新北市,新北市第5選舉區,True,1990-01-23,同名同縣市歷史命中，身分仍待核對；未填入已核實欄,False,戴瑋姗,新北市,5,0790123,女,大學,data/raw/cec_all_offices/107_elcand.csv,282,votedata/votedata/voteData/2022-111年地方公職人員選舉/T...,af38d1e0ca691d9e353fcfb3e154f0cbe1f178d6e796ce...
8,2026|直轄市議員|新北市第6選舉區|張志豪,張志豪,新北市,新北市第6選舉區,True,1981-08-24,同名同縣市歷史命中，身分仍待核對；未填入已核實欄,False,張志豪,新北市,6,0700824,男,碩士,data/raw/cec_all_offices/107_elcand.csv,307,votedata/votedata/voteData/2022-111年地方公職人員選舉/T...,af38d1e0ca691d9e353fcfb3e154f0cbe1f178d6e796ce...
9,2026|直轄市議員|新北市第7選舉區|羅文崇,羅文崇,新北市,新北市第7選舉區,True,1964-07-08,同名同縣市歷史命中，身分仍待核對；未填入已核實欄,False,羅文崇,新北市,7,0530708,男,碩士,data/raw/cec_all_offices/107_elcand.csv,312,votedata/votedata/voteData/2022-111年地方公職人員選舉/T...,af38d1e0ca691d9e353fcfb3e154f0cbe1f178d6e796ce...

data/processed/council_identity_review_round7_20261019.csv

,candidate_key,candidate_name,decision,birth_date,sex,official_source_url,official_source_file,official_source_page,history_source_file,history_source_row,identity_source_url,identity_source_file,identity_source_method,identity_anchors,cross_district_note,checked_date
0,2026|直轄市議員|高雄市第1選舉區|林慧欣,林慧欣,supported_2022_person_cells_link,1985-06-11,女,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/06a729e...,1,data/raw/cec_all_offices/107_elcand.csv,115,https://newtalk.tw/news/view/2026-02-10/1019657,data/raw/identity_followup_20261019/web_01.txt,web_tool_extraction_not_original_HTTP,擔任過老師 | 擔任邱議瑩委員的助理,,2026-10-19
1,2026|直轄市議員|高雄市第2選舉區|鄭東元,鄭東元,supported_2022_person_cells_link,1959-04-20,男,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/bd66678...,1,data/raw/cec_all_offices/107_elcand.csv,119,https://hoomedia.com.tw/2026/09/04/165433/,data/raw/identity_followup_20261019/web_02.txt,web_tool_extraction_not_original_HTTP,國立高雄大學經濟管理研究所碩士 | 正修科技大學土木工程學系,,2026-10-19
2,2026|直轄市議員|高雄市第5選舉區|陳若翠,陳若翠,supported_2022_person_cells_link,1969-04-29,女,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/a36fb7c...,1,data/raw/cec_all_offices/107_elcand.csv,182,https://www.300c3.org.tw/uninews_view.php?lang...,data/raw/identity_followup_20261019/b3a33c911c...,http_original_bytes,預計投入2026年高雄市第五選區市議員選舉的前市議員陳若翠,2022第8選區、2026第5選區；以曾任高雄市議員及2026第5選區情境補強，保留跨選區標記,2026-10-19
3,2026|直轄市議員|高雄市第5選舉區|陳惠君,陳惠君,supported_2022_person_cells_link,1968-09-04,女,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/5a9df43...,3,data/raw/cec_all_offices/107_elcand.csv,162,https://more-news.tw/714185/,data/raw/identity_followup_20261019/c1e0df6c4a...,http_original_bytes,曾於四年前獲台灣民眾黨提名投入市議員選舉的陳惠君 | 長期接觸音樂教育及學生培育,,2026-10-19
4,2026|直轄市議員|高雄市第7選舉區|童燕珍,童燕珍,supported_2022_person_cells_link,1953-11-02,女,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/806bb89...,2,data/raw/cec_all_offices/107_elcand.csv,177,https://www.cna.com.tw/news/aloc/202604220132....,data/raw/identity_followup_20261019/web_03.txt,web_tool_extraction_not_original_HTTP,曾任5屆高雄市議員，2022年連任失敗後 | 第7選區三民區,,2026-10-19
5,2026|直轄市議員|高雄市第9選舉區|蘇致榮,蘇致榮,supported_2022_person_cells_link,1977-10-29,男,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/07d3192...,3,data/raw/cec_all_offices/107_elcand.csv,199,https://udn.com/vote2026/story/124652/9652381,data/raw/identity_followup_20261019/005f873a8f...,http_original_bytes,蘇致榮為本屆「落選頭」，父親是前市議員蘇炎城,,2026-10-19
6,2026|直轄市議員|高雄市第9選舉區|徐尚賢,徐尚賢,supported_2022_person_cells_link,1990-09-30,男,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/07d3192...,3,data/raw/cec_all_offices/107_elcand.csv,202,https://udn.com/vote2026/story/124652/9652381,data/raw/identity_followup_20261019/005f873a8f...,http_original_bytes,前「罷捷」領銜人徐尚賢 | 第九（鳳山）選區,,2026-10-19
7,2026|直轄市議員|高雄市第10選舉區|湯茹婷,湯茹婷,supported_2022_person_cells_link,1993-11-19,女,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/a836ab3...,3,data/raw/cec_all_offices/107_elcand.csv,216,https://news111.com.tw/news/47/12852,data/raw/identity_followup_20261019/2284ca924c...,http_original_bytes,國立中山大學中國與亞太區域研究所碩士 | 2022年曾代表時代力量參選高雄市第10選舉區市議員,,2026-10-19
8,2026|直轄市議員|高雄市第11選舉區|洪村銘,洪村銘,supported_2022_person_cells_link,1978-11-22,男,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/b141e9c...,1,data/raw/cec_all_offices/107_elcand.csv,223,https://news111.com.tw/news/48/10939,data/raw/identity_followup_20261019/2e04933edd...,http_original_bytes,洪村銘曾任行政院南部服務中心執行長及民進黨高雄市黨部執行長,,2026-10-19
9,2026|直轄市議員|高雄市第2選舉區|李柏融,李柏融,still_pending_current_identity_corroboration,,,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/bd66678...,1,,,,,requests404_and_tool_open_failed; no false com...,,,2026-10-19

data/processed/party_profile_review_round7_20261019.csv

,candidate_key,candidate_name,electoral_district,source_url,source_file,source_method,education_raw,experience_raw,has_substantive_background,is_placeholder_only,decision,checked_date
0,2026|直轄市議員|高雄市第1選舉區|李振豪,李振豪,高雄市第1選舉區,https://2026.kmtks.org.tw/Council/li-zhen-hao,data/raw/kmtks_web_20261019/01.txt,web_tool_extraction_not_original_HTTP,,,False,True,entry_only_background_placeholder_not_completed,2026-10-19
1,2026|直轄市議員|高雄市第3選舉區|黃韻涵,黃韻涵,高雄市第3選舉區,https://2026.kmtks.org.tw/Council/huang-yun-han,data/raw/kmtks_web_20261019/02.txt,web_tool_extraction_not_original_HTTP,,,False,True,entry_only_background_placeholder_not_completed,2026-10-19
2,2026|直轄市議員|高雄市第5選舉區|陳若翠,陳若翠,高雄市第5選舉區,https://2026.kmtks.org.tw/Council/chen-ruo-cui,data/raw/kmtks_web_20261019/03.txt,web_tool_extraction_not_original_HTTP,,,False,True,entry_only_background_placeholder_not_completed,2026-10-19
3,2026|直轄市議員|高雄市第7選舉區|童燕珍,童燕珍,高雄市第7選舉區,https://2026.kmtks.org.tw/Council/tong-yan-zhen,data/raw/kmtks_web_20261019/04.txt,web_tool_extraction_not_original_HTTP,,,False,True,entry_only_background_placeholder_not_completed,2026-10-19
4,2026|直轄市議員|高雄市第8選舉區|黃裕庭,黃裕庭,高雄市第8選舉區,https://2026.kmtks.org.tw/Council/huang-yu-ting,data/raw/kmtks_web_20261019/05.txt,web_tool_extraction_not_original_HTTP,國立高雄師範大學教育研究所碩士,高市苓雅 區第3、4 屆仁政里里長 | 照顧服務員單一級技術士 | 國民黨高市卓越青年工作總...,True,False,accepted_person_background_source_self_reported,2026-10-19
5,2026|直轄市議員|高雄市第10選舉區|湯茹婷,湯茹婷,高雄市第10選舉區,https://2026.kmtks.org.tw/Council/tang-ju-ting,data/raw/kmtks_web_20261019/06.txt,web_tool_extraction_not_original_HTTP,,高雄市港都前進發展協會 理事長 | 高雄市前鎮民防中隊 副中隊長 | 財團法人高雄市前鎮鎮南...,True,False,accepted_person_background_source_self_reported,2026-10-19
6,2026|直轄市議員|高雄市第12選舉區|宋紹銘,宋紹銘,高雄市第12選舉區,https://2026.kmtks.org.tw/Council/song-shao-ming,data/raw/kmtks_web_20261019/07.txt,web_tool_extraction_not_original_HTTP,1.高雄市私立正修科技大學-休閒運動與管理學系 | 2.台南縣鹽水區南榮工專 | 3.高雄市...,1.115年中國國民黨高雄市黨部原住民工作會-都會區會長 | 2.高雄市政府原住民事務委員會...,True,False,accepted_person_background_source_self_reported,2026-10-19
7,2026|直轄市議員|高雄市第13選舉區|葛姵瑩,葛姵瑩,高雄市第13選舉區,https://2026.kmtks.org.tw/Council/ge-pei-ying,data/raw/kmtks_web_20261019/08.txt,web_tool_extraction_not_original_HTTP,,,False,True,entry_only_background_placeholder_not_completed,2026-10-19
8,2026|直轄市議員|高雄市第15選舉區|陳奕蓁,陳奕蓁,高雄市第15選舉區,https://2026.kmtks.org.tw/Council/chen-yi-zhen,data/raw/kmtks_web_20261019/09.txt,web_tool_extraction_not_original_HTTP,,,False,True,entry_only_background_placeholder_not_completed,2026-10-19

data/processed/candidate_evidence_round7_20261019.csv

,candidate_key,candidate_name,field,value,source_url,source_file,source_year,evidence_status,checked_date
0,2026|直轄市議員|高雄市第1選舉區|林慧欣,林慧欣,birth_date,1985-06-11,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/06a729e...,2022,2022官方公報個人欄位；2026同縣市／當屆參選情境與2022公報過往職務或學校相互支持；...,2026-10-19
1,2026|直轄市議員|高雄市第1選舉區|林慧欣,林慧欣,sex,女,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/06a729e...,2022,2022官方公報個人欄位；2026同縣市／當屆參選情境與2022公報過往職務或學校相互支持；...,2026-10-19
2,2026|直轄市議員|高雄市第1選舉區|林慧欣,林慧欣,education,國立高雄師範大學客家文化\n研究所,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/06a729e...,2022,2022官方公報個人欄位；2026同縣市／當屆參選情境與2022公報過往職務或學校相互支持；...,2026-10-19
3,2026|直轄市議員|高雄市第1選舉區|林慧欣,林慧欣,experience,高雄市政府陳其邁市長秘書\n高雄市國小教師客語教師\n立法委員邱議瑩助理\n客家委員會客語薪...,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/06a729e...,2022,2022官方公報個人欄位；2026同縣市／當屆參選情境與2022公報過往職務或學校相互支持；...,2026-10-19
4,2026|直轄市議員|高雄市第1選舉區|林慧欣,林慧欣,identity_link,擔任過老師 | 擔任邱議瑩委員的助理,https://newtalk.tw/news/view/2026-02-10/1019657,data/raw/identity_followup_20261019/web_01.txt,2026,2026同縣市／當屆參選情境與2022公報過往職務或學校相互支持；非僅以姓名連結；；當屆佐證...,2026-10-19
5,2026|直轄市議員|高雄市第1選舉區|林慧欣,林慧欣,first_time_any_office,0,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/06a729e...,2022,2022議員參選及身分支持，不推定2026仍在任,2026-10-19
6,2026|直轄市議員|高雄市第1選舉區|林慧欣,林慧欣,first_time_this_office,0,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/06a729e...,2022,2022議員參選及身分支持，不推定2026仍在任,2026-10-19
7,2026|直轄市議員|高雄市第2選舉區|鄭東元,鄭東元,birth_date,1959-04-20,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/bd66678...,2022,2022官方公報個人欄位；2026同縣市／當屆參選情境與2022公報過往職務或學校相互支持；...,2026-10-19
8,2026|直轄市議員|高雄市第2選舉區|鄭東元,鄭東元,sex,男,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/bd66678...,2022,2022官方公報個人欄位；2026同縣市／當屆參選情境與2022公報過往職務或學校相互支持；...,2026-10-19
9,2026|直轄市議員|高雄市第2選舉區|鄭東元,鄭東元,education,國立高雄大學經濟管理碩士\n正修科技大學專科部土木工\n程畢業,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/bd66678...,2022,2022官方公報個人欄位；2026同縣市／當屆參選情境與2022公報過往職務或學校相互支持；...,2026-10-19

### Summary Stats

In [3]:
for p,d in D.items():
 print(p);display(pd.DataFrame({'type':d.dtypes.astype(str),'empty':d.eq('').sum()}))
print('New linked names:',['林慧欣', '鄭東元', '陳若翠', '陳惠君', '童燕珍', '蘇致榮', '徐尚賢', '湯茹婷', '洪村銘'])
print('2022 DOB/sex=701; official DOB union=705; explicit sex including self-report=706; profiles missing=730; nonfirst any/council=712/704; pending identity=153')

data/processed/snapshots/pre_cross_office_round8_20261019/candidate_master_current.csv

                                 type  empty
candidate_key                     str      0
candidate_name                    str      0
office_type                       str      0
county_city                       str      0
electoral_district                str     81
party_registration_raw            str      0
registration_source               str      0
registration_source_file          str      0
registration_source_page          str      0
qualification_inherited           str      0
qualification_audit               str      0
sample_inclusion                  str      0
directory_lead_count              str      0
updated_date                      str      0
sex_status                        str      0
birth_date_status                 str      0
education_status                  str      0
incumbency_status                 str      0
first_time_this_office_status     str      0
first_time_any_office_status      str      0
profile_status                    str      0
website_status                    str      0
Facebook_status                   str      0
Instagram_status                  str      0
Threads_status                    str      0
posts_Facebook_status             str      0
posts_Instagram_status            str      0
posts_Threads_status              str      0
followers_status                  str      0
policy_text_status                str      0
visual_status                     str      0
political_family_status           str      0
administrative_experience_status  str      0
qualification_status              str      0

data/processed/snapshots/pre_cross_office_round8_20261019/candidate_fields_current.csv

               type  empty
candidate_key   str      0
candidate_name  str      0
office_type     str      0
county_city     str      0
field           str      0
status          str      0
existing_value  str  25217
evidence        str  24234
note            str  23936
next_source     str      0
updated_date    str      0

data/processed/snapshots/pre_cross_office_round8_20261019/council_background_20261019.csv

                                      type  empty
candidate_key                          str      0
candidate_name                         str      0
county_city                            str      0
office_type                            str      0
electoral_district                     str      0
party_registration_raw                 str      0
birth_date_supported_history           str    801
birth_year_supported_history           str    801
sex_supported_history                  str    801
birth_sex_evidence_status              str      0
history_source_file                    str    801
history_source_row                     str    801
history_identity_review                str    799
history_match_count                    str      0
education_raw                          str    813
experience_raw                         str    813
background_source_url                  str    722
moi_profile_url                        str    810
campaign_profile_url                   str   1474
education_2022_declared                str    810
education_completion_status            str      0
first_time_this_office_supported       str    798
first_time_any_office_supported        str    790
incumbency_2026                        str   1502
incumbency_status                      str      0
updated_date                           str      0
additional_profile_url                 str   1447
additional_profile_status              str   1447
birth_date_self_declared               str   1501
birth_date_self_declared_source        str   1501
sex_additional_source_value            str   1497
sex_additional_source_url              str   1497
sex_additional_source_year             str   1497
birth_date_bulletin_candidate          str   1489
birth_year_bulletin_candidate          str   1489
sex_bulletin_candidate                 str   1489
education_bulletin_raw                 str   1489
experience_bulletin_raw                str   1489
bulletin_source_url                    str   1489
bulletin_source_file                   str   1489
bulletin_source_page                   str   1489
bulletin_identity_status               str   1489
birth_date_additional_official         str   1498
birth_date_additional_source_url       str   1498
birth_date_additional_evidence_status  str   1498
round6_profile_urls                    str   1484
birth_date_additional_source_year      str   1498
additional_historical_education_cec    str   1499
round7_identity_url                    str   1493
party_page_lead_url                    str   1493

data/processed/snapshots/pre_cross_office_round8_20261019/council_history_pending_identity_current.csv

                             type  empty
candidate_key                 str      0
candidate_name                str      0
county_city                   str      0
electoral_district            str      0
same_district_number          str      0
birth_date_history_candidate  str      0
identity_status               str      0
profile_evidence_present      str      0
history_name                  str      0
history_county                str      0
history_district              str      0
history_birth_roc             str      0
history_sex                   str      0
history_education             str      0
history_file                  str      0
history_row                   str      0
history_archive_member        str      0
source_sha256                 str      0

data/processed/council_identity_review_round7_20261019.csv

                       type  empty
candidate_key           str      0
candidate_name          str      0
decision                str      0
birth_date              str      2
sex                     str      2
official_source_url     str      0
official_source_file    str      0
official_source_page    str      0
history_source_file     str      2
history_source_row      str      2
identity_source_url     str      2
identity_source_file    str      2
identity_source_method  str      0
identity_anchors        str      2
cross_district_note     str     10
checked_date            str      0

data/processed/party_profile_review_round7_20261019.csv

                           type  empty
candidate_key               str      0
candidate_name              str      0
electoral_district          str      0
source_url                  str      0
source_file                 str      0
source_method               str      0
education_raw               str      7
experience_raw              str      6
has_substantive_background  str      0
is_placeholder_only         str      0
decision                    str      0
checked_date                str      0

data/processed/candidate_evidence_round7_20261019.csv

                type  empty
candidate_key    str      0
candidate_name   str      0
field            str      0
value            str      0
source_url       str      0
source_file      str      0
source_year      str      0
evidence_status  str      0
checked_date     str      0

New linked names: ['林慧欣', '鄭東元', '陳若翠', '陳惠君', '童燕珍', '蘇致榮', '徐尚賢', '湯茹婷', '洪村銘']
2022 DOB/sex=701; official DOB union=705; explicit sex including self-report=706; profiles missing=730; nonfirst any/council=712/704; pending identity=153

### Assertions

In [4]:
c=D['data/processed/snapshots/pre_cross_office_round8_20261019/council_background_20261019.csv'];before=pd.read_csv(ROOT/'data/processed/snapshots/pre_identity_round7_20261019/council_background_20261019.csv',dtype=str,keep_default_na=False)
assert c.birth_date_supported_history.ne('').sum()==701 and c.sex_supported_history.ne('').sum()==701
assert (c.moi_profile_url.eq('')&c.campaign_profile_url.eq('')&c.additional_profile_url.eq('')).sum()==730
assert c[['candidate_key','party_registration_raw','incumbency_2026']].equals(before[['candidate_key','party_registration_raw','incumbency_2026']])
for name in ['李柏融','柳淑芳']: assert c.loc[c.candidate_name.eq(name),'birth_date_supported_history'].eq('').all()
print('Schema/key/hash, counts, unchanged registration/incumbency and unresolved people checks passed.')

Schema/key/hash, counts, unchanged registration/incumbency and unresolved people checks passed.