# Data Description
- Author: RUEI-HSIANG, CHANG (B12303030)，Codex 協助
- Date first created: 20261019
- Background: 邱建富2014官方公報第1頁號次1生日欄核對，並與既有CEC 2009/2014參選紀錄交叉比對；補入1960-11-29。
- Unit of observation: supplement＝1名候選人的逐格查核；enriched＝81位縣市長候選人；master＝1,583人；fields＝31,660個候選人欄位。
- Sample period: 2026研究名冊，生日出處2014年公報，2026-10-19查核。
- Known issues: 生日為官方歷史候選人申報，非戶籍認證。仍缺25人完整生日、魏造文性別仍未知；本輪沒有補其他人的日期。邱建富2014參選彰化市長屬鄉鎮市長，不當作曾參選縣市首長。
- Definition for each variable:
  - supplement的candidate_*識別；source_*、page、source_locator為出處與定位；birth_date_raw、birth_date、sex_raw為原文與西元日期；verification_method、historical_match_files、checked_date、limitation為查核與限制。
  - enriched沿用上游81人資料欄位，本輪只改邱建富birth_date_verified、age_2026_minus_birth_year、birth_date_source_url、birth_date_evidence_status；原生日及媒體欄位均保留。
  - master／fields欄位定義沿用background_round3_20261019_documentation.ipynb，本輪只更新邱建富birth_date狀態及來源；其餘欄位保持上游。
- Data path / Role / SHA-256:
  - data/processed/mayor_birthdate_verified_supplement_20261019.csv / source supplement or background inventory / 284471d062e9bc9474243697d1ec8e0ae0d115884626168f4b97cc95747a5472 (1列)
  - data/processed/candidates_2026_enriched_round3_20261019.csv / source supplement or background inventory / e28951160f82504eb5b5d61777995ceb78a9f94bae89a724e4a9238e4c08192d (81列)
  - data/processed/candidate_master_reviewed_round4_20261019.csv / source supplement or background inventory / 8af6660bfdee31ab3f2f0189218fbc607b3d779f0c2d349575fe1d3909daa0fd (1583列)
  - data/processed/candidate_fields_reviewed_round4_20261019.csv / source supplement or background inventory / eb36a93dbe7e38e2a7dbad48741b1f7f37eea114354ca18d021951acfb30fb74 (31660列)
- Source data: data/raw/birthday_recheck_20261019/visual_review.json、qiu_2014_bulletin.pdf；candidate_all_office_history.csv、原candidates_2026_enriched.csv、round3主表與欄位表。固定輸入hash見整理程式PINS。
- Processing code: data/code/verify_mayor_birthdate_20261019.ipynb。
- Verification status: clean kernel 執行，核對hash、列數、鍵、55→56已佐證生日及26→25缺口；處理程式另比對其他人與未動欄位完全一致。
- Downstream analysis input: candidates_2026_enriched_round3_20261019.csv可提供56人已佐證生日；缺失與其他未核實背景須依研究規則處理，不以零補值。

In [1]:
from pathlib import Path
import pandas as pd,json,hashlib
ROOT=next(p for p in [Path.cwd(),*Path.cwd().parents] if (p/'AGENTS.md').exists() and (p/'templates').is_dir())
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()

## Change for Your Own Data

In [2]:
FRAMES={}
assert sha(ROOT/'data/processed/mayor_birthdate_verified_supplement_20261019.csv')=='284471d062e9bc9474243697d1ec8e0ae0d115884626168f4b97cc95747a5472'
FRAMES['data/processed/mayor_birthdate_verified_supplement_20261019.csv']=pd.read_csv(ROOT/'data/processed/mayor_birthdate_verified_supplement_20261019.csv',dtype=str).fillna('')
assert len(FRAMES['data/processed/mayor_birthdate_verified_supplement_20261019.csv'])==1
assert sha(ROOT/'data/processed/candidates_2026_enriched_round3_20261019.csv')=='e28951160f82504eb5b5d61777995ceb78a9f94bae89a724e4a9238e4c08192d'
FRAMES['data/processed/candidates_2026_enriched_round3_20261019.csv']=pd.read_csv(ROOT/'data/processed/candidates_2026_enriched_round3_20261019.csv',dtype=str).fillna('')
assert len(FRAMES['data/processed/candidates_2026_enriched_round3_20261019.csv'])==81
assert sha(ROOT/'data/processed/candidate_master_reviewed_round4_20261019.csv')=='8af6660bfdee31ab3f2f0189218fbc607b3d779f0c2d349575fe1d3909daa0fd'
FRAMES['data/processed/candidate_master_reviewed_round4_20261019.csv']=pd.read_csv(ROOT/'data/processed/candidate_master_reviewed_round4_20261019.csv',dtype=str).fillna('')
assert len(FRAMES['data/processed/candidate_master_reviewed_round4_20261019.csv'])==1583
assert sha(ROOT/'data/processed/candidate_fields_reviewed_round4_20261019.csv')=='eb36a93dbe7e38e2a7dbad48741b1f7f37eea114354ca18d021951acfb30fb74'
FRAMES['data/processed/candidate_fields_reviewed_round4_20261019.csv']=pd.read_csv(ROOT/'data/processed/candidate_fields_reviewed_round4_20261019.csv',dtype=str).fillna('')
assert len(FRAMES['data/processed/candidate_fields_reviewed_round4_20261019.csv'])==31660

## Summary

In [3]:
for p,d in FRAMES.items():print(p,len(d))

data/processed/mayor_birthdate_verified_supplement_20261019.csv 1
data/processed/candidates_2026_enriched_round3_20261019.csv 81
data/processed/candidate_master_reviewed_round4_20261019.csv 1583
data/processed/candidate_fields_reviewed_round4_20261019.csv 31660

### Sample

In [4]:
for p,d in FRAMES.items():
 print(p);display(d.head(10))

data/processed/mayor_birthdate_verified_supplement_20261019.csv

,candidate_key,candidate_name,source_url,source_file,source_sha256,source_year,page,source_locator,birth_date_raw,birth_date,sex_raw,verification_method,historical_match_files,checked_date,limitation
0,2026-C2-031,邱建富,https://web.cec.gov.tw/api/file/1f07fea7-6589-...,data/raw/birthday_recheck_20261019/qiu_2014_bu...,4abfc312e471eb7522299da1cabe8399d4aa76609bea61...,2014,1,彰化市第17屆市長選舉；號次1；姓名及出生年月日欄,49年11月29日,1960-11-29,男,PDF page 1 rendered and birth-date cell visual...,data/raw/cec_all_offices/052_elcand.csv:136 | ...,2026-10-19,"historical candidate-declared record, not hous..."

data/processed/candidates_2026_enriched_round3_20261019.csv

,candidate_key,county_city,registration_date_roc,candidate_name,party_recommendation_original,source_note,office_type,source_file,source_page,source_url,...,prior_mayor_evidence_file,first_time_any_evidence_status,first_time_mayor_evidence_status,no_prior_mayor_match_in_available_archive,identity_conflict_notes,background_collection_status,sex_source_tier,sex_evidence_status,sex_directory_supplement,sex_directory_source_url
0,2026-C1-001,臺北市,115/08/31,郭璽,台灣麻將最大黨,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,,prior_CEC_record_name_and_birth_date_corroborated,,1,,partial_with_sources,historical_CEC,dob_corroborated_by_media,,
1,2026-C1-002,臺北市,115/09/02,沈伯洋,民主進步黨,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,,positive_prior_elected_office_evidence,,1,,partial_with_sources,official_profile,source_observation,,
2,2026-C1-003,臺北市,115/09/02,蕭文乾,臺灣SoR無法黨,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,,positive_prior_elected_office_evidence,,1,,partial_with_sources,official_bulletin,visually_checked_pdf_cell,,
3,2026-C1-004,臺北市,115/09/03,唐新民,三勢團結促進聯盟,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,data/raw/cec_all_offices/100_elcand.csv,prior_CEC_record_name_and_birth_date_corroborated,prior_CEC_mayoral_record_name_and_birth_date_c...,0,,partial_with_sources,historical_CEC,dob_corroborated_by_media,,
4,2026-C1-005,臺北市,115/09/04,蔣萬安,中國國民黨,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,data/raw/cec_all_offices/100_elcand.csv,prior_CEC_record_name_and_birth_date_corroborated,prior_CEC_mayoral_record_name_and_birth_date_c...,0,,partial_with_sources,historical_CEC,dob_corroborated_by_media,,
5,2026-C1-006,臺北市,115/09/04,林志成,無,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,,prior_CEC_record_name_and_birth_date_corroborated,,1,8 historical namesake/date conflicts excluded;...,partial_with_sources,historical_CEC,dob_corroborated_by_media,,
6,2026-C1-007,新北市,115/09/02,蘇巧慧,民主進步黨,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,,positive_prior_elected_office_evidence,,1,,partial_with_sources,official_profile,source_observation,,
7,2026-C1-008,新北市,115/09/04,李四川,中國國民黨,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,,,,1,2 historical namesake/date conflicts excluded;...,partial_with_sources,official_government_sex,explicit_sex_role_identity_matched,,
8,2026-C1-009,新北市,115/09/04,蘇輝湟,無,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,,prior_CEC_record_name_and_birth_date_corroborated,,1,,partial_with_sources,historical_CEC,dob_corroborated_by_media,,
9,2026-C1-010,桃園市,115/09/01,張善政,中國國民黨,,C1,data/raw/2026_metropolitan_registration.pdf,1,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,...,data/raw/cec_all_offices/100_elcand.csv,prior_CEC_record_name_and_birth_date_corroborated,prior_CEC_mayoral_record_name_and_birth_date_c...,0,,partial_with_sources,historical_CEC,dob_corroborated_by_media,,

data/processed/candidate_master_reviewed_round4_20261019.csv

,candidate_key,candidate_name,office_type,county_city,electoral_district,party_registration_raw,registration_source,registration_source_file,registration_source_page,qualification_inherited,...,Threads_status,posts_Facebook_status,posts_Instagram_status,posts_Threads_status,followers_status,policy_text_status,visual_status,political_family_status,administrative_experience_status,qualification_status
0,2026-C1-001,郭璽,直轄市長,臺北市,,台灣麻將最大黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
1,2026-C1-002,沈伯洋,直轄市長,臺北市,,民主進步黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,部分原文已保存，尚未政策編碼,未查找,未查找,未查找,官方內文待重新核對
2,2026-C1-003,蕭文乾,直轄市長,臺北市,,臺灣SoR無法黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
3,2026-C1-004,唐新民,直轄市長,臺北市,,三勢團結促進聯盟,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
4,2026-C1-005,蔣萬安,直轄市長,臺北市,,中國國民黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
5,2026-C1-006,林志成,直轄市長,臺北市,,無,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
6,2026-C1-007,蘇巧慧,直轄市長,新北市,,民主進步黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,部分原文已保存，尚未政策編碼,未查找,未查找,未查找,官方內文待重新核對
7,2026-C1-008,李四川,直轄市長,新北市,,中國國民黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
8,2026-C1-009,蘇輝湟,直轄市長,新北市,,無,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
9,2026-C1-010,張善政,直轄市長,桃園市,,中國國民黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對

data/processed/candidate_fields_reviewed_round4_20261019.csv

,candidate_key,candidate_name,office_type,county_city,field,status,existing_value,evidence,note,next_source,updated_date
0,2026-C1-001,郭璽,直轄市長,臺北市,sex,已有資料，待來源複核,男,https://db.cec.gov.tw/,dob_corroborated_by_media,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
1,2026-C1-001,郭璽,直轄市長,臺北市,birth_date,已有資料，待來源複核,1958-08-31,https://db.cec.gov.tw/,CEC_name_and_birth_date_corroborated_by_CNA,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
2,2026-C1-001,郭璽,直轄市長,臺北市,education,已有資料，待來源複核,大學,,歷史公報或媒體補充，非2026學歷認證,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
3,2026-C1-001,郭璽,直轄市長,臺北市,incumbency,既有搜尋後仍缺，待補查,,,,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
4,2026-C1-001,郭璽,直轄市長,臺北市,first_time_this_office,既有搜尋後仍缺，待補查,,,0=有過參選證據；空白不表示首次。此處沿用既有表。,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
5,2026-C1-001,郭璽,直轄市長,臺北市,first_time_any_office,已有資料，待來源複核,0,https://db.cec.gov.tw/,0=有過參選證據；空白不表示首次。此處沿用既有表。,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
6,2026-C1-001,郭璽,直轄市長,臺北市,profile,既有搜尋後仍缺，待補查,,,,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
7,2026-C1-001,郭璽,直轄市長,臺北市,website,既有搜尋後仍缺，待補查,,,,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
8,2026-C1-001,郭璽,直轄市長,臺北市,Facebook,尚未驗證，不代表無帳號,,,,官方人物頁／競選網站交叉連結,2026-10-19
9,2026-C1-001,郭璽,直轄市長,臺北市,Instagram,尚未驗證，不代表無帳號,,,,官方人物頁／競選網站交叉連結,2026-10-19

### Summary Stats

In [5]:
s,e,m,f=FRAMES.values();print({'有完整生日':int(e.birth_date_verified.ne('').sum()),'仍缺':int(e.birth_date_verified.eq('').sum())});display(e[e.candidate_name.eq('邱建富')][['candidate_name','birth_date_verified','birth_date_source_url','birth_date_evidence_status']])

{'有完整生日': 56, '仍缺': 25}

,candidate_name,birth_date_verified,birth_date_source_url,birth_date_evidence_status
30,邱建富,1960-11-29,https://web.cec.gov.tw/api/file/1f07fea7-6589-...,2014_official_bulletin_visually_checked_and_20...

### Assertions

In [6]:
assert e.candidate_key.is_unique and len(e)==81
assert e.birth_date_verified.ne('').sum()==56
assert e[e.candidate_name.eq('邱建富')].iloc[0].birth_date_verified=='1960-11-29'
assert m.candidate_key.is_unique and len(m)==1583
assert len(f)==31660 and not f.duplicated(['candidate_key','field']).any()
print('PASS：保存檔hash、列數、鍵、完整生日數與邱建富日期。')

PASS：保存檔hash、列數、鍵、完整生日數與邱建富日期。