# Data Description
- Author: RUEI-HSIANG, CHANG (B12303030)，Codex 協助
- Date first created: 20261019
- Background: 依學生要求先補「可點進去的窗口」，貼文窗口與蒐集暫緩。
- Unit of observation: evidence 為候選人×平台×網址×來源；worklist 為候選人×平台；unmatched 為來源候選人卡。
- Sample period: 2026-10-19 來源整理快照；非貼文觀察窗口。
- Known issues: 來源查找不均，不能據此比較黨派社群使用率。找到來源連結不代表已下載貼文，也未全面證明目標頁仍活躍。數字 Facebook 網址與名稱網址未確認等同前均保留。舊表未覆寫，請使用本日新工作單查看這批連結。
- Definition for each variable:

- candidate_key、candidate_name、county_city、office_type：研究名冊識別與姓名、縣市、公職。
- platform：Facebook／Instagram／Threads；account_url／official_urls：個人入口，後者以 | 分隔多個保留網址，並非全部獨立帳號。
- source_url、source_file、source_locator／discovered_on：發現入口的 URL、原始檔、候選人欄位或區塊定位。
- evidence_status：party_candidate_object_link（政黨候選人物件）、candidate_website_link（本人競選網站）、line_official_account_self_link（LINE 官方帳號自列）、campaign_directory_candidate_link（競選聯盟人物頁，仍待獨立核對），或 inherited_ 前綴（舊表原狀態）。
- target_content_status：未核對目標頁內容；checked_date／updated_date：本次來源整理日期。
- account_status：有來源連結、內容待核對，或尚未找到而非不存在。
- posts_status：尚未蒐集而非零；window_count、followers_start、followers_end：留空的後續欄位。
- unmatched 表 name、city、source、reason：來源人物、縣市、網址及沒有唯一研究名冊對應之理由，不代表人物不存在或不參選。

- Data path / Role / SHA-256:
  - data/processed/candidate_social_account_evidence_20261019.csv / collection index / b15e1bf88876de049533f381771920c3c560e18eef5c53e04fb8142cbedc5ff9 (162 列)
  - data/processed/meta_candidate_account_worklist_20261019.csv / collection index / b3432a639e2179f640f68681dc54eb2889fcf743540aef5b71ec4dd1593a0a49 (4749 列)
  - data/processed/social_directory_unmatched_20261019.csv / collection index / 322af147e7847b92ad7cf9a49929adcae5d86f197cfe69c5be8a655a1b15b786 (6 列)
- Source data: data/raw/round3_20261019/capture_manifest.json；data/processed/candidate_master_reviewed_20261019.csv；data/processed/candidate_campaign_sources.csv。
- Processing code: data/code/prepare_social_accounts_20261019.ipynb
- Verification status: 下列 hash、樣本、摘要與 assertions 由保存檔實際執行。
- Downstream analysis input: 本批僅為入口索引，不具備貼文數或策略分析值。

In [1]:
from pathlib import Path
import pandas as pd,json,hashlib
ROOT=next(p for p in [Path.cwd(),*Path.cwd().parents] if (p/'AGENTS.md').exists() and (p/'templates').is_dir())
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()

## Change for Your Own Data

In [2]:
FRAMES={}
assert sha(ROOT/'data/processed/candidate_social_account_evidence_20261019.csv')=='b15e1bf88876de049533f381771920c3c560e18eef5c53e04fb8142cbedc5ff9'
FRAMES['data/processed/candidate_social_account_evidence_20261019.csv']=pd.read_csv(ROOT/'data/processed/candidate_social_account_evidence_20261019.csv',dtype=str).fillna('')
assert len(FRAMES['data/processed/candidate_social_account_evidence_20261019.csv'])==162
assert sha(ROOT/'data/processed/meta_candidate_account_worklist_20261019.csv')=='b3432a639e2179f640f68681dc54eb2889fcf743540aef5b71ec4dd1593a0a49'
FRAMES['data/processed/meta_candidate_account_worklist_20261019.csv']=pd.read_csv(ROOT/'data/processed/meta_candidate_account_worklist_20261019.csv',dtype=str).fillna('')
assert len(FRAMES['data/processed/meta_candidate_account_worklist_20261019.csv'])==4749
assert sha(ROOT/'data/processed/social_directory_unmatched_20261019.csv')=='322af147e7847b92ad7cf9a49929adcae5d86f197cfe69c5be8a655a1b15b786'
FRAMES['data/processed/social_directory_unmatched_20261019.csv']=pd.read_csv(ROOT/'data/processed/social_directory_unmatched_20261019.csv',dtype=str).fillna('')
assert len(FRAMES['data/processed/social_directory_unmatched_20261019.csv'])==6

## Summary

In [3]:
for path,d in FRAMES.items():print(path,len(d),d.shape[1])
e,w,u=FRAMES.values()
print('有入口候選人',e.candidate_key.nunique(),'候選人×平台',len(e[['candidate_key','platform']].drop_duplicates()))

data/processed/candidate_social_account_evidence_20261019.csv 162 12
data/processed/meta_candidate_account_worklist_20261019.csv 4749 13
data/processed/social_directory_unmatched_20261019.csv 6 4
有入口候選人 50 候選人×平台 132

### Sample

In [4]:
for path,d in FRAMES.items():
 print(path);display(d.head(10))

data/processed/candidate_social_account_evidence_20261019.csv

,candidate_key,candidate_name,county_city,office_type,platform,account_url,source_url,source_file,source_locator,evidence_status,target_content_status,checked_date
0,2026-C2-033,温世政,南投縣,縣（市）長,Facebook,https://www.facebook.com/wEnShihheng,https://teamtaiwan.dpp.org.tw/asset/types/elec...,data/raw/round3_20261019/cab91a155008312e422c....,mayor_data name=温世政 field=fb,party_candidate_object_link,not_verified_not_posts_captured,2026-10-19
1,2026-C2-033,温世政,南投縣,縣（市）長,Instagram,https://www.instagram.com/wen_shih_cheng,https://teamtaiwan.dpp.org.tw/asset/types/elec...,data/raw/round3_20261019/cab91a155008312e422c....,mayor_data name=温世政 field=ig,party_candidate_object_link,not_verified_not_posts_captured,2026-10-19
2,2026-C2-033,温世政,南投縣,縣（市）長,Threads,https://www.threads.com/@wen_shih_cheng,https://teamtaiwan.dpp.org.tw/asset/types/elec...,data/raw/round3_20261019/cab91a155008312e422c....,mayor_data name=温世政 field=threads,party_candidate_object_link,not_verified_not_posts_captured,2026-10-19
3,2026|縣市議員|嘉義市第2選舉區|林詩涵,林詩涵,嘉義市,縣（市）議員,Facebook,https://www.facebook.com/shihhanlin.chiayi,https://www.taiwangogo.tw/lin-shih-han/,data/raw/round3_20261019/f94d16aea58833d3e1d3....,.cv-social; candidate card 林詩涵; 嘉義市,campaign_directory_candidate_link,not_verified_not_posts_captured,2026-10-19
4,2026|縣市議員|嘉義市第2選舉區|林詩涵,林詩涵,嘉義市,縣（市）議員,Instagram,https://www.instagram.com/flip_chiayi,https://www.taiwangogo.tw/lin-shih-han/,data/raw/round3_20261019/f94d16aea58833d3e1d3....,.cv-social; candidate card 林詩涵; 嘉義市,campaign_directory_candidate_link,not_verified_not_posts_captured,2026-10-19
5,2026-C2-080,王美惠,嘉義市,縣（市）長,Facebook,https://www.facebook.com/ahueimoto,https://teamtaiwan.dpp.org.tw/asset/types/elec...,data/raw/round3_20261019/cab91a155008312e422c....,mayor_data name=王美惠 field=fb,party_candidate_object_link,not_verified_not_posts_captured,2026-10-19
6,2026-C2-080,王美惠,嘉義市,縣（市）長,Instagram,https://www.instagram.com/ahueimoto,https://teamtaiwan.dpp.org.tw/asset/types/elec...,data/raw/round3_20261019/cab91a155008312e422c....,mayor_data name=王美惠 field=ig,party_candidate_object_link,not_verified_not_posts_captured,2026-10-19
7,2026-C2-080,王美惠,嘉義市,縣（市）長,Threads,https://www.threads.com/@ahueimoto,https://teamtaiwan.dpp.org.tw/asset/types/elec...,data/raw/round3_20261019/cab91a155008312e422c....,mayor_data name=王美惠 field=threads,party_candidate_object_link,not_verified_not_posts_captured,2026-10-19
8,2026|縣市議員|嘉義市第1選舉區|陳玥妗,陳玥妗,嘉義市,縣（市）議員,Facebook,https://www.facebook.com/OBS.YC,https://www.taiwangogo.tw/chen-yueh-chin/,data/raw/round3_20261019/cc1e275307b6709d2d8b....,.cv-social; candidate card 陳玥妗; 嘉義市,campaign_directory_candidate_link,not_verified_not_posts_captured,2026-10-19
9,2026|縣市議員|嘉義市第1選舉區|陳玥妗,陳玥妗,嘉義市,縣（市）議員,Instagram,https://www.instagram.com/obs.yc,https://www.taiwangogo.tw/chen-yueh-chin/,data/raw/round3_20261019/cc1e275307b6709d2d8b....,.cv-social; candidate card 陳玥妗; 嘉義市,campaign_directory_candidate_link,not_verified_not_posts_captured,2026-10-19

data/processed/meta_candidate_account_worklist_20261019.csv

,candidate_key,candidate_name,county_city,office_type,platform,official_urls,discovered_on,account_status,posts_status,window_count,followers_start,followers_end,updated_date
0,2026-C1-001,郭璽,臺北市,直轄市長,Facebook,,,not_yet_found_not_absent,not_collected_not_zero,,,,2026-10-19
1,2026-C1-001,郭璽,臺北市,直轄市長,Instagram,,,not_yet_found_not_absent,not_collected_not_zero,,,,2026-10-19
2,2026-C1-001,郭璽,臺北市,直轄市長,Threads,,,not_yet_found_not_absent,not_collected_not_zero,,,,2026-10-19
3,2026-C1-002,沈伯洋,臺北市,直轄市長,Facebook,https://www.facebook.com/1087764201093899 | ht...,https://puma.taipei/ | https://www.pumashen.or...,source_link_found_target_content_pending,not_collected_not_zero,,,,2026-10-19
4,2026-C1-002,沈伯洋,臺北市,直轄市長,Instagram,https://www.instagram.com/pumashen,https://teamtaiwan.dpp.org.tw/asset/types/elec...,source_link_found_target_content_pending,not_collected_not_zero,,,,2026-10-19
5,2026-C1-002,沈伯洋,臺北市,直轄市長,Threads,https://www.threads.com/@pumashen,https://teamtaiwan.dpp.org.tw/asset/types/elec...,source_link_found_target_content_pending,not_collected_not_zero,,,,2026-10-19
6,2026-C1-003,蕭文乾,臺北市,直轄市長,Facebook,,,not_yet_found_not_absent,not_collected_not_zero,,,,2026-10-19
7,2026-C1-003,蕭文乾,臺北市,直轄市長,Instagram,,,not_yet_found_not_absent,not_collected_not_zero,,,,2026-10-19
8,2026-C1-003,蕭文乾,臺北市,直轄市長,Threads,,,not_yet_found_not_absent,not_collected_not_zero,,,,2026-10-19
9,2026-C1-004,唐新民,臺北市,直轄市長,Facebook,,,not_yet_found_not_absent,not_collected_not_zero,,,,2026-10-19

data/processed/social_directory_unmatched_20261019.csv

,name,city,source,reason
0,洪瑞瑾,新竹縣,https://www.taiwangogo.tw/hung-jui-chin/,no_unique_in_scope_registration
1,許育綸,新竹縣,https://www.taiwangogo.tw/hsu-yu-lun/,no_unique_in_scope_registration
2,林旭良,新竹縣,https://www.taiwangogo.tw/lin-hsu-liang/,no_unique_in_scope_registration
3,彭致豪,新竹縣,https://www.taiwangogo.tw/peng-chih-hao/,no_unique_in_scope_registration
4,陳昀志,彰化縣,https://www.taiwangogo.tw/chen-yun-chih/,no_unique_in_scope_registration
5,游子昂,屏東縣,https://www.taiwangogo.tw/yu-tzu-ang/,no_unique_in_scope_registration

### Summary Stats

In [5]:
display(e[['candidate_key','platform']].drop_duplicates().platform.value_counts().to_frame('候選人數'));display(w.account_status.value_counts().to_frame('列數'));display(u)

           候選人數
platform
Facebook     50
Instagram    44
Threads      38

                                            列數
account_status
not_yet_found_not_absent                  4617
source_link_found_target_content_pending   132

,name,city,source,reason
0,洪瑞瑾,新竹縣,https://www.taiwangogo.tw/hung-jui-chin/,no_unique_in_scope_registration
1,許育綸,新竹縣,https://www.taiwangogo.tw/hsu-yu-lun/,no_unique_in_scope_registration
2,林旭良,新竹縣,https://www.taiwangogo.tw/lin-hsu-liang/,no_unique_in_scope_registration
3,彭致豪,新竹縣,https://www.taiwangogo.tw/peng-chih-hao/,no_unique_in_scope_registration
4,陳昀志,彰化縣,https://www.taiwangogo.tw/chen-yun-chih/,no_unique_in_scope_registration
5,游子昂,屏東縣,https://www.taiwangogo.tw/yu-tzu-ang/,no_unique_in_scope_registration

### Assertions

In [6]:
e,w,u=FRAMES.values()
assert not e.duplicated(['candidate_key','platform','account_url','source_url']).any()
assert not w.duplicated(['candidate_key','platform']).any() and len(w)==1583*3
assert w.groupby('candidate_key').size().eq(3).all()
assert e.platform.isin(['Facebook','Instagram','Threads']).all()
assert e.candidate_key.isin(w.candidate_key).all()
assert w[['window_count','followers_start','followers_end']].eq('').all().all()
assert not e.account_url.str.contains('moi.gov.tw|humansoftaipei|/share.php|/sharer').any()
assert e[e.candidate_name.eq('沈伯洋') & e.platform.eq('Threads')].account_url.eq('https://www.threads.com/@pumashen').all()
print('PASS：逐檔 hash、序列化列數、來源證據鍵、全名冊三平台、未蒐集值不填零及範例來源核對。')

PASS：逐檔 hash、序列化列數、來源證據鍵、全名冊三平台、未蒐集值不填零及範例來源核對。