# Data Description
- Author: RUEI-HSIANG, CHANG (B12303030)，Codex 協助
- Date first created: 20261019
- Background: 新來源索引帶回實際原始頁，區分來源線索、整頁原文、欄位已擷取、自述、官方歷史身分支持等不同完成程度。
- Unit of observation: 教育線索＝候選人×來源；頁面＝候選人×來源×頁；人物頁＝候選人；逐欄證據＝候選人×欄位×來源；社群與縣市長來源＝候選人×連結；current三表沿用原觀察單位。
- Sample period: 2026研究名冊，來源年代逐筆保存；2026-10-19取得。
- Known issues: 341人的第三方線索未等同完成341人學歷。HTML僅解析text/html並以已確認UTF-8解碼；ZIP不送入HTML解析器。舊社群證據中的8個林國漳分享網址已移至未解析表，新清單保留網站直接列出的粉專入口。姓名出現在PDF整頁仍可能有同名或欄位錯配，尚未逐格核對者不填入教育原文。新人物頁／競選網站為來源申報，不認證戶籍或學位；僅有來源原文而未確認者保留未知。未讀取完整貼文／追蹤數，Meta申請與貼文蒐集依學生指示暫緩。
- Definition for each variable:

  - candidate_key、candidate_name、county_city、electoral_district：研究名冊的候選人鍵、姓名、縣市與選區，依姓名＋完整選區唯一對應索引。
  - 教育線索的upstream_claim_raw／source_type／source_year：第三方原文字串與分類，明確不是已驗證教育欄；source_url／fetch_url分別保留含頁碼原連結及實際請求網址。
  - http_status、source_file、source_sha256、parse_error：存取、保存與解析結果；document_is_government依實際host，未照抄第三方gov標記。
  - requested_page、actual_name_pages、page_name_status、html_name_present、validation_status：指定頁、實際姓名出現頁與檢查結果；只驗證姓名可讀，不當作所有欄位已正確切分或當屆身分認證。
  - 頁面表page／page_text：完整來源頁與轉出的整頁文字（換行以字面\n保存），page_role明示未切分候選人欄位；可能含同頁其他候選人資料，不能整頁歸屬一人。
  - 新人物頁profile_url／education_raw／experience_raw：已查看的明確欄位或逐字原文；source_year／evidence_tier／identity_status保留年代、自述與待獨立身分核對。
  - 新逐欄證據field／value_raw／source_locator／source_sha256：欄位、原文、DOM區塊或手選文字片段及來源檔hash；不擅自補學位或畢業。林鈺梅birthday為官網明載自述，不混入官方歷史支持欄。
  - 社群account_url／status：人物頁專屬社群區塊連結，目標內容未核對；縣市長第三方線索kind／url／upstream_evidence_url／note／verification_status保留第三方標記，不宣稱本研究認證。
  - 社群current工作單每人每平台一列；official_urls為來源頁連出的入口，account_status保留目標內容待核對。window_count與followers_start/end均未蒐集、留空白。未解析分享及群組網址另表保留，不視為個人帳號。
  - upstream_repository／upstream_commit：上游公開索引固定版本，供來源追溯及署名。
  - current主表／欄位表沿用舊變數定義，本輪更新新增人物頁、教育來源待核對狀態、1筆birth_date與社群來源連結；其餘未改欄位經assertions比對。議員背景新增additional_profile_url／status及birth_date_self_declared／source，歷史支持690人欄位保留不動。

- Data path / Role / SHA-256:
  - data/processed/snapshots/source_extraction_20261019/council_education_source_leads_20261019.csv / source leads, evidence or collection inventory / adad3affa587d85301205160f25b83770a5abb7cc8c9d8f84a4a9683c78da349 (343列)
  - data/processed/snapshots/source_extraction_20261019/candidate_background_source_pages_20261019.csv / source leads, evidence or collection inventory / 1ea2f5c05afca12b60c3454dac7541c3b5d71e84ee77588dd4b252083a17ac37 (171列)
  - data/processed/candidate_web_profiles_expansion_20261019.csv / source leads, evidence or collection inventory / 7bd9873b0528d043e03223344df7d6344c272d6ec5cf9da28aa3457d3adf1361 (22列)
  - data/processed/candidate_background_evidence_expansion_20261019.csv / source leads, evidence or collection inventory / 90c27164083affaa508f87603dd02872f615095944e93ef26065185598f72a8f (64列)
  - data/processed/mayor_channel_discovery_leads_20261019.csv / source leads, evidence or collection inventory / 73370b240df6289566f11ca678dbaf4ef0ed1dd695c5e578231e67ea5ef0e053 (85列)
  - data/processed/council_social_links_expansion_20261019.csv / source leads, evidence or collection inventory / e752e42b983ba0d4be7f18669f89347513d830c84ea4f794bfa7641bfc55c514 (9列)
  - data/processed/snapshots/pre_government_round4_20261019/candidate_master_current.csv / source leads, evidence or collection inventory / bc3a9a7ef0aad7b2ac792581295b653e116dc630d20164fb4def968bf51d52a5 (1583列)
  - data/processed/snapshots/pre_government_round4_20261019/candidate_fields_current.csv / source leads, evidence or collection inventory / df2314986ed5eed973dc35d6d7c6f556d99ea55a2809f86fd5f1045313ec6894 (31660列)
  - data/processed/snapshots/pre_government_round4_20261019/council_background_20261019.csv / source leads, evidence or collection inventory / e64466d2e9f59bf9e2344fc7491b7ae585c00d26351b3b8d161cc468a5757430 (1502列)
  - data/processed/snapshots/pre_bulletin_round5_20261019/candidate_social_account_evidence_current.csv / source leads, evidence or collection inventory / 9178c49adc786db50c9865c2d98ec11747cab0a8cf692dd53c14c3033630649a (188列)
  - data/processed/snapshots/pre_bulletin_round5_20261019/meta_candidate_account_worklist_current.csv / source leads, evidence or collection inventory / 665fd1c45bbb06a312aaa28d9868ba20d3a7361c77fb411801c37158684a23ec (4749列)
  - data/processed/social_unresolved_links_20261019.csv / source leads, evidence or collection inventory / 5a077fad4ad8128d08d580d41b72ffc69819193c4e281a38196ff5ac286dcb82 (47列)
- Source data: 固定上游public_source_index_20261019、background_expansion_20261019的manifest/plan及逐檔保存來源；原current三表已封存於data/processed/snapshots/pre_source_expansion_20261019/，hash對應舊整合版本。
- Extraction cache lineage: data/processed/snapshots/source_extraction_20261019/ 保存第一次成功執行的343筆線索與171筆頁面文字，固定hash後重用；原始已執行程式與輸出另存data/code/source_expansion_initial_execution_20261019.ipynb。
- Processing code: data/code/expand_candidate_sources_20261019.ipynb。
- Role: collection leads / evidence / inventory，並非最後分析樣本；原始來源說明data/raw/source_expansion_20261019_documentation.ipynb。
- Verification status: 下方由保存檔核對hash、schema、鍵、列數與未動欄位；轉換程式另驗證手選文字片段確實存在於保存原頁。
- Downstream analysis input: education_raw／experience_raw可作後續來源審核起點；upstream_claim_raw及整頁page_text不直接當作單一候選人的已核實屬性或政策。


版本註記：本檔的整合三表已封存至snapshots/pre_government_round4_20261019；後續官方人物頁補充由government_profiles_round4_20261019.ipynb產出最新current。

版本註記：本輪原current檔已封存至snapshots/pre_bulletin_round5_20261019，最新current改由council_bulletin_round5_20261019.ipynb產出。

In [1]:
from pathlib import Path
import json,hashlib,pandas as pd
ROOT=next(p for p in [Path.cwd(),*Path.cwd().parents] if (p/'AGENTS.md').exists() and (p/'templates').is_dir())
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()

## Change for Your Own Data

In [2]:
FRAMES={}
assert sha(ROOT/'data/processed/snapshots/source_extraction_20261019/council_education_source_leads_20261019.csv')=='adad3affa587d85301205160f25b83770a5abb7cc8c9d8f84a4a9683c78da349'
FRAMES['data/processed/snapshots/source_extraction_20261019/council_education_source_leads_20261019.csv']=pd.read_csv(ROOT/'data/processed/snapshots/source_extraction_20261019/council_education_source_leads_20261019.csv',dtype=str).fillna('')
assert len(FRAMES['data/processed/snapshots/source_extraction_20261019/council_education_source_leads_20261019.csv'])==343
assert sha(ROOT/'data/processed/snapshots/source_extraction_20261019/candidate_background_source_pages_20261019.csv')=='1ea2f5c05afca12b60c3454dac7541c3b5d71e84ee77588dd4b252083a17ac37'
FRAMES['data/processed/snapshots/source_extraction_20261019/candidate_background_source_pages_20261019.csv']=pd.read_csv(ROOT/'data/processed/snapshots/source_extraction_20261019/candidate_background_source_pages_20261019.csv',dtype=str).fillna('')
assert len(FRAMES['data/processed/snapshots/source_extraction_20261019/candidate_background_source_pages_20261019.csv'])==171
assert sha(ROOT/'data/processed/candidate_web_profiles_expansion_20261019.csv')=='7bd9873b0528d043e03223344df7d6344c272d6ec5cf9da28aa3457d3adf1361'
FRAMES['data/processed/candidate_web_profiles_expansion_20261019.csv']=pd.read_csv(ROOT/'data/processed/candidate_web_profiles_expansion_20261019.csv',dtype=str).fillna('')
assert len(FRAMES['data/processed/candidate_web_profiles_expansion_20261019.csv'])==22
assert sha(ROOT/'data/processed/candidate_background_evidence_expansion_20261019.csv')=='90c27164083affaa508f87603dd02872f615095944e93ef26065185598f72a8f'
FRAMES['data/processed/candidate_background_evidence_expansion_20261019.csv']=pd.read_csv(ROOT/'data/processed/candidate_background_evidence_expansion_20261019.csv',dtype=str).fillna('')
assert len(FRAMES['data/processed/candidate_background_evidence_expansion_20261019.csv'])==64
assert sha(ROOT/'data/processed/mayor_channel_discovery_leads_20261019.csv')=='73370b240df6289566f11ca678dbaf4ef0ed1dd695c5e578231e67ea5ef0e053'
FRAMES['data/processed/mayor_channel_discovery_leads_20261019.csv']=pd.read_csv(ROOT/'data/processed/mayor_channel_discovery_leads_20261019.csv',dtype=str).fillna('')
assert len(FRAMES['data/processed/mayor_channel_discovery_leads_20261019.csv'])==85
assert sha(ROOT/'data/processed/council_social_links_expansion_20261019.csv')=='e752e42b983ba0d4be7f18669f89347513d830c84ea4f794bfa7641bfc55c514'
FRAMES['data/processed/council_social_links_expansion_20261019.csv']=pd.read_csv(ROOT/'data/processed/council_social_links_expansion_20261019.csv',dtype=str).fillna('')
assert len(FRAMES['data/processed/council_social_links_expansion_20261019.csv'])==9
assert sha(ROOT/'data/processed/snapshots/pre_government_round4_20261019/candidate_master_current.csv')=='bc3a9a7ef0aad7b2ac792581295b653e116dc630d20164fb4def968bf51d52a5'
FRAMES['data/processed/snapshots/pre_government_round4_20261019/candidate_master_current.csv']=pd.read_csv(ROOT/'data/processed/snapshots/pre_government_round4_20261019/candidate_master_current.csv',dtype=str).fillna('')
assert len(FRAMES['data/processed/snapshots/pre_government_round4_20261019/candidate_master_current.csv'])==1583
assert sha(ROOT/'data/processed/snapshots/pre_government_round4_20261019/candidate_fields_current.csv')=='df2314986ed5eed973dc35d6d7c6f556d99ea55a2809f86fd5f1045313ec6894'
FRAMES['data/processed/snapshots/pre_government_round4_20261019/candidate_fields_current.csv']=pd.read_csv(ROOT/'data/processed/snapshots/pre_government_round4_20261019/candidate_fields_current.csv',dtype=str).fillna('')
assert len(FRAMES['data/processed/snapshots/pre_government_round4_20261019/candidate_fields_current.csv'])==31660
assert sha(ROOT/'data/processed/snapshots/pre_government_round4_20261019/council_background_20261019.csv')=='e64466d2e9f59bf9e2344fc7491b7ae585c00d26351b3b8d161cc468a5757430'
FRAMES['data/processed/snapshots/pre_government_round4_20261019/council_background_20261019.csv']=pd.read_csv(ROOT/'data/processed/snapshots/pre_government_round4_20261019/council_background_20261019.csv',dtype=str).fillna('')
assert len(FRAMES['data/processed/snapshots/pre_government_round4_20261019/council_background_20261019.csv'])==1502
assert sha(ROOT/'data/processed/snapshots/pre_bulletin_round5_20261019/candidate_social_account_evidence_current.csv')=='9178c49adc786db50c9865c2d98ec11747cab0a8cf692dd53c14c3033630649a'
FRAMES['data/processed/snapshots/pre_bulletin_round5_20261019/candidate_social_account_evidence_current.csv']=pd.read_csv(ROOT/'data/processed/snapshots/pre_bulletin_round5_20261019/candidate_social_account_evidence_current.csv',dtype=str).fillna('')
assert len(FRAMES['data/processed/snapshots/pre_bulletin_round5_20261019/candidate_social_account_evidence_current.csv'])==188
assert sha(ROOT/'data/processed/snapshots/pre_bulletin_round5_20261019/meta_candidate_account_worklist_current.csv')=='665fd1c45bbb06a312aaa28d9868ba20d3a7361c77fb411801c37158684a23ec'
FRAMES['data/processed/snapshots/pre_bulletin_round5_20261019/meta_candidate_account_worklist_current.csv']=pd.read_csv(ROOT/'data/processed/snapshots/pre_bulletin_round5_20261019/meta_candidate_account_worklist_current.csv',dtype=str).fillna('')
assert len(FRAMES['data/processed/snapshots/pre_bulletin_round5_20261019/meta_candidate_account_worklist_current.csv'])==4749
assert sha(ROOT/'data/processed/social_unresolved_links_20261019.csv')=='5a077fad4ad8128d08d580d41b72ffc69819193c4e281a38196ff5ac286dcb82'
FRAMES['data/processed/social_unresolved_links_20261019.csv']=pd.read_csv(ROOT/'data/processed/social_unresolved_links_20261019.csv',dtype=str).fillna('')
assert len(FRAMES['data/processed/social_unresolved_links_20261019.csv'])==47

## Summary

In [3]:
for p,d in FRAMES.items():print(p,{'rows':len(d),'columns':len(d.columns)})

data/processed/snapshots/source_extraction_20261019/council_education_source_leads_20261019.csv {'rows': 343, 'columns': 21}
data/processed/snapshots/source_extraction_20261019/candidate_background_source_pages_20261019.csv {'rows': 171, 'columns': 12}
data/processed/candidate_web_profiles_expansion_20261019.csv {'rows': 22, 'columns': 12}
data/processed/candidate_background_evidence_expansion_20261019.csv {'rows': 64, 'columns': 14}
data/processed/mayor_channel_discovery_leads_20261019.csv {'rows': 85, 'columns': 10}
data/processed/council_social_links_expansion_20261019.csv {'rows': 9, 'columns': 7}
data/processed/snapshots/pre_government_round4_20261019/candidate_master_current.csv {'rows': 1583, 'columns': 34}
data/processed/snapshots/pre_government_round4_20261019/candidate_fields_current.csv {'rows': 31660, 'columns': 11}
data/processed/snapshots/pre_government_round4_20261019/council_background_20261019.csv {'rows': 1502, 'columns': 30}
data/processed/snapshots/pre_bulletin_round5_20261019/candidate_social_account_evidence_current.csv {'rows': 188, 'columns': 12}
data/processed/snapshots/pre_bulletin_round5_20261019/meta_candidate_account_worklist_current.csv {'rows': 4749, 'columns': 13}
data/processed/social_unresolved_links_20261019.csv {'rows': 47, 'columns': 5}

### Sample

In [4]:
for p,d in FRAMES.items():
 print(p);display(d.head(10))

data/processed/snapshots/source_extraction_20261019/council_education_source_leads_20261019.csv

,candidate_key,candidate_name,county_city,electoral_district,upstream_claim_raw,upstream_source_type,upstream_source_year,source_url,fetch_url,http_status,...,source_sha256,document_is_government,requested_page,actual_name_pages,page_name_status,html_name_present,validation_status,parse_error,upstream_repository,upstream_commit
0,2026|直轄市議員|高雄市第1選舉區|林慧欣,林慧欣,高雄市,高雄市第1選舉區,"[""國立高雄師範大學・客家文化研究所，未載學位（2022年公報自填）""]",gazette,2022,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,200,...,13d98d3897822d0ca5de04681a42337d7d3dc84443f965...,True,1,1,name_present_on_requested_page,False,source_saved_name_found_fields_and_identity_pe...,,weryk153/legislator-background,84e3f47f21263575c6e8f7d634c11a4d51f47e5a
1,2026|直轄市議員|高雄市第1選舉區|鍾炳光,鍾炳光,高雄市,高雄市第1選舉區,"[""臺灣警察專科學校・警專第1期畢業（2026年報導）""]",news,2026,https://udn.com/news/story/7327/9366552,https://udn.com/news/story/7327/9366552,200,...,3c579ee43ebd63760b446f220734e5e9a6041c7926a097...,False,,,not_a_readable_saved_pdf,True,source_saved_name_found_fields_and_identity_pe...,,weryk153/legislator-background,84e3f47f21263575c6e8f7d634c11a4d51f47e5a
2,2026|直轄市議員|高雄市第1選舉區|李振豪,李振豪,高雄市,高雄市第1選舉區,"[""國立臺南藝術大學・音樂學士（2026年報導）""]",news,2026,https://youngnews3631.com/news_detail.php?News...,https://youngnews3631.com/news_detail.php?News...,200,...,89e9bffd737bf1501a0a55d1d77167889fc1ae9021ea1d...,False,,,not_a_readable_saved_pdf,True,source_saved_name_found_fields_and_identity_pe...,,weryk153/legislator-background,84e3f47f21263575c6e8f7d634c11a4d51f47e5a
3,2026|直轄市議員|高雄市第2選舉區|李柏融,李柏融,高雄市,高雄市第2選舉區,"[""臺南市六信高級中學・高中學歷，未載畢業（2022年公報自填）""]",gazette,2022,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,200,...,9427a9b23315effeada0c78fbfc63d55d4823e2d9b462d...,True,1,1,name_present_on_requested_page,False,source_saved_name_found_fields_and_identity_pe...,,weryk153/legislator-background,84e3f47f21263575c6e8f7d634c11a4d51f47e5a
4,2026|直轄市議員|高雄市第2選舉區|鄭東元,鄭東元,高雄市,高雄市第2選舉區,"[""國立高雄大學・經濟管理碩士（2022年公報自填）"", ""正修科技大學・專科部土木工程畢業...",gazette,2022,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,200,...,9427a9b23315effeada0c78fbfc63d55d4823e2d9b462d...,True,1,1,name_present_on_requested_page,False,source_saved_name_found_fields_and_identity_pe...,,weryk153/legislator-background,84e3f47f21263575c6e8f7d634c11a4d51f47e5a
5,2026|直轄市議員|高雄市第2選舉區|陳琳潔,陳琳潔,高雄市,高雄市第2選舉區,"[""英國倫敦大學・公共行政碩士（2026年報導）""]",news,2026,https://greatnews.com.tw/news_pagein.php?iType...,https://greatnews.com.tw/news_pagein.php?iType...,200,...,4dfa05a7a64c8bb3c328bef0ab0486acaf8778368b0f81...,False,,,not_a_readable_saved_pdf,True,source_saved_name_found_fields_and_identity_pe...,,weryk153/legislator-background,84e3f47f21263575c6e8f7d634c11a4d51f47e5a
6,2026|直轄市議員|高雄市第3選舉區|張騏晟,張騏晟,高雄市,高雄市第3選舉區,"[""國立高雄科技大學・水產科技產業博士（2026年報導）""]",news,2026,https://www.lifebilss.org.tw/p/81854/299936,https://www.lifebilss.org.tw/p/81854/299936,200,...,dd16b085769408b7a4af6d170a6aa17095064854535064...,False,,,not_a_readable_saved_pdf,True,source_saved_name_found_fields_and_identity_pe...,,weryk153/legislator-background,84e3f47f21263575c6e8f7d634c11a4d51f47e5a
7,2026|直轄市議員|高雄市第3選舉區|黃韻涵,黃韻涵,高雄市,高雄市第3選舉區,"[""美國德州休士頓大學・學士，未載系所（2026年報導）"", ""義守大學・管理學碩士（202...",news,2026,https://www.bo6s.com.tw/search_detail.php?News...,https://www.bo6s.com.tw/search_detail.php?News...,200,...,101da34c2d3558ac1e41826bfd479f9e076ad6e805359d...,False,,,not_a_readable_saved_pdf,True,source_saved_name_found_fields_and_identity_pe...,,weryk153/legislator-background,84e3f47f21263575c6e8f7d634c11a4d51f47e5a
8,2026|直轄市議員|高雄市第4選舉區|張以理,張以理,高雄市,高雄市第4選舉區,"[""大同大學・工業設計研究所，未載學位（參選網站自述）""]",website,,https://www.pridewatch.tw/candidate/idealyouth...,https://www.pridewatch.tw/candidate/idealyouth...,200,...,2af7826d5efb26847c5c1971fc0a13a608202d7aee4e75...,False,,,not_a_readable_saved_pdf,True,source_saved_name_found_fields_and_identity_pe...,,weryk153/legislator-background,84e3f47f21263575c6e8f7d634c11a4d51f47e5a
9,2026|直轄市議員|高雄市第4選舉區|柳淑芳,柳淑芳,高雄市,高雄市第4選舉區,"[""岡山農工・化工科，未載畢業（2022年公報自填）""]",gazette,2022,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,200,...,737d6a547b3012138fccb0e2d1375aea3415d7128d5842...,True,3,3,name_present_on_requested_page,False,source_saved_name_found_fields_and_identity_pe...,,weryk153/legislator-background,84e3f47f21263575c6e8f7d634c11a4d51f47e5a

data/processed/snapshots/source_extraction_20261019/candidate_background_source_pages_20261019.csv

,candidate_key,candidate_name,county_city,source_url,fetch_url,source_file,source_sha256,page,page_text,page_role,identity_status,government_source
0,2026|直轄市議員|高雄市第1選舉區|林慧欣,林慧欣,高雄市,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/06a729e...,13d98d3897822d0ca5de04681a42337d7d3dc84443f965...,1,遵守選舉法令 宏揚法治精神\n3\n第1頁(共1頁 )\n高雄市議會第4屆議員選舉，經定於中...,whole_source_page_not_segmented_candidate_fields,historical_name_match_pending_independent_linkage,True
1,2026|直轄市議員|高雄市第2選舉區|李柏融,李柏融,高雄市,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/bd66678...,9427a9b23315effeada0c78fbfc63d55d4823e2d9b462d...,1,遵守選舉法令 宏揚法治精神 第1頁(共1頁 )\n高雄市議會第4屆議員選舉，經定於中華民國一...,whole_source_page_not_segmented_candidate_fields,historical_name_match_pending_independent_linkage,True
2,2026|直轄市議員|高雄市第2選舉區|鄭東元,鄭東元,高雄市,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/bd66678...,9427a9b23315effeada0c78fbfc63d55d4823e2d9b462d...,1,遵守選舉法令 宏揚法治精神 第1頁(共1頁 )\n高雄市議會第4屆議員選舉，經定於中華民國一...,whole_source_page_not_segmented_candidate_fields,historical_name_match_pending_independent_linkage,True
3,2026|直轄市議員|高雄市第4選舉區|柳淑芳,柳淑芳,高雄市,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/0108098...,737d6a547b3012138fccb0e2d1375aea3415d7128d5842...,3,11\n12\n13\n14\n15\n遵守選舉法令 宏揚法治精神 第3頁(共4頁 )\n高...,whole_source_page_not_segmented_candidate_fields,historical_name_match_pending_independent_linkage,True
4,2026|直轄市議員|高雄市第5選舉區|陳若翠,陳若翠,高雄市,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/a36fb7c...,f235d01f3f55f226a269fe4fa002bd2ad068b00d2d34e6...,1,遵守選舉法令 宏揚法治精神 第1頁(共2頁 )\n高雄市議會第4屆議員選舉，經定於中華民國一...,whole_source_page_not_segmented_candidate_fields,historical_name_match_pending_independent_linkage,True
5,2026|直轄市議員|高雄市第5選舉區|陳惠君,陳惠君,高雄市,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/5a9df43...,6b80caadfefe6397e93270e076ea99f7d4cbd175a54fc6...,3,第5選舉區：大社區、仁武區、鳥松區、大樹區\n無\n1.灣內國小\n2.仁武國中\n3.南榮...,whole_source_page_not_segmented_candidate_fields,historical_name_match_pending_independent_linkage,True
6,2026|直轄市議員|高雄市第7選舉區|童燕珍,童燕珍,高雄市,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/806bb89...,fc917d512e7aa3c652fb4dae815311f054fc6ea91ac315...,2,遵守選舉法令 宏揚法治精神 第2頁(共3頁 )\n6\n進\n基\n灣\n台\n80\n年\...,whole_source_page_not_segmented_candidate_fields,historical_name_match_pending_independent_linkage,True
7,2026|直轄市議員|高雄市第7選舉區|林于凱,林于凱,高雄市,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/806bb89...,fc917d512e7aa3c652fb4dae815311f054fc6ea91ac315...,1,遵守選舉法令 宏揚法治精神\n3\n第1頁(共3頁 )\n高雄市議會第4屆議員選舉，經定於中...,whole_source_page_not_segmented_candidate_fields,historical_name_match_pending_independent_linkage,True
8,2026|直轄市議員|高雄市第9選舉區|蘇致榮,蘇致榮,高雄市,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/07d3192...,22ae5353195c3fe1335d3a93ec34a94a52a8ad38b59c7c...,3,男 國立中山大學海事所碩士\n國立中山大學海資系\n高雄市議會特色公園小組召集人\n高雄市議...,whole_source_page_not_segmented_candidate_fields,historical_name_match_pending_independent_linkage,True
9,2026|直轄市議員|高雄市第9選舉區|徐尚賢,徐尚賢,高雄市,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,https://eebulletin.cec.gov.tw/111/07%E9%AB%98%...,data/raw/background_expansion_20261019/07d3192...,22ae5353195c3fe1335d3a93ec34a94a52a8ad38b59c7c...,3,男 國立中山大學海事所碩士\n國立中山大學海資系\n高雄市議會特色公園小組召集人\n高雄市議...,whole_source_page_not_segmented_candidate_fields,historical_name_match_pending_independent_linkage,True

data/processed/candidate_web_profiles_expansion_20261019.csv

,candidate_key,candidate_name,county_city,electoral_district,profile_url,education_raw,experience_raw,source_file,source_sha256,source_year,evidence_tier,identity_status
0,2026|直轄市議員|高雄市第4選舉區|張以理,張以理,高雄市,高雄市第4選舉區,https://www.pridewatch.tw/candidate/idealyouth...,大同大學工業設計研究所 | 道明中學 | 前金國小,高雄市政府青年局局長 | 陳其邁競選總部發言人 | 蔡英文高雄競選總部執行長 | 立委趙天麟...,data/raw/background_expansion_20261019/7da34d7...,2af7826d5efb26847c5c1971fc0a13a608202d7aee4e75...,2026,civil_society_candidate_profile_declaration_no...,name_and_candidate_context_lead_pending_indepe...
1,2026|直轄市議員|高雄市第7選舉區|林彥,林彥,高雄市,高雄市第7選舉區,https://portaly.cc/issue101/pages/introduceyou...,國立臺灣科技大學 工學院學士 | 國立高雄應用科技大學 商學院學士 | 國立高雄科技大學 商...,曾於 高雄市政府 負責觀光旅宿管理 | 也曾在 高雄榮民總醫院 推動各行政區與醫療單位的公共...,data/raw/background_expansion_20261019/b0aa3c4...,335eb135ac0b6b4f1c42425d72c1560019d5b76835059b...,2026,candidate_website_self_declaration_not_degree_...,name_and_candidate_context_lead_pending_indepe...
2,2026|縣市議員|雲林縣第1選舉區|廖昶淳,廖昶淳,雲林縣,雲林縣第1選舉區,https://newpowerparty.tw/vote2026/candidate-2610,國立臺灣師範大學地理學系碩士班 | 國立臺灣師範大學地理學系 | 國立斗六高級中學 | 雲林...,國立臺灣師範大學地理學系研究助理 | 農業部林業及自然保育署專案計畫經理 | 教育部數位學習...,data/raw/background_expansion_20261019/db6abdb...,5993c4d09e1a5ab872c51589781d2012f4f45f0f3a8444...,2026,official_party_candidate_profile_self_declaration,name_and_candidate_context_lead_pending_indepe...
3,2026|直轄市議員|新北市第1選舉區|游明諺,游明諺,新北市,新北市第1選舉區,https://pridewatch.tw/candidate/%E6%B8%B8%E6%9...,♦︎私立明新科技大學,♦︎立法院國會 何志偉辦公室主任 | ♦︎台北市議員 鍾佩玲辦公室主任 | ♦︎台灣新動力智...,data/raw/background_expansion_20261019/59ce126...,ff3b21bc31da38a1560a6a519cd65b522689b40f4c6c23...,2026,civil_society_candidate_profile_declaration_no...,name_and_candidate_context_lead_pending_indepe...
4,2026|直轄市議員|新北市第4選舉區|陳彥廷,陳彥廷,新北市,新北市第4選舉區,https://andy.believe.tw/,台大光電碩士,家樂福 15 年資深經歷,data/raw/background_expansion_20261019/207b065...,c38e532cfff926c7107e44a546f813066f6614596b84d4...,2026,candidate_website_self_declaration_not_degree_...,name_and_candidate_context_lead_pending_indepe...
5,2026|直轄市議員|新北市第4選舉區|蕭告,蕭告,新北市,新北市第4選舉區,https://www.hsiaogao.com/about/aboutus/,國立臺灣大學法律學系司法組畢業 | 加州大學舊金山法學院（UC Hastings）交換學生,蕭告律師事務所主持律師,data/raw/background_expansion_20261019/655ffe4...,f5b79e79b9090f426d08abd27a439fcb1173fcc8b2695d...,2026,candidate_website_self_declaration_not_degree_...,name_and_candidate_context_lead_pending_indepe...
6,2026|直轄市議員|新北市第5選舉區|李昆穎,李昆穎,新北市,新北市第5選舉區,https://yingforfuture.oen.tw/,,,data/raw/background_expansion_20261019/73ebd03...,e0d2a8b48d725e93c1f80e4434a102a13f415be054d514...,2026,candidate_website_self_declaration_not_degree_...,name_and_candidate_context_lead_pending_indepe...
7,2026|直轄市議員|新北市第5選舉區|陳俊諺,陳俊諺,新北市,新北市第5選舉區,https://www.pridewatch.tw/candidate/gogoyen,國防大學戰略暨國際事務研究所碩士 | 東海大學政治系 | 華江高中 | 新埔國中 | 文德國小,立法委員張宏陸服務處-助理 | 新北市議員石一佑服務處-執行長 | 新北市信賴之友會板橋分會...,data/raw/background_expansion_20261019/79f96db...,08846b4d2e36a314e5f77fa3fa013b746afe345d3eba37...,2026,civil_society_candidate_profile_declaration_no...,name_and_candidate_context_lead_pending_indepe...
8,2026|直轄市議員|新北市第9選舉區|陳韋任,陳韋任,新北市,新北市第9選舉區,https://pridewatch.tw/candidate/weijenchenoa,1. 國立臺灣科技大學建築研究所（碩士班） | 2. 中原大學建築系 | 3. 國立政治大學...,1. 立法委員蘇巧慧服務團隊副主任 | 2. 新北市議員陳永福服務團隊特助 | 3. 民進黨...,data/raw/background_expansion_20261019/3feafed...,29c805f58f6c73d1710288a5df35e1fb54ed21efd9a329...,2026,civil_society_candidate_profile_declaration_no...,name_and_candidate_context_lead_pending_indepe...
9,2026|縣市議員|新竹市第1選舉區|林妤芬,林妤芬,新竹市,新竹市第1選舉區,https://yufenlovehsinchu.com/,美國加州大學柏克萊分校 | 法學碩士（LL.M.） | 輔仁大學財經法律系 | 法學士,新竹市政府廉政會報委員 | 新竹縣警局諮詢委員 | 弘準國際法律事務所 | 主持律師,data/raw/background_expansion_20261019/e258a4f...,0260f70fe65c476490ccd3c2db52b0f0fe0729e75ce478...,2026,candidate_website_self_declaration_not_degree_...,name_and_candidate_context_lead_pending_indepe...

data/processed/candidate_background_evidence_expansion_20261019.csv

,candidate_key,candidate_name,county_city,office_type,field,value_raw,source_url,source_file,source_sha256,source_locator,source_year,evidence_tier,identity_status,checked_date
0,2026|直轄市議員|高雄市第4選舉區|張以理,張以理,高雄市,直轄市議員,profile_url,https://www.pridewatch.tw/candidate/idealyouth...,https://www.pridewatch.tw/candidate/idealyouth...,data/raw/background_expansion_20261019/7da34d7...,2af7826d5efb26847c5c1971fc0a13a608202d7aee4e75...,candidate/person background page with matching...,2026,civil_society_candidate_profile_declaration_no...,source_name_and_candidate_context_reviewed_pen...,2026-10-19
1,2026|直轄市議員|高雄市第4選舉區|張以理,張以理,高雄市,直轄市議員,education,大同大學工業設計研究所 | 道明中學 | 前金國小,https://www.pridewatch.tw/candidate/idealyouth...,data/raw/background_expansion_20261019/7da34d7...,2af7826d5efb26847c5c1971fc0a13a608202d7aee4e75...,.views-field-field-education/.views-field-fiel...,2026,civil_society_candidate_profile_declaration_no...,source_name_and_candidate_context_reviewed_pen...,2026-10-19
2,2026|直轄市議員|高雄市第4選舉區|張以理,張以理,高雄市,直轄市議員,experience,高雄市政府青年局局長 | 陳其邁競選總部發言人 | 蔡英文高雄競選總部執行長 | 立委趙天麟...,https://www.pridewatch.tw/candidate/idealyouth...,data/raw/background_expansion_20261019/7da34d7...,2af7826d5efb26847c5c1971fc0a13a608202d7aee4e75...,.views-field-field-education/.views-field-fiel...,2026,civil_society_candidate_profile_declaration_no...,source_name_and_candidate_context_reviewed_pen...,2026-10-19
3,2026|直轄市議員|高雄市第7選舉區|林彥,林彥,高雄市,直轄市議員,profile_url,https://portaly.cc/issue101/pages/introduceyou...,https://portaly.cc/issue101/pages/introduceyou...,data/raw/background_expansion_20261019/b0aa3c4...,335eb135ac0b6b4f1c42425d72c1560019d5b76835059b...,candidate/person background page with matching...,2026,candidate_website_self_declaration_not_degree_...,source_name_and_candidate_context_reviewed_pen...,2026-10-19
4,2026|直轄市議員|高雄市第7選舉區|林彥,林彥,高雄市,直轄市議員,education,國立臺灣科技大學 工學院學士 | 國立高雄應用科技大學 商學院學士 | 國立高雄科技大學 商...,https://portaly.cc/issue101/pages/introduceyou...,data/raw/background_expansion_20261019/b0aa3c4...,335eb135ac0b6b4f1c42425d72c1560019d5b76835059b...,manually selected literal source spans,2026,candidate_website_self_declaration_not_degree_...,source_name_and_candidate_context_reviewed_pen...,2026-10-19
5,2026|直轄市議員|高雄市第7選舉區|林彥,林彥,高雄市,直轄市議員,experience,曾於 高雄市政府 負責觀光旅宿管理 | 也曾在 高雄榮民總醫院 推動各行政區與醫療單位的公共...,https://portaly.cc/issue101/pages/introduceyou...,data/raw/background_expansion_20261019/b0aa3c4...,335eb135ac0b6b4f1c42425d72c1560019d5b76835059b...,manually selected literal source spans,2026,candidate_website_self_declaration_not_degree_...,source_name_and_candidate_context_reviewed_pen...,2026-10-19
6,2026|縣市議員|雲林縣第1選舉區|廖昶淳,廖昶淳,雲林縣,縣（市）議員,profile_url,https://newpowerparty.tw/vote2026/candidate-2610,https://newpowerparty.tw/vote2026/candidate-2610,data/raw/background_expansion_20261019/db6abdb...,5993c4d09e1a5ab872c51589781d2012f4f45f0f3a8444...,candidate/person background page with matching...,2026,official_party_candidate_profile_self_declaration,source_name_and_candidate_context_reviewed_pen...,2026-10-19
7,2026|縣市議員|雲林縣第1選舉區|廖昶淳,廖昶淳,雲林縣,縣（市）議員,education,國立臺灣師範大學地理學系碩士班 | 國立臺灣師範大學地理學系 | 國立斗六高級中學 | 雲林...,https://newpowerparty.tw/vote2026/candidate-2610,data/raw/background_expansion_20261019/db6abdb...,5993c4d09e1a5ab872c51589781d2012f4f45f0f3a8444...,h5 學歷／經歷所在e-con之text-editor,2026,official_party_candidate_profile_self_declaration,source_name_and_candidate_context_reviewed_pen...,2026-10-19
8,2026|縣市議員|雲林縣第1選舉區|廖昶淳,廖昶淳,雲林縣,縣（市）議員,experience,國立臺灣師範大學地理學系研究助理 | 農業部林業及自然保育署專案計畫經理 | 教育部數位學習...,https://newpowerparty.tw/vote2026/candidate-2610,data/raw/background_expansion_20261019/db6abdb...,5993c4d09e1a5ab872c51589781d2012f4f45f0f3a8444...,h5 學歷／經歷所在e-con之text-editor,2026,official_party_candidate_profile_self_declaration,source_name_and_candidate_context_reviewed_pen...,2026-10-19
9,2026|直轄市議員|新北市第1選舉區|游明諺,游明諺,新北市,直轄市議員,profile_url,https://pridewatch.tw/candidate/%E6%B8%B8%E6%9...,https://pridewatch.tw/candidate/%E6%B8%B8%E6%9...,data/raw/background_expansion_20261019/59ce126...,ff3b21bc31da38a1560a6a519cd65b522689b40f4c6c23...,candidate/person background page with matching...,2026,civil_society_candidate_profile_declaration_no...,source_name_and_candidate_context_reviewed_pen...,2026-10-19

data/processed/mayor_channel_discovery_leads_20261019.csv

,candidate_key,candidate_name,county_city,kind,url,upstream_evidence_url,upstream_note,verification_status,upstream_repository,upstream_commit
0,2026-C1-001,郭璽,臺北市,facebook-page,https://www.facebook.com/p/%E9%83%AD%E7%92%BD-...,https://www.facebook.com/p/%E9%83%AD%E7%92%BD-...,專頁列西北大學博士、國防背景，與候選人履歷相符；頁面仍保留過往選舉內容。,third_party_discovery_lead_not_independently_r...,weryk153/legislator-background,84e3f47f21263575c6e8f7d634c11a4d51f47e5a
1,2026-C1-002,沈伯洋,臺北市,campaign,https://puma.taipei/,https://puma.taipei/,網站列出本人姓名、參選職位與競選內容。,third_party_discovery_lead_not_independently_r...,weryk153/legislator-background,84e3f47f21263575c6e8f7d634c11a4d51f47e5a
2,2026-C1-002,沈伯洋,臺北市,facebook-page,https://www.facebook.com/puma.taipei/,https://www.facebook.com/puma.taipei/,核對公開頁面姓名、政治／參選身分與所在地，並比對本次候選人名冊及搜尋結果。,third_party_discovery_lead_not_independently_r...,weryk153/legislator-background,84e3f47f21263575c6e8f7d634c11a4d51f47e5a
3,2026-C1-003,蕭文乾,臺北市,facebook-profile,https://www.facebook.com/wen.hsiao.100/,https://www.facebook.com/wen.hsiao.100/,公開帳號顯示 Wen Hsiao／蕭文乾，發表 SoR 英文教育內容，與候選人的教育專業相符。,third_party_discovery_lead_not_independently_r...,weryk153/legislator-background,84e3f47f21263575c6e8f7d634c11a4d51f47e5a
4,2026-C1-005,蔣萬安,臺北市,facebook-page,https://www.facebook.com/chiangwanan/,https://www.facebook.com/chiangwanan/,核對公開頁面姓名、政治／參選身分與所在地，並比對本次候選人名冊及搜尋結果。,third_party_discovery_lead_not_independently_r...,weryk153/legislator-background,84e3f47f21263575c6e8f7d634c11a4d51f47e5a
5,2026-C1-007,蘇巧慧,新北市,campaign,https://chiao.tw/,https://chiao.tw/,網站列出本人姓名、參選職位與競選內容。,third_party_discovery_lead_not_independently_r...,weryk153/legislator-background,84e3f47f21263575c6e8f7d634c11a4d51f47e5a
6,2026-C1-007,蘇巧慧,新北市,facebook-page,https://www.facebook.com/chiaohui.su/,https://chiao.tw/,候選人網站直接連至此 Facebook，並已打開頁面核對姓名與身分。,third_party_discovery_lead_not_independently_r...,weryk153/legislator-background,84e3f47f21263575c6e8f7d634c11a4d51f47e5a
7,2026-C1-008,李四川,新北市,hub,https://portaly.cc/hammerlee,https://portaly.cc/hammerlee,本人官方社群連結頁，集中列出社群與競選資訊。,third_party_discovery_lead_not_independently_r...,weryk153/legislator-background,84e3f47f21263575c6e8f7d634c11a4d51f47e5a
8,2026-C1-008,李四川,新北市,facebook-page,https://www.facebook.com/p/%E6%9D%8E%E5%9B%9B%...,https://portaly.cc/hammerlee,候選人網站直接連至此 Facebook，並已打開頁面核對姓名與身分。,third_party_discovery_lead_not_independently_r...,weryk153/legislator-background,84e3f47f21263575c6e8f7d634c11a4d51f47e5a
9,2026-C1-010,張善政,桃園市,facebook-page,https://www.facebook.com/SanCheng624/,https://www.facebook.com/SanCheng624/,核對公開頁面姓名、政治／參選身分與所在地，並比對本次候選人名冊及搜尋結果。,third_party_discovery_lead_not_independently_r...,weryk153/legislator-background,84e3f47f21263575c6e8f7d634c11a4d51f47e5a

data/processed/council_social_links_expansion_20261019.csv

,candidate_key,candidate_name,county_city,account_url,source_url,source_file,status
0,2026|直轄市議員|新北市第1選舉區|游明諺,游明諺,新北市,https://www.facebook.com/share/14oUmftzKBj/?mi...,https://pridewatch.tw/candidate/%E6%B8%B8%E6%9...,data/raw/background_expansion_20261019/59ce126...,candidate_specific_social_block_link_target_co...
1,2026|直轄市議員|新北市第1選舉區|游明諺,游明諺,新北市,https://www.instagram.com/youmingyan88588?stkn...,https://pridewatch.tw/candidate/%E6%B8%B8%E6%9...,data/raw/background_expansion_20261019/59ce126...,candidate_specific_social_block_link_target_co...
2,2026|直轄市議員|新北市第1選舉區|游明諺,游明諺,新北市,https://line.me/ti/p/~@941dliay,https://pridewatch.tw/candidate/%E6%B8%B8%E6%9...,data/raw/background_expansion_20261019/59ce126...,candidate_specific_social_block_link_target_co...
3,2026|直轄市議員|新北市第9選舉區|陳韋任,陳韋任,新北市,https://www.facebook.com/share/1VHY7MXBzY/?mib...,https://pridewatch.tw/candidate/weijenchenoa,data/raw/background_expansion_20261019/3feafed...,candidate_specific_social_block_link_target_co...
4,2026|直轄市議員|新北市第9選舉區|陳韋任,陳韋任,新北市,https://www.instagram.com/weijenchenoa?obrf=Z3...,https://pridewatch.tw/candidate/weijenchenoa,data/raw/background_expansion_20261019/3feafed...,candidate_specific_social_block_link_target_co...
5,2026|縣市議員|南投縣第1選舉區|吳淳祐,吳淳祐,南投縣,https://www.facebook.com/profile.php?id=615900...,https://www.pridewatch.tw/candidate/chunyounantou,data/raw/background_expansion_20261019/0a4e87f...,candidate_specific_social_block_link_target_co...
6,2026|縣市議員|南投縣第1選舉區|吳淳祐,吳淳祐,南投縣,https://www.instagram.com/chunyou.nantou/,https://www.pridewatch.tw/candidate/chunyounantou,data/raw/background_expansion_20261019/0a4e87f...,candidate_specific_social_block_link_target_co...
7,2026|縣市議員|苗栗縣第3選舉區|陳薈茗,陳薈茗,苗栗縣,https://www.facebook.com/share/1C7GzSdVXF/?mib...,https://www.pridewatch.tw/candidate/chenhuimin...,data/raw/background_expansion_20261019/8407709...,candidate_specific_social_block_link_target_co...
8,2026|縣市議員|苗栗縣第3選舉區|陳薈茗,陳薈茗,苗栗縣,https://www.instagram.com/chen.hui.ming?stkn=M...,https://www.pridewatch.tw/candidate/chenhuimin...,data/raw/background_expansion_20261019/8407709...,candidate_specific_social_block_link_target_co...

data/processed/snapshots/pre_government_round4_20261019/candidate_master_current.csv

,candidate_key,candidate_name,office_type,county_city,electoral_district,party_registration_raw,registration_source,registration_source_file,registration_source_page,qualification_inherited,...,Threads_status,posts_Facebook_status,posts_Instagram_status,posts_Threads_status,followers_status,policy_text_status,visual_status,political_family_status,administrative_experience_status,qualification_status
0,2026-C1-001,郭璽,直轄市長,臺北市,,台灣麻將最大黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
1,2026-C1-002,沈伯洋,直轄市長,臺北市,,民主進步黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,人物頁／競選頁已列帳號連結；目標內容待核對,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,部分原文已保存，尚未政策編碼,未查找,未查找,未查找,官方內文待重新核對
2,2026-C1-003,蕭文乾,直轄市長,臺北市,,臺灣SoR無法黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
3,2026-C1-004,唐新民,直轄市長,臺北市,,三勢團結促進聯盟,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
4,2026-C1-005,蔣萬安,直轄市長,臺北市,,中國國民黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
5,2026-C1-006,林志成,直轄市長,臺北市,,無,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
6,2026-C1-007,蘇巧慧,直轄市長,新北市,,民主進步黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,人物頁／競選頁已列帳號連結；目標內容待核對,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,部分原文已保存，尚未政策編碼,未查找,未查找,未查找,官方內文待重新核對
7,2026-C1-008,李四川,直轄市長,新北市,,中國國民黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,人物頁／競選頁已列帳號連結；目標內容待核對,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
8,2026-C1-009,蘇輝湟,直轄市長,新北市,,無,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對
9,2026-C1-010,張善政,直轄市長,桃園市,,中國國民黨,https://web.cec.gov.tw/api/file/bb9a8d7a-9b8a-...,data/raw/2026_metropolitan_registration.pdf,1,approved_2026-10-16,...,尚未驗證，不代表無帳號,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,未取得，不能視為零,待補查原文,未查找,未查找,未查找,官方內文待重新核對

data/processed/snapshots/pre_government_round4_20261019/candidate_fields_current.csv

,candidate_key,candidate_name,office_type,county_city,field,status,existing_value,evidence,note,next_source,updated_date
0,2026-C1-001,郭璽,直轄市長,臺北市,sex,已有資料，待來源複核,男,https://db.cec.gov.tw/,dob_corroborated_by_media,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
1,2026-C1-001,郭璽,直轄市長,臺北市,birth_date,已有資料，待來源複核,1958-08-31,https://db.cec.gov.tw/,CEC_name_and_birth_date_corroborated_by_CNA,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
2,2026-C1-001,郭璽,直轄市長,臺北市,education,已有資料，待來源複核,大學,,歷史公報或媒體補充，非2026學歷認證,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
3,2026-C1-001,郭璽,直轄市長,臺北市,incumbency,既有搜尋後仍缺，待補查,,,,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
4,2026-C1-001,郭璽,直轄市長,臺北市,first_time_this_office,既有搜尋後仍缺，待補查,,,0=有過參選證據；空白不表示首次。此處沿用既有表。,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
5,2026-C1-001,郭璽,直轄市長,臺北市,first_time_any_office,已有資料，待來源複核,0,https://db.cec.gov.tw/,0=有過參選證據；空白不表示首次。此處沿用既有表。,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
6,2026-C1-001,郭璽,直轄市長,臺北市,profile,既有搜尋後仍缺，待補查,,,,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
7,2026-C1-001,郭璽,直轄市長,臺北市,website,既有搜尋後仍缺，待補查,,,,議會／政府人物頁、歷屆選舉公報；身分與時間核對,2026-10-19
8,2026-C1-001,郭璽,直轄市長,臺北市,Facebook,尚未驗證，不代表無帳號,,,,官方人物頁／競選網站交叉連結,2026-10-19
9,2026-C1-001,郭璽,直轄市長,臺北市,Instagram,尚未驗證，不代表無帳號,,,,官方人物頁／競選網站交叉連結,2026-10-19

data/processed/snapshots/pre_government_round4_20261019/council_background_20261019.csv

,candidate_key,candidate_name,county_city,office_type,electoral_district,party_registration_raw,birth_date_supported_history,birth_year_supported_history,sex_supported_history,birth_sex_evidence_status,...,education_completion_status,first_time_this_office_supported,first_time_any_office_supported,incumbency_2026,incumbency_status,updated_date,additional_profile_url,additional_profile_status,birth_date_self_declared,birth_date_self_declared_source
0,2026|直轄市議員|臺北市第1選舉區|謝閔弘,謝閔弘,臺北市,直轄市議員,臺北市第1選舉區,時代力量,,,,尚無可連結的歷史紀錄,...,保留來源原文，未認證學位；在學不當作已畢業,,0,,未由歷史當選或履歷自動推定,2026-10-19,,,,
1,2026|直轄市議員|臺北市第1選舉區|李文,李文,臺北市,直轄市議員,臺北市第1選舉區,無,,,,尚無可連結的歷史紀錄,...,保留來源原文，未認證學位；在學不當作已畢業,,,,未由歷史當選或履歷自動推定,2026-10-19,,,,
2,2026|直轄市議員|臺北市第1選舉區|陳彥廷,陳彥廷,臺北市,直轄市議員,臺北市第1選舉區,無,,,,尚無可連結的歷史紀錄,...,保留來源原文，未認證學位；在學不當作已畢業,,,,未由歷史當選或履歷自動推定,2026-10-19,,,,
3,2026|直轄市議員|臺北市第1選舉區|鍾佩玲,鍾佩玲,臺北市,直轄市議員,臺北市第1選舉區,民主進步黨,1979-03-27,1979,女,2022官方申報，先前身分連結審核有支持；非2026戶籍認定,...,保留來源原文，未認證學位；在學不當作已畢業,0,0,,未由歷史當選或履歷自動推定,2026-10-19,,,,
4,2026|直轄市議員|臺北市第1選舉區|紀建漢,紀建漢,臺北市,直轄市議員,臺北市第1選舉區,無,,,,尚無可連結的歷史紀錄,...,保留來源原文，未認證學位；在學不當作已畢業,,,,未由歷史當選或履歷自動推定,2026-10-19,,,,
5,2026|直轄市議員|臺北市第1選舉區|陳賢蔚,陳賢蔚,臺北市,直轄市議員,臺北市第1選舉區,民主進步黨,1977-07-12,1977,男,2022官方申報，先前身分連結審核有支持；非2026戶籍認定,...,保留來源原文，未認證學位；在學不當作已畢業,0,0,,未由歷史當選或履歷自動推定,2026-10-19,,,,
6,2026|直轄市議員|臺北市第1選舉區|林世宗,林世宗,臺北市,直轄市議員,臺北市第1選舉區,民主進步黨,1959-06-13,1959,男,2022官方申報，先前身分連結審核有支持；非2026戶籍認定,...,保留來源原文，未認證學位；在學不當作已畢業,0,0,,未由歷史當選或履歷自動推定,2026-10-19,,,,
7,2026|直轄市議員|臺北市第1選舉區|黃瀞瑩,黃瀞瑩,臺北市,直轄市議員,臺北市第1選舉區,台灣民眾黨,1992-06-10,1992,女,2022官方申報，先前身分連結審核有支持；非2026戶籍認定,...,保留來源原文，未認證學位；在學不當作已畢業,0,0,,未由歷史當選或履歷自動推定,2026-10-19,,,,
8,2026|直轄市議員|臺北市第1選舉區|林揚庭,林揚庭,臺北市,直轄市議員,臺北市第1選舉區,中國國民黨,,,,尚無可連結的歷史紀錄,...,保留來源原文，未認證學位；在學不當作已畢業,,,,未由歷史當選或履歷自動推定,2026-10-19,,,,
9,2026|直轄市議員|臺北市第1選舉區|陳慈慧,陳慈慧,臺北市,直轄市議員,臺北市第1選舉區,民主進步黨,1983-11-22,1983,女,2022官方申報，先前身分連結審核有支持；非2026戶籍認定,...,保留來源原文，未認證學位；在學不當作已畢業,0,0,,未由歷史當選或履歷自動推定,2026-10-19,,,,

data/processed/snapshots/pre_bulletin_round5_20261019/candidate_social_account_evidence_current.csv

,candidate_key,candidate_name,county_city,office_type,platform,account_url,source_url,source_file,source_locator,evidence_status,target_content_status,checked_date
0,2026|縣市議員|南投縣第1選舉區|吳淳祐,吳淳祐,南投縣,縣（市）議員,Facebook,https://www.facebook.com/profile.php?id=615900...,https://www.pridewatch.tw/candidate/chunyounantou,data/raw/background_expansion_20261019/0a4e87f...,ul.candidate-social-links,candidate_specific_civil_society_profile_link,not_verified_not_posts_captured,2026-10-19
1,2026|縣市議員|南投縣第1選舉區|吳淳祐,吳淳祐,南投縣,縣（市）議員,Instagram,https://www.instagram.com/chunyou.nantou,https://www.pridewatch.tw/candidate/chunyounantou,data/raw/background_expansion_20261019/0a4e87f...,ul.candidate-social-links,candidate_specific_civil_society_profile_link,not_verified_not_posts_captured,2026-10-19
2,2026-C2-033,温世政,南投縣,縣（市）長,Facebook,https://www.facebook.com/wEnShihheng,https://teamtaiwan.dpp.org.tw/asset/types/elec...,data/raw/round3_20261019/cab91a155008312e422c....,mayor_data name=温世政 field=fb,party_candidate_object_link,not_verified_not_posts_captured,2026-10-19
3,2026-C2-033,温世政,南投縣,縣（市）長,Instagram,https://www.instagram.com/wen_shih_cheng,https://teamtaiwan.dpp.org.tw/asset/types/elec...,data/raw/round3_20261019/cab91a155008312e422c....,mayor_data name=温世政 field=ig,party_candidate_object_link,not_verified_not_posts_captured,2026-10-19
4,2026-C2-033,温世政,南投縣,縣（市）長,Threads,https://www.threads.com/@wen_shih_cheng,https://teamtaiwan.dpp.org.tw/asset/types/elec...,data/raw/round3_20261019/cab91a155008312e422c....,mayor_data name=温世政 field=threads,party_candidate_object_link,not_verified_not_posts_captured,2026-10-19
5,2026|縣市議員|嘉義市第2選舉區|林詩涵,林詩涵,嘉義市,縣（市）議員,Facebook,https://www.facebook.com/shihhanlin.chiayi,https://www.taiwangogo.tw/lin-shih-han/,data/raw/round3_20261019/f94d16aea58833d3e1d3....,.cv-social; candidate card 林詩涵; 嘉義市,campaign_directory_candidate_link,not_verified_not_posts_captured,2026-10-19
6,2026|縣市議員|嘉義市第2選舉區|林詩涵,林詩涵,嘉義市,縣（市）議員,Instagram,https://www.instagram.com/flip_chiayi,https://www.taiwangogo.tw/lin-shih-han/,data/raw/round3_20261019/f94d16aea58833d3e1d3....,.cv-social; candidate card 林詩涵; 嘉義市,campaign_directory_candidate_link,not_verified_not_posts_captured,2026-10-19
7,2026-C2-080,王美惠,嘉義市,縣（市）長,Facebook,https://www.facebook.com/ahueimoto,https://teamtaiwan.dpp.org.tw/asset/types/elec...,data/raw/round3_20261019/cab91a155008312e422c....,mayor_data name=王美惠 field=fb,party_candidate_object_link,not_verified_not_posts_captured,2026-10-19
8,2026-C2-080,王美惠,嘉義市,縣（市）長,Instagram,https://www.instagram.com/ahueimoto,https://teamtaiwan.dpp.org.tw/asset/types/elec...,data/raw/round3_20261019/cab91a155008312e422c....,mayor_data name=王美惠 field=ig,party_candidate_object_link,not_verified_not_posts_captured,2026-10-19
9,2026-C2-080,王美惠,嘉義市,縣（市）長,Threads,https://www.threads.com/@ahueimoto,https://teamtaiwan.dpp.org.tw/asset/types/elec...,data/raw/round3_20261019/cab91a155008312e422c....,mayor_data name=王美惠 field=threads,party_candidate_object_link,not_verified_not_posts_captured,2026-10-19

data/processed/snapshots/pre_bulletin_round5_20261019/meta_candidate_account_worklist_current.csv

,candidate_key,candidate_name,county_city,office_type,platform,official_urls,discovered_on,account_status,posts_status,window_count,followers_start,followers_end,updated_date
0,2026-C1-001,郭璽,臺北市,直轄市長,Facebook,,,not_yet_found_not_absent,not_collected_not_zero,,,,2026-10-19
1,2026-C1-001,郭璽,臺北市,直轄市長,Instagram,,,not_yet_found_not_absent,not_collected_not_zero,,,,2026-10-19
2,2026-C1-001,郭璽,臺北市,直轄市長,Threads,,,not_yet_found_not_absent,not_collected_not_zero,,,,2026-10-19
3,2026-C1-002,沈伯洋,臺北市,直轄市長,Facebook,https://www.facebook.com/1087764201093899 | ht...,https://puma.taipei/ | https://www.pumashen.or...,candidate_specific_source_link_target_content_...,not_collected_not_zero,,,,2026-10-19
4,2026-C1-002,沈伯洋,臺北市,直轄市長,Instagram,https://www.instagram.com/pumashen,https://teamtaiwan.dpp.org.tw/asset/types/elec...,candidate_specific_source_link_target_content_...,not_collected_not_zero,,,,2026-10-19
5,2026-C1-002,沈伯洋,臺北市,直轄市長,Threads,https://www.threads.com/@pumashen,https://teamtaiwan.dpp.org.tw/asset/types/elec...,candidate_specific_source_link_target_content_...,not_collected_not_zero,,,,2026-10-19
6,2026-C1-003,蕭文乾,臺北市,直轄市長,Facebook,,,not_yet_found_not_absent,not_collected_not_zero,,,,2026-10-19
7,2026-C1-003,蕭文乾,臺北市,直轄市長,Instagram,,,not_yet_found_not_absent,not_collected_not_zero,,,,2026-10-19
8,2026-C1-003,蕭文乾,臺北市,直轄市長,Threads,,,not_yet_found_not_absent,not_collected_not_zero,,,,2026-10-19
9,2026-C1-004,唐新民,臺北市,直轄市長,Facebook,,,not_yet_found_not_absent,not_collected_not_zero,,,,2026-10-19

data/processed/social_unresolved_links_20261019.csv

,candidate_key,candidate_name,url,source_url,reason
0,2026-C2-046,林國漳,https://www.facebook.com/share/p/1AzEm1mMiJ,https://2026openchang.tw/,legacy_share_or_content_link_excluded_from_acc...
1,2026-C2-046,林國漳,https://www.facebook.com/share/p/1CLe75GUvt,https://2026openchang.tw/,legacy_share_or_content_link_excluded_from_acc...
2,2026-C2-046,林國漳,https://www.facebook.com/share/p/1CeCP3zgr5,https://2026openchang.tw/,legacy_share_or_content_link_excluded_from_acc...
3,2026-C2-046,林國漳,https://www.facebook.com/share/p/1CgsQtEnzx,https://2026openchang.tw/,legacy_share_or_content_link_excluded_from_acc...
4,2026-C2-046,林國漳,https://www.facebook.com/share/p/1CnbWG74dr,https://2026openchang.tw/,legacy_share_or_content_link_excluded_from_acc...
5,2026-C2-046,林國漳,https://www.facebook.com/share/p/1DNsYJ2yNb,https://2026openchang.tw/,legacy_share_or_content_link_excluded_from_acc...
6,2026-C2-046,林國漳,https://www.facebook.com/share/p/1J9vMrYbYn,https://2026openchang.tw/,legacy_share_or_content_link_excluded_from_acc...
7,2026-C2-046,林國漳,https://www.facebook.com/share/p/1KmYvSseaB,https://2026openchang.tw/,legacy_share_or_content_link_excluded_from_acc...
8,2026|直轄市議員|新北市第1選舉區|游明諺,游明諺,https://www.facebook.com/share/14oUmftzKBj/?mi...,https://pridewatch.tw/candidate/%E6%B8%B8%E6%9...,share_or_content_or_group_link_not_resolved_to...
9,2026|直轄市議員|新北市第9選舉區|陳韋任,陳韋任,https://www.facebook.com/share/1VHY7MXBzY/?mib...,https://pridewatch.tw/candidate/weijenchenoa,share_or_content_or_group_link_not_resolved_to...

### Summary Stats

In [5]:
leads,pages,profiles,evidence,mayor,social,m,f,c=list(FRAMES.values())[:9];display(leads.validation_status.value_counts().to_frame('來源紀錄數'));display(profiles[['candidate_name','education_raw','experience_raw','source_year']]);print('第三方縣市長連結線索人數',mayor.candidate_key.nunique())

                                                    來源紀錄數
validation_status
source_saved_name_found_fields_and_identity_pen...    254
source_access_or_name_check_pending                    89

,candidate_name,education_raw,experience_raw,source_year
0,張以理,大同大學工業設計研究所 | 道明中學 | 前金國小,高雄市政府青年局局長 | 陳其邁競選總部發言人 | 蔡英文高雄競選總部執行長 | 立委趙天麟...,2026
1,林彥,國立臺灣科技大學 工學院學士 | 國立高雄應用科技大學 商學院學士 | 國立高雄科技大學 商...,曾於 高雄市政府 負責觀光旅宿管理 | 也曾在 高雄榮民總醫院 推動各行政區與醫療單位的公共...,2026
2,廖昶淳,國立臺灣師範大學地理學系碩士班 | 國立臺灣師範大學地理學系 | 國立斗六高級中學 | 雲林...,國立臺灣師範大學地理學系研究助理 | 農業部林業及自然保育署專案計畫經理 | 教育部數位學習...,2026
3,游明諺,♦︎私立明新科技大學,♦︎立法院國會 何志偉辦公室主任 | ♦︎台北市議員 鍾佩玲辦公室主任 | ♦︎台灣新動力智...,2026
4,陳彥廷,台大光電碩士,家樂福 15 年資深經歷,2026
5,蕭告,國立臺灣大學法律學系司法組畢業 | 加州大學舊金山法學院（UC Hastings）交換學生,蕭告律師事務所主持律師,2026
6,李昆穎,,,2026
7,陳俊諺,國防大學戰略暨國際事務研究所碩士 | 東海大學政治系 | 華江高中 | 新埔國中 | 文德國小,立法委員張宏陸服務處-助理 | 新北市議員石一佑服務處-執行長 | 新北市信賴之友會板橋分會...,2026
8,陳韋任,1. 國立臺灣科技大學建築研究所（碩士班） | 2. 中原大學建築系 | 3. 國立政治大學...,1. 立法委員蘇巧慧服務團隊副主任 | 2. 新北市議員陳永福服務團隊特助 | 3. 民進黨...,2026
9,林妤芬,美國加州大學柏克萊分校 | 法學碩士（LL.M.） | 輔仁大學財經法律系 | 法學士,新竹市政府廉政會報委員 | 新竹縣警局諮詢委員 | 弘準國際法律事務所 | 主持律師,2026
10,錢康明,國立台東大學兒童文學碩士 | 國立藝術學院（臺北藝術大學）戲劇系 藝術學學士,前新竹市文化局局長 | 台中國家歌劇院評鑑委員暨評議委員,2026
11,許纘融,中國醫藥大學製藥碩士畢業 | 成都中醫藥大學臨床醫學畢業,現於南投在地擔任專業看護與按摩師傅,2026
12,吳淳祐,東吳大學政治學系,立法委員王安祥 南投市主任 | 立法委員陳亭妃 助理 | 立法委員候選人周宏昌 助理 | 市...,2026
13,林鈺梅,國立中興大學企業管理學系 | 國立中興大學應用經濟學系碩士在職專班 | 順利完成碩士學位,日月光集團（ASE Group）旗下環隆電氣（USI）任職 | 科技業服務七年,2026
14,簡嘉佑,文化大學法律系,立委蔡其昌特別助理 | 前立委洪慈庸競總主任 | 立委候選人謝子涵競選總幹事 | 南投縣長候...,2026
15,陳又新,台大法律系及社工系雙學位學士 | 交大科法所碩士,,2026
16,陳力新,國立政治大學 EMBA 碩士 | 台大 E 勢泮後 EMBA 結業,國際企業負責人,2026
17,應佳妤,加拿大多倫多大學（University of Toronto） | 社會學（Sociolog...,臺北市議會圖書館實習生 | 臺北市議員辦公室實習生 | 臺北市議員服務團隊成員 | 2010...,2026
18,陳薈茗,朝陽科技大學管理學院學士,苗栗縣苑裡鎮第20屆西平里里長 | 苗栗縣陳品安議員特助 | 社團法人海線一家親環保協會理事...,2026
19,黎煥強,后庄國小 | 君毅中學 | 大葉大學機械系學士 | 中華大學工業管理學碩士,一、\t第19屆苗栗縣議員 | 二、\t第1屆頭份市民代表 | 三、\t明基友達集團瑞鼎科技...,2022_or_earlier_profile_not_currently_reconfirmed
20,陳思伃,輔仁大學英國語言學系,立法委員蕭美琴花蓮服務處助理 | 行政院東部聯合服務中心文化組專員 | 花蓮縣上騰工商英語科專任,2026
21,李明燦,清大電機碩士 | 成大電機學士 | 嘉義高中／水上國中／大同國小,台灣、美國與中國 3 地 25 年半導體電子業研發與品保主管 | 曾任聯電集團處長 | 唐恩...,2026

第三方縣市長連結線索人數 62

### Assertions

In [6]:
leads,pages,profiles,evidence,mayor,social,m,f,c=list(FRAMES.values())[:9]
assert len(leads)==343 and leads.candidate_key.nunique()==341
assert profiles.candidate_key.is_unique
assert not pages.duplicated(['candidate_key','fetch_url','page']).any()
assert not evidence.duplicated(['candidate_key','field','source_url']).any()
assert len(m)==1583 and m.candidate_key.is_unique
assert len(f)==31660 and not f.duplicated(['candidate_key','field']).any()
assert len(c)==1502 and c.candidate_key.is_unique
assert c.birth_date_supported_history.ne('').sum()==690 and c.sex_supported_history.ne('').sum()==690
assert c.birth_date_self_declared.ne('').sum()==1
assert c[c.candidate_name.eq('林鈺梅')].iloc[0].birth_date_self_declared=='1992-10-17'
assert mayor.verification_status.eq('third_party_discovery_lead_not_independently_reverified').all()
old=pd.read_csv(ROOT/'data/processed/snapshots/pre_source_expansion_20261019/candidate_fields_current.csv',dtype=str).fillna('').set_index(['candidate_key','field'])
now=f.set_index(['candidate_key','field'])
for field in ['sex','incumbency','first_time_this_office','first_time_any_office','administrative_experience','posts_Facebook','posts_Instagram','posts_Threads','followers']:
 pd.testing.assert_frame_equal(old.xs(field,level='field'),now.xs(field,level='field'))
accounts=FRAMES['data/processed/snapshots/pre_bulletin_round5_20261019/candidate_social_account_evidence_current.csv']
work=FRAMES['data/processed/snapshots/pre_bulletin_round5_20261019/meta_candidate_account_worklist_current.csv']
assert len(work)==4749 and not work.duplicated(['candidate_key','platform']).any()
assert not accounts.account_url.str.contains('/share/|/groups/|/posts/|/post/|/reel/').any()
assert work[['window_count','followers_start','followers_end']].eq('').all().all()
print('PASS：hash／列數／鍵／來源層級；歷史690人與無關欄位不變；4749筆平台工作單、分享與群組不當作帳號、未蒐集值不填零。')

PASS：hash／列數／鍵／來源層級；歷史690人與無關欄位不變；4749筆平台工作單、分享與群組不當作帳號、未蒐集值不填零。

2026-10-20 維護：重複檔案改用單一保存路徑，固定指紋同步更新；議員登記CSV排版換行改為空格，政黨標籤不變。本次已獨立從raw表格重建並比對全部1,502筆及16欄；未重跑本Notebook或整條研究流程，既有執行輸出屬先前執行紀錄。