# Data Description
- Background: 第八輪使用保存的CEC跨公職名冊、行政區代碼與當屆履歷交叉核對3人的身分。
- date received: 20261019本輪核對／抽出行政區碼；其餘來源原保存日期見各manifest，並非本輪重新下載。
- Path to data file: 下方固定PINS逐檔列示；原來源CEC https://db.cec.gov.tw/ 與競選頁URL見保存的manifest。
- Unit of observation: CEC候選人列、行政區代碼列、競選人物頁；manifest為擷取metadata。
- Sample period: 2014、2018、2020、2022官方歷史申報及2026競選頁；本輪核對2026-10-19。
- Known issues: 歷史學歷為當年級別；里長參選不能當議員參選；生日照官方原欄保存，不對1月1日自行調整或推測精度。競選頁自述與政府申報分開。任期與2026在任不從當選符號推定。
- Definition for each variable: CEC候選表無表頭，0–4為地區／選區碼、5為號次、6姓名、7政黨碼、8性別碼(1男2女)、9民國生日、10年齡、11出生地、12學歷級別、13現任旗標、14當選符號、15其他旗標；只使用有來源支持且本輪查驗的欄。行政區碼表0–4為相同階層碼、5地名。manifest為path/sha256/url/archive_member等檔案身分與來源metadata。
- Data path: PINS固定來源清單。
- Role: raw / acquisition metadata / unchanged extracted bytes。
- Verification status: 下方實際存在及SHA檢查，原始資料不覆寫。
- SHA-256: PINS逐檔列示。
- Next processing notebook: [第八輪處理](../code/cross_office_round8_20261019.ipynb)。

In [1]:
from pathlib import Path
import pandas as pd,json,hashlib,csv
from IPython.display import display
ROOT=next(p for p in [Path.cwd(),*Path.cwd().parents] if (p/'AGENTS.md').exists() and (p/'data').exists())
sha=lambda p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
PINS={'data/raw/cec_all_offices/107_elcand.csv': 'af38d1e0ca691d9e353fcfb3e154f0cbe1f178d6e796ce7441ef7cb52d02f1b9', 'data/raw/cec_all_offices/110_elcand.csv': 'b323d6713df428b57161e3b1b6799ebf25d679ef9948e8fe4fbb3fa0d7cfbc73', 'data/raw/cec_all_offices/112_elcand.csv': 'f355705254d5ca457d4fe130b77983b769602126b10713e7c968889d2d52530c', 'data/raw/cec_all_offices/095_elcand.csv': '2106bc9400f7d64784595799d2404496186cffaa56d82b14554d172d781f1b60', 'data/raw/cec_all_offices/073_elcand.csv': '3d5391d0276093fb4721778d84b8d36c4569457d1d865ee14d45805939d9e5bd', 'data/raw/cec_all_offices/087_elcand.csv': '58616de64001f72a3f16be830a15aceb42cecdc63b239ce234c13c3ba408e307', 'data/raw/cec_all_offices_manifest.json': '726d464020ff8f850ce39685bb70926c8529712f75c1833ac5b5c6d795354ed7', 'data/raw/cross_office_round8_20261019/2022_village_elbase.csv': '4d0afbae084ccd77785ebe9a878eadb7e97e828555926d92866dddbfb4b14e79', 'data/raw/cross_office_round8_20261019/manifest.json': '6c3b1612b234da8a0ab7e799fe7367bc6ebaae9ef48f190144fbb09ed4124022', 'data/raw/social_followup_round6_20261019/manifest.json': 'f5471133039402a9e21143f23d30b70b645ddf3406805e19f78764f5b2063746', 'data/raw/kmtks_web_20261019/manifest.json': 'a519c5d80a86591bec6da77b7f031e56c5c10fa9e79245e5e1b74332a4709fb8', 'data/raw/social_followup_round6_20261019/b39ba23e64e7bb9ca8b3.html': 'c0a7c18159f0dc6e66dfcca6757183d0eb26f66487871cd5fb635c1c4e72bdd6', 'data/raw/social_followup_round6_20261019/0277960ed4f266884bad.html': 'f31d0165ee321abb26ce8b9cb6816b9dbbd4655fc9a7f9ddc309a75bcbc12c90', 'data/raw/kmtks_web_20261019/05.txt': '410ff727927bf36c12bc505782951ead7cfb91b88b0e1d28e4802249c7f99b26'}
for p,h in PINS.items():assert sha(p)==h,p
print('Source file hashes checked:',len(PINS))

Source file hashes checked: 14

## Change for Your Own Data
只讀固定來源，不下載或替換。

## Summary

### Sample

In [2]:
TABLES={}
for p in PINS:
 if p.endswith('.csv'):
  with (ROOT/p).open(encoding='utf-8-sig') as f:rows=list(csv.reader(f))
  d=pd.DataFrame(rows);TABLES[p]=d;print(p);display(d.head(10))
meta=json.loads((ROOT/'data/raw/cross_office_round8_20261019/manifest.json').read_text());display(pd.DataFrame([meta]))

data/raw/cec_all_offices/107_elcand.csv

   0    1   2    3     4   5    6    7  8        9   10   11  12 13 14 15
0  63  000  01  000  0000   1  林延鳳   16  2  0710417  40  臺灣省  碩士  N  *
1  63  000  01  000  0000   2  陳賢蔚   16  1  0660712  45  高雄市  大學  Y  *
2  63  000  01  000  0000   3  李光輝  999  1  0511110  59  高雄市  博士  N
3  63  000  01  000  0000   4  林杏兒    1  2  0700105  41  臺北市  碩士  N  *
4  63  000  01  000  0000   5  汪志冰    1  2  0460420  65  臺中市  碩士  Y  *
5  63  000  01  000  0000   6  林世宗   16  1  0480613  63  臺北市  碩士  Y  *
6  63  000  01  000  0000   7  陳重文    1  1  0660924  45  臺北市  博士  Y  *
7  63  000  01  000  0000   8  劉仕傑  267  1  0690209  42  臺灣省  碩士  N
8  63  000  01  000  0000   9  陳慈慧   16  2  0721122  38  臺北市  大學  Y  *
9  63  000  01  000  0000  10  鍾佩玲   16  2  0680327  43  新北市  碩士  Y  *

data/raw/cec_all_offices/110_elcand.csv

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,10,002,12,000,0000,1,沈志弘,1,1,0530209,58,臺灣省,高中(職),N,*,
1,10,002,12,000,0000,2,陳傑麟,90,1,0541108,56,臺灣省,碩士,Y,,
2,10,002,13,000,0000,1,游吉祥,1,1,0520528,59,臺灣省,大學,N,*,
3,10,004,12,000,0000,1,林世偉,999,1,0560101,55,臺灣省,高中(職),N,,
4,10,004,12,000,0000,2,劉建民,1,1,0651130,45,臺灣省,大學,Y,*,
5,10,004,13,000,0000,1,張益生,1,1,0640610,47,臺灣省,大學,Y,*,
6,10,004,13,000,0000,2,張雁萍,999,2,0620515,49,臺灣省,高中(職),N,,
7,10,005,08,000,0000,1,劉美蘭 Iwan·Sigiy,1,2,0511023,60,臺灣省,專科,N,*,
8,10,005,08,000,0000,2,黃月娥 Yuma’Baysu’,999,2,0460708,65,臺灣省,高中(職),Y,,
9,10,008,07,000,0000,1,王榮儀,999,1,0630222,48,臺灣省,大學,N,,

data/raw/cec_all_offices/112_elcand.csv

   0    1   2    3     4  5    6    7  8        9   10    11       12 13 14 15
0  09  007  00  010  0001  1  陳春開   16  1  0440621  67  金馬地區  高中(職)以下  N
1  09  007  00  010  0001  2  陳美貴    1  1  0520630  59  金馬地區  高中(職)以下  Y  *
2  09  007  00  010  0002  1  曹爾嵐    1  1  0450325  66  金馬地區  高中(職)以下  Y  *
3  09  007  00  010  0003  1  陳泰英    1  1  0460909  65  金馬地區  高中(職)以下  Y
4  09  007  00  010  0003  2  陳震森    1  1  0671106  43  金馬地區    高中(職)  N  *
5  09  007  00  010  0004  1  陳善安    1  1  0530917  58  金馬地區    高中(職)  Y  *
6  09  007  00  010  0004  2  周治孝  999  1  0750412  36   桃園市       大學  N
7  09  007  00  010  0005  1  黃寶清    1  1  0550530  56  金馬地區  高中(職)以下  Y  *
8  09  007  00  010  0006  1  劉用順  999  1  0510304  60  金馬地區  高中(職)以下  Y  *
9  09  007  00  010  0007  1  陳智偉    1  1  0681108  42  金馬地區       大學  Y  *

data/raw/cec_all_offices/095_elcand.csv

   0    1   2    3     4  5     6    7  8        9   10   11     12 13 14 15
0  10  020  01  000  0000  1   陳泰山  999  1  0381005  70  臺灣省     碩士  N
1  64  000  06  000  0000  1   李鎔任  341  1  0411222  67  臺南市     專科  N
2  67  000  01  000  0000  1   康淑敏  191  2  0480625  60  高雄市     專科  N
3  66  000  03  000  0000  1   朱立凡  319  1  0690414  39  臺灣省     大學  N
4  63  000  05  000  0000  1   楊烱煌  292  1  0350304  73  臺中市     碩士  N
5  10  015  01  000  0000  1   蕭嘉豪  312  1  0770708  31  新北市  高中(職)  N
6  63  000  08  000  0000  1   蕭曉玲  348  2  0530919  55  臺灣省     大學  N
7  10  005  01  000  0000  1  鍾林芷綸  355  2  0550417  53  新北市  高中(職)  N
8  10  016  01  000  0000  1   呂應宏  348  1  0400222  68  臺灣省     大學  N
9  64  000  01  000  0000  1   晏揚清  101  1  0480103  60  臺中市     博士  N

data/raw/cec_all_offices/073_elcand.csv

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,'10,'004,'12,'000,'0000,1,黃比德,'1,'1,'0600413,43,臺灣省,高中,N,,
1,'10,'004,'12,'000,'0000,2,柔夏‧布待Rosya.Butay,'999,'1,'0470616,56,臺灣省,其他,N,,
2,'10,'004,'12,'000,'0000,3,雲翔,'999,'1,'0530707,50,臺灣省,專科,N,,
3,'10,'004,'12,'000,'0000,4,范坤松,'1,'1,'0340507,69,臺灣省,高中,N,*,
4,'10,'004,'13,'000,'0000,1,趙一先Obay a Awi’,'1,'1,'0540905,49,臺灣省,碩士,Y,*,
5,'10,'004,'13,'000,'0000,2,張定中,'999,'1,'0520625,51,臺灣省,其他,N,,
6,'10,'004,'13,'000,'0000,3,凱撒巴燕,'16,'1,'0500611,53,臺灣省,其他,N,,
7,'10,'005,'08,'000,'0000,1,林國雄,'999,'1,'0460523,57,臺灣省,大學,N,,
8,'10,'005,'08,'000,'0000,2,黃月娥,'1,'2,'0460708,57,臺灣省,高中,Y,*,
9,'10,'008,'07,'000,'0000,1,史清水,'1,'1,'0390517,64,臺灣省,大學,Y,*,

data/raw/cec_all_offices/087_elcand.csv

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,'10,'004,'12,'000,'0000,1,柔夏．布待Rosya．Butay,'999,'1,'0470616,60,臺灣省,高中(職)以下,N,,
1,'10,'004,'12,'000,'0000,2,劉建民,'1,'1,'0651130,41,臺灣省,大學,N,*,
2,'10,'004,'13,'000,'0000,1,達陸．翡述,'999,'1,'0600411,47,臺灣省,專科,N,,
3,'10,'004,'13,'000,'0000,2,張益生,'999,'1,'0640610,43,臺灣省,大學,N,*,
4,'10,'004,'13,'000,'0000,3,凱撒巴燕,'999,'1,'0500611,57,臺灣省,高中(職)以下,N,,
5,'10,'004,'13,'000,'0000,4,張定國,'999,'1,'0580101,49,臺灣省,專科,N,,
6,'10,'005,'08,'000,'0000,1,黃月娥Yuma．Vaiso,'1,'2,'0460708,61,臺灣省,高中,Y,*,
7,'10,'005,'08,'000,'0000,2,楊政孝,'999,'1,'0600608,47,臺灣省,高中,N,,
8,'10,'008,'07,'000,'0000,1,王榮儀,'999,'1,'0630222,44,臺灣省,大學,N,,
9,'10,'008,'07,'000,'0000,2,全文才Balan．Soqluman,'1,'1,'0520325,55,臺灣省,大學,N,*,

data/raw/cross_office_round8_20261019/2022_village_elbase.csv

    0    1   2    3     4    5
0  00  000  00  000  0000   全國
1  63  000  00  000  0000  臺北市
2  63  000  00  010  0000  松山區
3  63  000  00  010  0002  莊敬里
4  63  000  00  010  0003  東榮里
5  63  000  00  010  0004  三民里
6  63  000  00  010  0005  新益里
7  63  000  00  010  0006  富錦里
8  63  000  00  010  0007  新東里
9  63  000  00  010  0008  富泰里

,source_url,original_archive,archive_sha256,archive_member,path,sha256,extracted_date,method
0,https://db.cec.gov.tw/,election/raw/cec/votedata.zip,84740535b1f4a9a8fec8ebfe8f7577889837b7639cd7f5...,votedata/votedata/voteData/2022-111年地方公職人員選舉/V...,data/raw/cross_office_round8_20261019/2022_vil...,4d0afbae084ccd77785ebe9a878eadb7e97e828555926d...,2026-10-19,extract unchanged bytes from previously preser...

### Summary Stats

In [3]:
for p,d in TABLES.items():
 print(p, 'rows',len(d),'columns',len(d.columns),'exact duplicate rows',int(d.duplicated().sum()));display(pd.DataFrame({'type':d.dtypes.astype(str),'empty':d.eq('').sum()}))
print('Candidate names may repeat across elections; that is not an entity identity assertion.')

data/raw/cec_all_offices/107_elcand.csv rows 683 columns 16 exact duplicate rows 0

   type  empty
0   str      0
1   str      0
2   str      0
3   str      0
4   str      0
5   str      0
6   str      0
7   str      0
8   str      0
9   str      0
10  str      0
11  str      0
12  str      0
13  str      0
14  str      0
15  str      0

data/raw/cec_all_offices/110_elcand.csv rows 50 columns 16 exact duplicate rows 0

   type  empty
0   str      0
1   str      0
2   str      0
3   str      0
4   str      0
5   str      0
6   str      0
7   str      0
8   str      0
9   str      0
10  str      0
11  str      0
12  str      0
13  str      0
14  str      0
15  str      0

data/raw/cec_all_offices/112_elcand.csv rows 14021 columns 16 exact duplicate rows 0

   type  empty
0   str      0
1   str      0
2   str      0
3   str      0
4   str      0
5   str      0
6   str      0
7   str      0
8   str      0
9   str      0
10  str      0
11  str      0
12  str      0
13  str      0
14  str      0
15  str      0

data/raw/cec_all_offices/095_elcand.csv rows 410 columns 16 exact duplicate rows 0

   type  empty
0   str      0
1   str      0
2   str      0
3   str      0
4   str      0
5   str      0
6   str      0
7   str      0
8   str      0
9   str      0
10  str      0
11  str      0
12  str      0
13  str      0
14  str      0
15  str      0

data/raw/cec_all_offices/073_elcand.csv rows 58 columns 16 exact duplicate rows 0

   type  empty
0   str      0
1   str      0
2   str      0
3   str      0
4   str      0
5   str      0
6   str      0
7   str      0
8   str      0
9   str      0
10  str      0
11  str      0
12  str      0
13  str      0
14  str      0
15  str      0

data/raw/cec_all_offices/087_elcand.csv rows 68 columns 16 exact duplicate rows 0

   type  empty
0   str      0
1   str      0
2   str      0
3   str      0
4   str      0
5   str      0
6   str      0
7   str      0
8   str      0
9   str      0
10  str      0
11  str      0
12  str      0
13  str      0
14  str      0
15  str      0

data/raw/cross_office_round8_20261019/2022_village_elbase.csv rows 8147 columns 6 exact duplicate rows 0

  type  empty
0  str      0
1  str      0
2  str      0
3  str      0
4  str      0
5  str      0

Candidate names may repeat across elections; that is not an entity identity assertion.